### ISSUE TITLE
Lights not being continuously updated/adapted

### ISSUE THREAD

**Issue by badabingbadabongha** [basnijholt/adaptive-lighting#1014]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
No logs to be found even though I enabled debug logging…
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```

lights: - light.bad_deckenlampe - light.bogenlampe - light.flur_deckenlampe - light.gummibaum - light.kamin_links_oben - light.kamin_links_unten - light.kamin_rechts_oben - light.kamin_rechts_unten - light.kammer_licht - light.kleiderschrank - light.rudergerat - light.sofa - light.spiegel - light.treppe_links - light.treppe_rechts interval: 15 transition: 0 initial_transition: 0 min_brightness: 1 max_brightness: 100 min_color_temp: 2202 max_color_temp: 4000 prefer_rgb_color: false sleep_brightness: 1 sleep_rgb_or_color_temp: color_temp sleep_color_temp: 1000 sleep_rgb_color: - 255 - 56 - 0 sleep_transition: 1 transition_until_sleep: false sunrise_time: null min_sunrise_time: null max_sunrise_time: null sunrise_offset: 0 sunset_time: null min_sunset_time: null max_sunset_time: null sunset_offset: 0 brightness_mode: default brightness_mode_time_dark: 900 brightness_mode_time_light: 3600 take_over_control: false detect_non_ha_changes: false autoreset_control_seconds: 60 only_once: false adapt_only_on_bare_turn_on: false separate_turn_on_commands: true send_split_delay: 1 adapt_delay: 1 skip_redundant_commands: false intercept: true multi_light_intercept: true include_config_in_attributes: true name: rest
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:

As you can see in my configuration I have disabled both only_once and adapt_only_on_bare_turn_on. No lights are marked as manual control while this bug occurs. No matter what way I turn on a light, weather it’s by using the turn on service or by using my physical IKEA Tradfri five button switch (the latter is my main method of turning on lights), The light will adapt right away and turn on, but only once. Turning on the lights using turn_on on a device id or on an entity id doesn’t make a difference, lights are still only adapted once and not continuously updated. I have used AL for years since it was still called CL and I hit my ups and downs with different issues but the continues adapting always worked fine. Sometimes I would have to toggle the AL switch often on in order to update lights that got stuck on certain values but then they would work just fine afterwards but now toggling that same switch doesn’t even force my lights, of which none of them are being updated continuously, to be adapted. These days, the only way to force them to adapt is by calling the set_manual_control service which makes me think this bag has something to do with the manual control. But then again as I said, none of the affected lights are marked as manually controlled. Even when I mark them as manually controlled and the set autoreset time puts them back into not being marked as manually controlled The lights still don’t get adapted.

5. Steps to reproduce the behavior:

 - have IKEA Tradfri lights
 - Have them adapted by a AL switch with my config
 - Turn on lights using a physical switch
 - Watch them being adapted once
 - Noticed them not being adapted continuously

**Comment by Wireheadbe** [comment]
Can you try downgrading to 1.21.3 (previous version) and restarting home-assistant? Do you still have that behavior?

**Comment by badabingbadabongha** [comment]
> Can you try downgrading to 1.21.3 (previous version) and restarting home-assistant? Do you still have that behavior?

How would one go about downgrading an integration?

**Comment by danielbrunt57** [comment]
> How would one go about downgrading an integration?

In HACS...
![image](https://github.com/basnijholt/adaptive-lighting/assets/49846893/4b7ea662-cce1-4bee-b223-e14748d32090)

![image](https://github.com/basnijholt/adaptive-lighting/assets/49846893/3de659be-357b-4697-b73e-07055ca15447)

**Comment by badabingbadabongha** [comment]
@danielbrunt57 Thanks for the instructions, good to know! I did resolve the issue in the mean time though by deleting all my instances of AL and then creating new ones which separate lights that don’t do color from those which do…
