### ISSUE TITLE
Allow milliseconds in `adapt_delay`

### ISSUE THREAD

**Issue by EmatraDev** [basnijholt/adaptive-lighting#104]
Hi everyone,

I am experiencing some problems with my setup which consists of two Hue Bridges and several Innr Gu10 lights.
Basically whenever I turn on the lights of one room (which can contain up to 14 inner lights), the lights don't reach the right temperature/brightness because Hue Bridges can fire only a limited number of requests per second (I read somewhere about 7 requests per second). This results that only a limited number of lights reach the right temperature/brightness and so I am forced to fire the set_manually event until all of them are ok. Unfortunately I cannot use default hue light groups, because whenever I use them, adaptive lighting causes the innr to flash exactly every 'interval' seconds.

I am asking if there is the possibility to delay the activation of the lights of a configurable amount of seconds: e.g. turn on light_1, wait 1 sec, turn on light_2, wait another 1 sec, and so on...
Unfortunately I couldn't find a way to do so.

Thanks for your help.

**Comment by TheAlphaLaw** [comment]
I have the same request, but using a Conbee II. Even with that, I run into a request issue constantly.  My limit seems to be 4 groups (of 3 lights each). Typically the 3 and or 4 set of lights will not change temperature when all groups are turning on. I have nearly 100 hue fixtures in my home.

I'd also like to request a delay in the periodic temperature/brightness requests, as this can bog down my network entirely. It would be great to introduce custom delays for each group's periodic transition.

**Comment by TheAlphaLaw** [comment]
> This is finished in 1.4.1 and probably older versions with `adapt_delay` and `interval` settings set appropriately.

Thank you, adapt delay should solve this issue if set per light. Would be more useful if we could set the delay in milliseconds also.

**Comment by th3w1zard1** [comment]
@TheAlphaLaw How so? What's the need for millisecond accuracy? `adapt_delay` is already inaccurate as a light is only adapted on each interval.

**Comment by TheAlphaLaw** [comment]
> @TheAlphaLaw How so? What's the need for millisecond accuracy? `adapt_delay` is already inaccurate as a light is only adapted on each interval.

Lights are not adapted based on interval when initially turning on the lights. I have my lights set to adapt in 2 when turned on and every interval, longer periods create issues with responsiveness. 

The Zigbee flood created on my Zigbee Network when turning on 10+ lights and then adapting brightness and temperature is solved even with as little as a 250ms delay. Millisecond accuracy isn't necessarily needed but it would make the difference in light adaption less noticeable between multiple lights in the same area. So they would all still appear to adapt at the same time but the delay would solve the flooding issue.

**Comment by th3w1zard1** [comment]
We could easily add millisecond delays, for backwards compatibility reasons we'd have to change `adapt_delay` to be a float though. Is that acceptable?

I've never thought about having different adapt delays per light - that's a really good idea! I have noticed that my zigbee network lags initially when I restart HASS.

**Comment by TheAlphaLaw** [comment]
> We could easily add millisecond delays, for backwards compatibility reasons we'd have to change `adapt_delay` to be a float though. Is that acceptable?
> 
> I've never thought about having different adapt delays per light - that's a really good idea! I have noticed that my zigbee network lags initially when I restart HASS.

I don't think changing it to a float would have any negative effects, but I will leave that to you. Happy with anything you are willing to implement 😁

Yeah, per light would be great. It technically could be done right now but the configuration would become cumbersome quickly (I have 30+ light groups and over 80 Zigbee lights). 

Everyday my wife will turn on all the kitchen lights via tablet or voice and often I see 1 group not adapt (12 total lights). I'll test the 1 second delay for all the lights and see how that works. I may need to separate each group out, though.

**Comment by th3w1zard1** [comment]
If you utilize regex and copy/paste it shouldn't be too difficult to copy your config for all of your light groups. Are you using the yaml file to store your config? If not, for 30+ light groups I highly recommend you do so.

**Comment by th3w1zard1** [comment]
I quickly added this feature to the basic community PR at #459, feel free to test it and ensure it works the way you'd like.

**Comment by TheAlphaLaw** [comment]
> If you utilize regex and copy/paste it shouldn't be too difficult to copy your config for all of your light groups. Are you using the yaml file to store your config? If not, for 30+ light groups I highly recommend you do so.

I've been using the GUI config but can take a look at YAML option. Would be easier to manage, honestly. 

> I quickly added this feature to the basic community PR at #459, feel free to test it and ensure it works the way you'd like.

Sure, I'll take a look this weekend. Thank you!

**Comment by TheAlphaLaw** [comment]
> I quickly added this feature to the basic community PR at #459, feel free to test it and ensure it works the way you'd like.

Tested an it seems to work. Live pushed still needs GUI adjustments. GUI displays "seconds".
