### ISSUE TITLE
Neither a switch nor a light was provided in the service call

### ISSUE THREAD

**Issue by Jleagle** [basnijholt/adaptive-lighting#1061]
So today i have been running into this message a lot..

> adaptive-lighting: Neither a switch nor a light was provided in the service call. If you intend to adapt all lights on all switches, please inform the developers at https://github.com/basnijholt/adaptive-lighting about your  use case. Currently, you must pass either an adaptive-lighting switch or  the lights to an `adaptive_lighting` service call.

https://github.com/basnijholt/adaptive-lighting/blob/ccf465251c5c17b8b2f021b5f57322f8f89baed7/custom_components/adaptive_lighting/switch.py#L317

My use case is that sometimes i want to disable the whole extension, and i think to do so i need to list every light/switch. It would be great if there was a way to just do them all in one go, this way i wont have to edit the JSON payload in multiple places every time i add/remove a light in the house.

Thanks,

**Comment by djurny** [comment]
Hi there,
To understand your case a little better; do you want to really disable the integration? Or do you want to disable all instances of the integration? Or do you want to disable AL functionality of all instances of the AL integration?

1. Disabling an integration is - I think - not possible in HASS. You can _delete_ an integration or you can disable an _instance_ of an integration. Most likely this is not what you want, as to roll back this action would involve adding the integration "from scratch".
1.  Disabling an instance of an integration will have an effect on all the entities provided by the integration instance. Most likely this is not what you want, as all entities related to the integration instance will become `Unavailable`, so any automation, script or dashboard will not function as expected.
1. Disabling the function of the instance of an AL integration can be done by `switch.turn_off`ing of the `switch.adaptive_lighting_name`. This is most likely what you are looking for?

For #3 you could consider making one group containing all `switch.adaptive_lighting_names`es and using `switch.turn_on` or `switch.turn_off` to enable/disable the group. That will enable/disable all AL switches, resulting in disabling the AL functionality of all AL integration instances.
Alternatively for #3 you could also make a button on your dashboard that will do a `service: switch.turn_on` with templated `entity_id`s. You can list all integration instances of a certain integration with `integration_entities('adaptive_lighting')` and map the names to `switch` `entity_id`s.

Hope that helps,
Groetjes,

**Comment by Jleagle** [comment]
Thanks for the info, you were right, number 3 is what i was after.
Is there much difference between just toggling the switch for that light vs setting set_manual_control?

**Comment by djurny** [comment]
Hi there,
Using `manual_control` you might get a similar outcome, but it makes more sense to turn off the `switch.adaptive_lighting_x` of each instance. That way you are asssured that AL does not adjust anything.
I am a NodeRed n00b, but pretty sure you'd be able to make that happen in there as well.
Hope that helps,
Groetjes,
