### ISSUE TITLE
Colour Temp and Transition Issues

### ISSUE THREAD

**Issue by dennyha** [basnijholt/adaptive-lighting#107]
I have been using this integration for a while now with a set of Yeelight 1S bulbs around the house and it has been flawless (great job).  However, I have now swapped out all my Yeelight bulbs for Lifx bulbs (mini colour) and I am having a few issues.  I cant find anyone else that has had the same problems so far.

My issue is that the temperature ranges do not match the true representation of what the bulb is doing. I can set the minimum kelvin range to 1500k (which is the warmest colour possible for this bulb in the lifx app) in the integration but it is much cooler than it should be.  The only way I can get it to be warmer is by forcing it to use rgb colours and then the closest I can get to 1500k is by setting the min temp to 3250k.  It still doesnt look right but its the closest I can get it.

The other issue I have involves the transition times, these seem to be ignored with the lifx bulbs.  I have a turn on transition time of 2s for all bulbs in the integration but they come on/go off instantaneously.  

Firmware for all the lifx bulbs is 3.6.

**Comment by basnijholt** [comment]
This issue is not related to this project but rather the HA implementation or firmware of your lights.

I would report it with the HA main repo.
