### ISSUE TITLE
Last comment on the pull request for the core

### ISSUE THREAD

**Issue by haivala** [basnijholt/adaptive-lighting#108]
> I think there might be benefits to restart this pull if it still valid. It now has 160 ish commits. So it has gone through many changes since it was opened. It would be good to get something small in to start with.

**Comment by basnijholt** [comment]
Unfortunately, @frenck locked the PR (https://github.com/home-assistant/core/pull/40626), so I cannot even respond myself :-(

**Comment by haivala** [comment]
Maybe just make a new one?

I'll close this. just made sure you know this.
