### ISSUE TITLE
Cannot remove adaptive lighting switch from HA

### ISSUE THREAD

**Issue by backcountrymountains** [basnijholt/adaptive-lighting#109]
I tried to remove an adaptive_lighting switch by commenting it out in the YAML, but it still shows up in HA.
The following switch still shows up in HA:
```
adaptive_lighting:
  # - name: Dining
    # <<: *lightsettings
    # interval: 270
    # lights:
      # - light.dining_lights_template
```
I've actually deleted the whole switch from my YAML config, but it still shows up in HA:

switch.adaptive_lighting_dining | off | brightness_pct: null color_temp_kelvin: null color_temp_mired: null rgb_color: null xy_color: null hs_color: null sun_position: null friendly_name: Adaptive Lighting: Dining icon: mdi:theme-light-dark
-- | -- | --

How do I permanently remove adaptive lighting switches that I no longer want?

Really like this component. 
Thanks.

**Comment by solidssss** [comment]
I have the same problem and also want help

**Comment by backcountrymountains** [comment]
So adaptive lighting now shows up on the integration page (configuration-->integrations). I was able to delete the switch from there by selecting the switch I didn't want, clicking the 3 vertical dots and selecting the red delete option.
