### ISSUE TITLE
Select Lights by Name rather than Entity ID

### ISSUE THREAD

**Issue by zombielinux** [basnijholt/adaptive-lighting#11]
For those of us with a lot of zigbee lights (I think I'm in the 20's now), would it be possible to list all lights by their name including the entity ID?

I think that would be somewhere around line 96 in [config-flow.py](https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/config_flow.py). 

That way it wouldn't be this endless back and forth referencing names to long hex strings while setting it up/modifying it. 

EDIT: This might only apply to zigbee2mqtt users.

**Comment by basnijholt** [comment]
> EDIT: This might only apply to zigbee2mqtt users.

Thanks for the suggestion, but I am afraid I won't do this precisely because of what you wrote.

**Comment by broyuken** [comment]
Could you add a search bar at the top when adding lights to the switches instead of just a full list of all lights that we have to scroll through?

**Comment by basnijholt** [comment]
That is a good request but it should be asked in the homeassistant/frondend repo because it’s beyond what I can implement in a integration.

**Comment by basnijholt** [comment]
Basically, they would have to add this functionality in `cv.multi_select`.
