### ISSUE TITLE
test button

### ISSUE THREAD

**Issue by dennisbrouwer91** [basnijholt/adaptive-lighting#115]
Hi,

I love Adaptive Lighting, it's great and all the options work amazing, thanks for all the hard work. I had an idea : In the UI you can set all kinds of things, min brightness, min color for example. But it's very, very hard to visualise what that will exactly do when you set it. Maybe a "Test" button would be nice, to set the lights to the set settings for example : 

- Test lights at min_brightness
- Test lights at max_brigtness
- Test lights at min_color
- Test lights at max_color

Or something.

What do you think?

**Comment by seanmccabe** [comment]
You can do this with the developer tools, just set the light to the value you are after, then can set them back.
