### ISSUE TITLE
Keep reporting Kelvin value when adaptive lighting is off

### ISSUE THREAD

**Issue by Patrick1610** [basnijholt/adaptive-lighting#116]
I have scenarios in which I don’t want adaptive lighting to control the temperature of my lights so I disable the adaptive lighting button. The only downside it has is that it doesn’t only stop from controlling the lights but also reporting the kelvin state, which in some cases I’d like to have continuously. 

Another solution would be that the integration is allowed to disable brightness / color / sleep at the same time, while adaptive lighting is on, so I can keep adaptive lighting on (brightness and sleep are always disabled in my use case). Now the app doesn’t seem to handle this to well. 

![F4D737BC-A988-4048-8553-A18540F9B5C1](https://user-images.githubusercontent.com/6585375/118239783-7e307400-b49a-11eb-850e-6bffabae0096.png)

**Comment by Patrick1610** [comment]
Extra info: 

This is the error I get in the logging when Adaptice lighting is on, but color/brightness/sleep is off and I turn on a light manually. 

--------------------------------

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1217 
Integration: Adaptive Lighting 
First occurred: 22 May 2021, 11:53:08 (194 occurrences) 
Last logged: 10:13:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1217, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'

**Comment by kreene1987** [comment]
I do this via a Default AL instance and don't have any lights controlled by it.

**Comment by Patrick1610** [comment]
You mean you have multiple AL versions running? Can you elaborate on that? How can I do that? :)

**Comment by Patrick1610** [comment]
Oh man, I feel pretty stupid.. I was thinking way to complicated (installing the integration twice or something like that) but I found out! Thanks for pointing me in that direction 🙏🏼

**Comment by kreene1987** [comment]
Yep, the beauty of this add-on is in multiple instances per unique set of inputs! Cheers! You might close or mark as solution so the developer isn't tracking anymore.
