### ISSUE TITLE
Adaptive Lighting not working after HA update

### ISSUE THREAD

**Issue by halfcab1981** [basnijholt/adaptive-lighting#120]
Hi,
yesterday I updated my Home Assistant core and after the update, adaptive lighting was no longer available.

When I open the entity I see this message 
![image](https://user-images.githubusercontent.com/36119320/119070226-e814c480-ba2a-11eb-8b36-4c5fdd1cbc80.png)

Log is attached. Any help would be most appreciated! Thanks
[home-assistant.log](https://github.com/basnijholt/adaptive-lighting/files/6519552/home-assistant.log)

**Comment by fwump38** [comment]
Hi - just saw your issue and I was having this too. Idk if Adaptive Lighting was missing from HACS for you like it was for me but adding it back let me "install" it again and get the latest version which addressed this and other issues for me.

More discussion on this in #112

**Comment by halfcab1981** [comment]
Thanks. I fixed it by updating HACS and the Adaptive Lighting component within.
