### ISSUE TITLE
Binary lights 

### ISSUE THREAD

**Issue by RubenKelevra** [basnijholt/adaptive-lighting#123]
I'm using two 60 W (real watts) LEDs with daylight temperature to boost the brightness in the room to create bright enough lighting even in winter. They are pointed at the ceiling to avoid strong shadows everywhere.

It would be great if I could add those switched regular bulbs to the automation with a light output number in lux. This way they can get turned on over the day without manual intervention.

**Comment by RubenKelevra** [comment]
I'm currently in the process of doing version 2. This will be added/fixed.

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.

**Comment by basnijholt** [comment]
This actually sounds like something that be accomplished with an automation. It also sounds like a niche application so I will close this now as a wont-fix until someone else will implement this.
