### ISSUE TITLE
Prevent Adaptive lighting from updating light during power on transition

### ISSUE THREAD

**Issue by Patrick1610** [basnijholt/adaptive-lighting#125]
I currently have a couple of automations which make my lights go on when the room gets darker, because I want more control than the brightness switch provides. I do however use the temperature/color switch from adaptive lighting. 
When the automation turns the light on with a transition of 150s, adaptive lighting seems to override / skip that transition and turns the lights on with the specified update time (e.g. 10s) for color temperature and updates its temperature.
- when all switches are off, except adaptive lighting (brightness, color and sleep) this occurs
- when adaptive lighting is off (no matter what the state of the other switches is) this does not occur
- Long initial turn on time is not the right solution, because when for example I walk into the hallway I don't want the temperature to update over 150s. 

Reproduce: 
- automation with long turn on time (150s to 100%)
- short update time in Adaptive lighting (transition 5, interval 10)

**Comment by kreene1987** [comment]
Potential workaround would be to turn off the adaptive lighting for the period of time, then turn back on. Just a thought!

**Comment by Patrick1610** [comment]
Thanks! That is indeed what I have been using, but especially with new automations and multiple existing transition times, this is not a great method.

**Comment by RubenKelevra** [comment]
This sounds like a common scenario.

I think what you want is a method to softstart all (or a subset) of the configured lights via this component as a service, right?

That's basically what I want too. But automatically by using a brightness sensor for the feedback.

Have a look at #122. Would this solve your problem?

**Comment by callumgare** [comment]
I’d also love this. @RubenKelevra is it not possible when light is turned on for AL to check to check if that turn_on service call has set a transition time and if so respect that by also using that transition time when adapting the light?

**Comment by basnijholt** [comment]
Instead of calling `light.turn_on` with the 150s transition, you can [call `adaptive_lighting.apply` with `transition: 150` and `turn_on_lights: true` ](https://github.com/basnijholt/adaptive-lighting#adaptive_lightingapply).

This should fix your problem. Sorry it took >2 years to reply 😅
