### ISSUE TITLE
Ability to adjust horizon for max brightness and min color temp

### ISSUE THREAD

**Issue by jacob3089** [basnijholt/adaptive-lighting#127]
I was wondering if you could consider allowing adjustment of the horizon for max brightness and min color temp. Right now it is at sunrise and sunset without the ability to configure it. I would like to both have a cooler color temp at sunset, getting warmer into the evening and also not have peak light brightness right at sunrise. I have a proposal for enabling this functionality below. Two configurable settings would need to be added. 

brightness_horizon_offset: percent above horizon where max brightness will be reached; default 0.

color_temp_horizon_offset: percent below horizon where min color temp will be reached; default 0.

I have one option of a working implementation with the code below.

     def calc_brightness_pct(self, percent: float, is_sleep: bool) -> float:
        """Calculate the brightness in %."""
        if is_sleep:
            return self.sleep_brightness
        if percent > (0 + brightness_horizon_offset):
            return self.max_brightness
        delta_brightness = self.max_brightness - self.min_brightness
        return (delta_brightness * (1 + percent) / (1 + brightness_horizon_offset)) + self.min_brightness

    def calc_color_temp_kelvin(self, percent: float, is_sleep: bool) -> float:
        """Calculate the color temperature in Kelvin."""
        if is_sleep:
            return self.sleep_color_temp
        if percent > (0 - color_temp_horizon_offset):
            delta = self.max_color_temp - self.min_color_temp
            return (delta * (percent + color_temp_horizon_offset) / (1 + color_temp_horizon_offset)) + self.min_color_temp
        return self.min_color_temp`

**Comment by basnijholt** [comment]
Check out the new `brightness_mode` feature introduced in 1.19.0: https://github.com/basnijholt/adaptive-lighting/blob/104664d3588442730f7ea9e811dd1986aca0c2e8/README.md#custom-brightness-ramps-using-brightness_mode-with-linear-and-tanh

This should give you enough control to separate brightness and color.

Some more examples:
Notice the values of `brightness_mode_time_light` and `brightness_mode_time_dark` in the text box.
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/15143580-13cd-4ab2-a603-89f2b7830afd)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/f61fdac9-6d47-48c9-84ed-cbb451d5de5d)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/e5fc5d27-3c37-4e3d-93d1-6e7cf4b48e7c)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/3dcbdc42-63c4-49df-8651-d2fae53dd08d)

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

![adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/assets/6897215/4e5cb08c-0327-40c2-8822-3095eb795358)

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f

**Comment by jacob3089** [comment]
New brightness control is great! Thanks!

**Comment by basnijholt** [comment]
I am glad you like it 😄
