### ISSUE TITLE
Sleep mode not working after recent HACS update

### ISSUE THREAD

**Issue by MaoZ1993** [basnijholt/adaptive-lighting#134]
Hi Bas
Thanks for the great work. I have used this add on for 6 months and all works perfectly for my various brand smart lights.
I have automation to enable sleep mode at 11:00 pm every day, however, it stops working in recent month. I have troubleshot around and I realise I cannot even put into sleep mode manually. 

I'm not sure why this caused, please see the screenshot of my configuration. 

Also, I found an error in the log attached.

![Screen Shot 2021-06-12 at 9 57 45 am](https://user-images.githubusercontent.com/35769176/121758464-c0fe6e00-cb64-11eb-9ac8-8e6a4f1b6092.png)
![Screen Shot 2021-06-12 at 9 57 54 am](https://user-images.githubusercontent.com/35769176/121758466-c2c83180-cb64-11eb-81e4-91aad5fb4629.png)
![Screen Shot 2021-06-12 at 9 57 25 am](https://user-images.githubusercontent.com/35769176/121758470-c3f95e80-cb64-11eb-91a5-d139637d3534.png)

Many many thanks

**Comment by RubenKelevra** [comment]
Hey @MaoZ1993,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886276
