### ISSUE TITLE
Use RGB mode only in sleep mode only

### ISSUE THREAD

**Issue by gorbypark** [basnijholt/adaptive-lighting#135]
I have some of the new Lidl smart bulbs and their colour settings are a bit odd.  When in colour temperature mode, they act normal, but 1% brightness is very bright (I'd guesstimate it's at about 30-40% still).  While in RGB mode, it's the opposite, where 100% brightness is fairly dim (maybe 30%).  It's like the lights are two lights in one, a colour temperature bulb and a full rgb bulb.  Anyways, I was hoping to have an option to use RBG mode in sleep mode only, so that I can set the light levels really low at night.

**Comment by steve41200** [comment]
Sure the brightness is very different form RGB and color temp. I have one Strip led lidl, with 
take_over_control: true
detect_non_ha_changes: true
but it always go to automatic light when I change him manually. Do you observe this too ?

**Comment by ASNNetworks** [comment]
As a workaround you can duplicate the integration for the light. Turn off sleep mode for integration A and turn on only sleep mode for integration B and use rgb_color option.

**Comment by nschwermann** [comment]
Came here to ask for this as well! I have a light that is a downlight for white light and offlight for RGB. So can't use one or the other.

**Comment by RubenKelevra** [comment]
Due to a feature freeze of v1 the milestone has been changed to v2.

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.
