### ISSUE TITLE
Adaptive lighting has a very slow loading time

### ISSUE THREAD

**Issue by pimw1** [basnijholt/adaptive-lighting#136]
Hi all,

The adaptive-lighting integration takes >11 seconds to load on my Raspberry Pi 4, Docker supervised. It is in the top-3 of the slowest-loading integrations i have come accross. It would be great if performance could get some attention.

**Comment by basnijholt** [comment]
I think this probably is because adaptive lighting waits until everything else is loaded.

**Comment by RubenKelevra** [comment]
@pimw1 does this answer your question? :)

**Comment by pimw1** [comment]
Hi, partly. Two questions are in my mind:

1. is the hypothesis true? Even though it waits until everything else is loaded, it can still have a long loading time. Is that the case or not? 
2. Why is this integration waiting for everything else to be loaded first? It sounds inefficient. But i don't have the inside knowlegde of Adaptive Lighting,, so it's easy for me to say.

Could someone shed some light on this?

**Comment by RubenKelevra** [comment]
I try to answer this (as Bas is super busy right now) - but haven't worked myself in the codebase yet, so just a guess:

The plugin depends on various other components which talks to the hardware, so it waits until those components are finished and then it will start up and hook into the lights to avoid to process all the boot up messages of the other plug-ins.

**Comment by pimw1** [comment]
Thanks for taking this effort Ruben. What do you think about question 1?

**Comment by basnijholt** [comment]
This component doesn’t do any complicated calculations or communication. It should only take a few microseconds to do the calculations for the sun set and sunrise. so I am not particularly worried about a slow start ups times.

Ruben is correct with what he said above 😄

**Comment by pimw1** [comment]
Thanks Bas! I'll close the issue.
