### ISSUE TITLE
Input Boolean for State of Adaptive Lighting

### ISSUE THREAD

**Issue by maniscalcojohn** [basnijholt/adaptive-lighting#137]
Would be very helpful if there was an input_boolean automatically created for each instance that turns off when manual control is enabled and can be turned on to restore the adaptive lighting control. I know it can be done with an automation, but it is tedious to do it for every instance. Thanks!

**Comment by ASNNetworks** [comment]
You can just turn the main switch off and on. That will apply adaptive light again. It's a switch entity, you can add it to Lovelace. Your solution would create a lot of extra input booleans if you have multiple lights inside a Adaptive Lightning. Each light on it's own would then need an input_boolean that turns off when you manually override it. I have around 30 lights and not really looking forward to have 30 extra input booleans to be honest. 

Just switching the main Adaptive Lightning switch off and on will do the same thing to the lights.

**Comment by maniscalcojohn** [comment]
Yes, you can do that, but it’s not intuitive for the rest of the occupants in the home. If someone changes a light and the adaptive lighting switches to manual mode, there isn’t even an obvious way to identify whether adaptive lighting is active. The input Boolean makes it very clear and obvious to anyone that the adaptive lighting is inactive and a simple switch to reactivate it. And no need to switch it off and back on. 

Re the extra inputs, you wouldn’t have to use them for normal operation if you don’t want to, just ignore them.

**Comment by ASNNetworks** [comment]
Good point. Though I don't have need for it myself, I can see why others might.
