### ISSUE TITLE
Deleted Integration Item returns after restart

### ISSUE THREAD

**Issue by jkms** [basnijholt/adaptive-lighting#141]
So, I accidentally created duplicated "Kitchen" "Adaptive Lighting" integrations.  This was causing the sleep mode to malfunction until I noticed the duplicate.  No big deal.  Removing the duplicate integration solves the problem.

However, when I restart HA, the integration always returns.
![image](https://user-images.githubusercontent.com/660916/122709076-61622b80-d212-11eb-9548-928024ab4e9e.png)

unsure if this is a `adaptive-lighting` bug, or `home assistant`.

Advice?

**Comment by RubenKelevra** [comment]
No idea actually. But I'm sure I'll take a look at it when I do the refactoring/rewriting of this part for version 2 :)

**Comment by th3w1zard1** [comment]
@jkms Is this still an issue in the latest version?

**Comment by jkms** [comment]
I am unable to replicate the issue at this time.

**Comment by th3w1zard1** [comment]
please comment back here or open a new issue thread if you notice this bug again :)
