### ISSUE TITLE
Not able to use configuration via Fronted

### ISSUE THREAD

**Issue by E020** [basnijholt/adaptive-lighting#143]
Installed everything via Hacs. Restarted HA but under Configuration -> Integration Adaptive lightning was not visible. Only way to get it there is via the YAML configuration for me.

Any idea how to solve this?

**Comment by jeroenvansch** [comment]
I have the same issue, I added the repo to HACS but after that I cant find adaptive lighting under Integration (or under add Integration). Only when I add a yaml config do I see the integration, but then I cant see or edit anything through the frontend.
This is the first time I'm using HACS with a custom integration so I could be doing something wrong...

I'm running the latest HA as a docker container on a synology.

**Comment by basnijholt** [comment]
Unfortunately I will be AFK for the next month. If anyone can make an attempt at fixing this, I will merge it.
