### ISSUE TITLE
Tradfri - bulb turned on by HASS cant be turned off with physical button

### ISSUE THREAD

**Issue by agilob** [basnijholt/adaptive-lighting#144]
This appeared in the last 3-5 weeks (I dont update HACS often). The same bug is present in HA native component flux making it impossible to use. A light bulb turned on using HA, when turned off using physical button will be turned on again in several seconds. Light bulb has to be turned off using HA again to persist its _off_ state.

I uninstalled adaptive-lighting from HACS to confirm the bug is in this component.

**Comment by KrzysztofHajdamowicz** [comment]
Looks like polling issue.
You turn light off, but until HA realizes light is off it calculates new light parameters and sends them to bridge.

As a workaround, try to change interval value to update light less frequent.

**Comment by agilob** [comment]
Cant reproduce it now
