### ISSUE TITLE
Values are cut off by up/down buttons

### ISSUE THREAD

**Issue by Sjorsa** [basnijholt/adaptive-lighting#152]
![image](https://user-images.githubusercontent.com/40437966/127376853-776c80bd-675e-401c-9edc-b4bbc4ffaeba.png)
It looks like this for me on Chrome and Firefox, I first thought it was a 0-1000 value but actually its 0-10000.
I think either the buttons should be removed, because steps of 1 are useless on this scale, or the fields should be wider.
Also, if you scroll down a little further, some explanation texts are cut off as well.

**Comment by FsFalcon** [comment]
I just noticed this issue myself; I agree that the arrows are of limited use in this interface, I'd be okay with only a txt field for entry + the sliders.

**Comment by basnijholt** [comment]
Unfortunately, I cannot do anything about this. I would recommend posting this issue at https://github.com/home-assistant/frontend/issues.
