### ISSUE TITLE
Published versions are not shown in HACS, but the commit to the master

### ISSUE THREAD

**Issue by RubenKelevra** [basnijholt/adaptive-lighting#156]
![Untitled](https://user-images.githubusercontent.com/614929/127775833-ce141e4f-156c-4937-9e36-caabb68e68e1.png)

**Comment by RubenKelevra** [comment]
@basnijholt I've published the release latest release as github release (a tag in Github isn't enough). Can you check if it's working for you?

**Comment by mt0321** [comment]
Looks good to me!
![image](https://user-images.githubusercontent.com/6291808/127806366-778934f0-63b1-4a50-92f4-ddbc070d9c82.png)
