### ISSUE TITLE
Latest release 1.0.13 have circadian-lighting inside the zip file instead of adaptive-lightning

### ISSUE THREAD

**Issue by SeLLeRoNe** [basnijholt/adaptive-lighting#159]
#### Description:
Latest release 1.0.13 have circadian-lighting inside the zip file instead of adaptive-lightning, causing the installation in HACS and the functionality in HA not to work.

Please try to include:
![image](https://user-images.githubusercontent.com/9599441/127779162-929f70d2-82be-4f25-bb53-865a69a48c4c.png)

**Comment by mmartoccia** [comment]
Second this.

**Comment by RubenKelevra** [comment]
I'm sorry. I've published the last git tag (which was 1.0.13) as a GitHub release. This triggered HACS to downgrade from the latest master commit to a much older version.

I just pushed version 1.0.14, which is based on the latest master commit. This should fix the issue

**Comment by beyondtenor** [comment]
Just popping in to say this fixed the issue for me. Thanks for the fast fix!!

**Comment by RubenKelevra** [comment]
@beyondtenor well yeah, I broke it so I had to fix it fast. :)

Had some issues in my installation - it didn't want to just upgrade.

So you guys might need to remove it in HACS, restart HA, install it again in HACS, and restart HA - if you run into any trouble.

**Comment by beyondtenor** [comment]
My experience: HACS wouldn't upgrade it. Restarted HA without removing. Upgraded, restarted HA. I didn't have to remove it and I think the first restart was HACS or cache related.

**Comment by RubenKelevra** [comment]
Ah okay thanks :)

**Comment by SeLLeRoNe** [comment]
Thanks for the quick fix :)

**Comment by mmartoccia** [comment]
All good now, thanks for the quick turn on the fix and update!
