### ISSUE TITLE
Feature Request: combined RBG + colour temp

### ISSUE THREAD

**Issue by nickg90** [basnijholt/adaptive-lighting#16]
i may be wrong but current options allow you to either use the main light with kelvin adjustment OR the RGB light with colour changes.

I would love to be able to have an additional option to use full brightness (and truer daylight colours) of the main white light but the full dim coloured glow of the RGB lights during the night. perhaps a set time to swithc with 60+ second transition as it is difficult to match between the two. I feel like the options already are supposed to support this but I seem to only be able to select RBG or colour temp at the moment?

It would also be nice to be able to select a nighttime colour. In the past I had an automation to turn the bathroom lights to 3% brightness dark purple which ment you dont need to turn the light on to see and minimise impact on sleep. Guess I could easily keep this running but would be nice to have it integrated.

Also, love the graphs in documentation showing how lights change through the day. could these graphs be drawn at the bottom of the options to show you what you have configured?

Im looking forward to seeing this as a native integration in Hassio 0.117!

**Comment by basnijholt** [comment]
I have added two switches: 
* `switch.adaptive_lighting_adapt_brightness_NAME`
* `switch.adaptive_lighting_adapt_color_NAME`

With it I think you will be able to do what you want.

See the docs here https://deploy-preview-14877--home-assistant-docs.netlify.app/integrations/adaptive_lighting/

**Comment by basnijholt** [comment]
@nickg90, could you try the latest commit, I've added a `separate_turn_on_commands` option.

**Comment by basnijholt** [comment]
See https://github.com/basnijholt/adaptive-lighting/issues/29 also.

**Comment by nickg90** [comment]
> 
> 
> @nickg90, could you try the latest commit, I've added a `separate_turn_on_commands` option.

Yes, I think this would let me automate to get what I want more easily. perhaps another suggestion could be to set a sleep RGB colour?

Also, it would be very useful if the integration options included an graph to show how the light brightness changes over 24 hours. im not sure if this is possible, perhaps a link to an graph or something similar?

**Comment by basnijholt** [comment]
You can add these sensors https://github.com/basnijholt/home-assistant-config/blob/93d42dba1fc0d1eeaf33e1c2260807bc3cc6d7b4/includes/sensors.yaml#L264-L282

**Comment by nickg90** [comment]
thanks, got graphs working now 👍

**Comment by basnijholt** [comment]
Please reopen if you have any more issues.
