### ISSUE TITLE
"No content to download" when updating in HACS

### ISSUE THREAD

**Issue by ipetrovits** [basnijholt/adaptive-lighting#162]
#### Version information:
1.0.14

#### Description:

When pressing update button in HACS, getting "No content to download" for a split second then HACS closes the integration info page.

**Comment by RubenKelevra** [comment]
Hey @ipetrovits,

I think this might have something to do with our change from master commit to GitHub versions.

sorry that you're encountering this issue. I've seen this as well but restarting my HA instance fixed this. Can you try this and report back?

**Comment by ipetrovits** [comment]
> Hey @ipetrovits,
> 
> I think this might have something to do with our change from master commit to GitHub versions.
> 
> sorry that you're encountering this issue. I've seen this as well but restarting my HA instance fixed this. Can you try this and report back?

Hey @RubenKelevra,

Thanks for the reply and sorry for the delay, yes - as you expected, core restart did the trick - now my integration is also loaded successfully.

Thanks!

**Comment by Chreece** [comment]
Updating to 1.0.14 solves this.

**Comment by RubenKelevra** [comment]
> > Hey @ipetrovits,
> > 
> > I think this might have something to do with our change from master commit to GitHub versions.
> > 
> > sorry that you're encountering this issue. I've seen this as well but restarting my HA instance fixed this. Can you try this and report back?
> 
> Hey @RubenKelevra,
> 
> Thanks for the reply and sorry for the delay, yes - as you expected, core restart did the trick - now my integration is also loaded successfully.
> 
> Thanks!

Cool 😎
