### ISSUE TITLE
Take weather into account when calculating color temp and brightness

### ISSUE THREAD

**Issue by Airyzz** [basnijholt/adaptive-lighting#164]
Hi,

I would love to see the ability to use a weather entity to influence the state of lights. I think it would be good to be able to have the lights go warmer and maybe dimmer while it is raining / cloudy outside, as well as going cooler and brighter when the sun is out. 

I think it could be implemented using the forecast provided by the weather.home entity which HA adds by default. 

Thanks for your awesome work on this integration!

**Comment by Chreece** [comment]
Hello @Airyzz 

The integration is based on the theory of "circadian rhythm". The lights get adapted on this. 
Is there any reason for the lights to get adapted in the weather, or is just a personal wish?

**Comment by RubenKelevra** [comment]
> Hello @Airyzz 
> 
> The integration is based on the theory of "circadian rhythm". The lights get adapted on this. 
> Is there any reason for the lights to get adapted in the weather, or is just a personal wish?

A cloudy day has a different color temperature than one with a clear sky. 

And you normally don't want to mix color temperatures as this can lead to discomfort. By mixing I mean one room has a different color temperature than the next one and you move back and forth. 

So if there's a thunderstorm outside or a cloudy day a room with lots of window area will maybe still lit enough without artificial light, while the next room has no windows and need to be lit by adaptive lighting. 

To avoid mixing of color temperatures adaptive lighting would need to react to the outside temperature. 

But here's the catch: It's extremely hard to get right just from the weather data. 

A cloud covered sky is around 6500 K while a clear sky will produce between 5000 K and 5500 K. So the light temperature actually gets cooler on a cloudy day.

The opposite is true for thunderstorms which can produce various light colors, even outside of the regular light temperature arc. 

I feel like we won't be able to mimic the outside color temperature without light temperature sensor (which is used in photography).

**Comment by RubenKelevra** [comment]
Additional most people actually like to "detach" from the outside light temperature and brightness, to for example work in an office.

So they want the opposite: Increased indoor brightness and steady cold color temperature if the natural light is insufficient.

**Comment by bpinney** [comment]
I use one configuration for clear days ranging from 2700K to 6000K, and a separate configuration for cloudy days ranging from 2700K to 3300K. An automation toggles an input boolean based on the weather, and then another automation toggles both the clear and cloudy adaptive lighting configurations. It is an imperfect solution but it is working for me.

**Comment by RubenKelevra** [comment]
@bpinney so you perceive a cloudy day as "warmer" and want the same color temperature inside?

What's about precipitation?

**Comment by bpinney** [comment]
@RubenKelevra During daylight hours, I perceive any conditions reported by `weather` that are not "clear-night, partlycloudy, sunny, windy, windy-variant, exceptional" as dimmer than sunny conditions, and so I prefer a warmer color temperature.

@Airyzz suggested having Adaptive Lighting change based on `weather`, but I envision a control very similar to the existing "sleep mode" with maximum brightness/color temperature that can be toggled or adjusted through user-defined automations. Even if the maximum brightness/color temperature were exposed for changes by a service call, users could automate Adaptive Lighting for any conditions as they see fit.

**Comment by RubenKelevra** [comment]
@bpinney ah I think I get what's going on:

While the color temperature outside is actually getting cooler with worse weather, the luminance inside is dropping significantly. So cool light gets actually uncomfortable since your lights without bright light from outside are too dim.

This is called Kruithof curve.

The outside color temperature is like 6500K to 7500K for a cloud-covered sky plus your lights inside are probably below the necessary ~300 lux.

Can you measure the brightness inside (for example with your smartphone's luminance sensor) to confirm this?

**Comment by RubenKelevra** [comment]
Apart from this, I think https://github.com/basnijholt/adaptive-lighting/issues/132 should cover these cases with an extension of the special sleep mode to more general profiles. If you create a profile like "bad weather" and switch to it adaptive lighting would take this as target temperature/brightness and adapt to it with some limitations on the speed of the adaption in lux/minute and mired/minute changing rate. :)

**Comment by RubenKelevra** [comment]
I've added a new ticket as a feature request for obeying the Kruithof curve. :)

**Comment by RubenKelevra** [comment]
> Apart from this, I think #132 should cover these cases with an extension of the special sleep mode to more general profiles. If you create a profile like "bad weather" and switch to it adaptive lighting would take this as target temperature/brightness and adapt to it with some limitations on the speed of the adaption in lux/minute and mired/minute changing rate. :)

As profiles will be included in the upcoming v2, this would be fixed by just creating a light profile for bad weather and maybe one for a cloudy day?

Switching back and forth should be fairly easy as there are weather plugins which can show the cloud coverage and precipitation:

![Precipitation Probability and Cloud Coverage](https://user-images.githubusercontent.com/614929/148677736-3bfa7d2e-7e28-4948-9a09-adcf001e9f73.png)
