### ISSUE TITLE
adaptive lighting and motion sensors

### ISSUE THREAD

**Issue by anoblet** [basnijholt/adaptive-lighting#167]
#### Description:

I have a motion sensor that turns on lights when someone enters the room. With adaptive lighting turned off for that area, the lights fade in gently. If adaptive lighting is turned on, the color and/or brightness seem to jump right away to whatever state adaptive lighting believes they should be.

I have set `initial_transition` to `45` in the area config. 

I've also tried `adaptive_lighting.apply` before turning on the light with `turn_on_lights` set to `false` and `transition` set to `45`. 

Any ideas?

**Comment by RubenKelevra** [comment]
Hey @anoblet, @desertblade,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

- https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886261
- https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886273
