### ISSUE TITLE
RGBW lights seem to be assumed to be cold white

### ISSUE THREAD

**Issue by gitrichhub** [basnijholt/adaptive-lighting#169]
1.0.14

After upgrading to Home Assistant 2021.8.6 I noticed that at mid-day my RGBW lights were setting the blue channel to 0, rather using the blue to bring the kelvin up to the 6000K setting.

**Comment by RubenKelevra** [comment]
Hey @gitrichhub,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886264
