### ISSUE TITLE
add delay before changing lights after turning on

### ISSUE THREAD

**Issue by cascer1** [basnijholt/adaptive-lighting#174]
Hi!

I'd love a feature to delay the automatic adjustment of lights when they first turn on. This woukd be useful because my lights sometimes don't respond immediately to changes when they are fading on and so half of them will be set to the correct color temperature and the rest will remain at the temperature they had when they turned off. They will not only all get the correct color temperature after the next adjustment interval.

I think that waiting for x seconds before issuing the adjustment should help resolve this.

**Comment by RubenKelevra** [comment]
Well yeah this makes sense. But I think if you can switch the lamps via a master switch through adaptive lighting this should be resolved as well:

https://github.com/basnijholt/adaptive-lighting/issues/132

**Comment by cascer1** [comment]
I don't think the master switch would quite work with the way I have my lights setup. I have individual lights assigned to the integration and then don't always turn them all on. Would the master switch automatically turn on all the lights always?

**Comment by RubenKelevra** [comment]
Hey @cascer1, @TheAlphaLaw,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886261
