### ISSUE TITLE
Lights set to 1% brightness mid-day after latest update (#f65ba6c)

### ISSUE THREAD

**Issue by jordandrako** [basnijholt/adaptive-lighting#18]
I can't tell exactly why, but it seems the component thinks the sun is at a much lower elevation, and setting the lights to their minimum settings. Before I updated, they would normally be at 100% brightness at this time.

**Comment by basnijholt** [comment]
That's probably because the sleep mode switch is on. This happened because of a bug I introduced (but already fixed!).

**Comment by jordandrako** [comment]
Ah, that was it! I didn't have the sleep mode switches in my UI so I didn't think to check them. Closing this issue since the solution is to turn off the sleep mode switches and you've fixed the bug.
