### ISSUE TITLE
Sunrise and sunset times

### ISSUE THREAD

**Issue by Ryanm72** [basnijholt/adaptive-lighting#182]
The drama I'm having is the rate of increased and decreased brightness vs the time, see by the graph that it dims the light at only for a hour at 1 o'clock in the morning, is there a way to change this so I can have a ramp at sunrise and sunset in bright to simulate a full day from sunrise and sunset time so I don't get a rapid change in light turning of into sleep mode?

Regards

**Comment by RubenKelevra** [comment]
Hey @Ryanm72,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

- https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886274
- https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886276
- https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886300
