### ISSUE TITLE
Make the switch entity less chatty

### ISSUE THREAD

**Issue by stefanroelofs** [basnijholt/adaptive-lighting#187]
Hi,

Here's just something to think about:

I had a look at my Home Assistant database, and the adaptive lighting switches generate a lot of entries:
![image](https://user-images.githubusercontent.com/37924749/133081217-9c27e0d3-00d1-4dd8-9e92-1b07d0b2dae7.png)

I record data for 14 days, so in 14 days the state of the switches change about 14000 times.

I assume this is because of the attributes of these switches (like sun_position):
![image](https://user-images.githubusercontent.com/37924749/133080904-76ae7bfb-0fe0-4c8e-b24e-e8ae81835e33.png)

Can we make these switches less chatty?
For reference, the `sun.sun` entity only has 4285 entries in the states table, so I don't know why there must be so much data.

Some ideas to decrease the amount of entries in the database:
* Decrease precision of attribute data (keep only 1 or 2 digits behind the comma, e.g. sun_position = 0.99)
* Remove some of the attributes

**Comment by basnijholt** [comment]
Hi @stefanroelofs, thanks for the suggestions. However, if you don't want to store the information then you can just exclude these from your database, see https://www.home-assistant.io/integrations/recorder/#exclude.

This integration is still not working 100% well in all cases (as indicated by the many issues), therefore I would like to still keep the history for debugging purposes.

**Comment by stefanroelofs** [comment]
I understand that you like to keep the debug info. I just wanted to let you know.

I think you mean the setting: 'Interval - time between switch updates'. I've got that set for 90 seconds. Seems like a reasonable value.  When I calculate this for 14 days (40*24*14) I get: 13.440 updates. So I guess the amount of entries in the states table actually make sense. 

I will close the issue. 
Thanks!
