### ISSUE TITLE
Get back previous light state

### ISSUE THREAD

**Issue by egorgam** [basnijholt/adaptive-lighting#191]
Hello!

I think it will be good, if this plugin can implement this use case:

1. Lights are turned of with any state (colored, dimmed, etc)
2. User turned on adaptive-lighting
3. Used turned off adaptive-lighting
4. Lights state is back to p.1

**Comment by basnijholt** [comment]
Thanks a lot for the suggestion, however, this will be very hard to keep track of, especially during restarts.

Also, I can imagine cases where this is not desirable.

Since I find it extremely unlikely that I will implement this, I will close the issue for now.

**Comment by mindtripper** [comment]
> Hello!
> 
> I think it will be good, if this plugin can implement this use case:
> 
> 1. Lights are turned of with any state (colored, dimmed, etc)
> 2. User turned on adaptive-lighting
> 3. Used turned off adaptive-lighting
> 4. Lights state is back to p.1

Hi egogram,

Can the use of Scene and "snapshot_entities" to solve your use case?

1. Lights are turned of with any state (colored, dimmed, etc)
2. Scene create entities snapshot
3. User turned on adaptive-lighting
3. Used turned off adaptive-lighting
4. Scene restore entities snapshot
5. Lights state is back to p.1
