### ISSUE TITLE
Adaptive lighting error in Core Log

### ISSUE THREAD

**Issue by Patrick1610** [basnijholt/adaptive-lighting#199]
#### Version information:
current

#### Description:
I was looking in the logfiles, I don't know what HA or AL was trying to do ATM. 

2021-09-29 19:30:59 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1228, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'

**Comment by mstefany** [comment]
Same here:
```
Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1257
Integration: Adaptive Lighting (documentation, issues)
First occurred: 20:25:38 (2 occurrences)
Last logged: 20:27:50

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1257, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'
```

Using latest adaptive_lighting 1.0.14

**Comment by facastagnini** [comment]
There is many tickets pointing at the same error over a long period of time, can it be possible to dedup them?

https://github.com/basnijholt/adaptive-lighting/issues?q=is%3Aissue+is%3Aopen+Error+doing+job%3A+Task+exception+was+never+retrieved

**Comment by basnijholt** [comment]
This issue is fixed in https://github.com/basnijholt/adaptive-lighting/pull/321.

Please update Adaptive Lighting :)
