### ISSUE TITLE
Remove `transition` when it is 0 (botches running transitions), or add possibility to remove it.

### ISSUE THREAD

**Issue by dekiesel** [basnijholt/adaptive-lighting#200]
Before I start: Thanks for writing this awesome piece of software!

As a part of my movie-lighting I'd like to slowly transition lights from `on` to `off` and vice versa. 

Let's say I want to slowly turn on a light when a movie is paused: I set `transition=4` in my `service_call` definition and run it.

This activates `adaptive lighting` and it too fires its initial transition, which means instead of the light slowly turning on over the course of 4 seconds `adaptive lighting` turns it fully on after 1 second.

My initial reaction was: Well ok, I'll set it to 0. But then `transition=0` is added to the call and the lights come on even quicker.

![image](https://user-images.githubusercontent.com/17333827/135351758-34996fce-02fb-480e-9bf5-f8b104b06237.png)
As you can see in the image (I am using zigbee2mqtt with this light): "My" transition value of four was overwritten by `adaptive lighting`s transition value of 0.

Please add a way to remove the transition value, either by omitting it if it is 0 or by adding a toggle.

Thanks.

**Comment by RubenKelevra** [comment]
Hey @dekiesel @anoblet,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886261
