### ISSUE TITLE
Option sleep_transition not available in frontend

### ISSUE THREAD

**Issue by thomasfals** [basnijholt/adaptive-lighting#202]
The option sleep_transition is not available in the frontend. The only way to set it is by defining in config but then you loose access to the options via the integration.

**Comment by Stooovie** [comment]
It doesn't even work via config. It gives
`Invalid config for [adaptive_lighting]: [sleep_transition] is an invalid option for [adaptive_lighting]. Check: adaptive_lighting->adaptive_lighting->0->sleep_transition.`

**Comment by bung69** [comment]
Dosnt work via the GUI either on the latest version

**Comment by cameronurnes** [comment]
This seems to be fixed now
