### ISSUE TITLE
Options Disappear after update to 4d24249

### ISSUE THREAD

**Issue by Dakael** [basnijholt/adaptive-lighting#21]
Adapt brightness, adapt rgb/x/y, and adapt color temp have disappeared after update.
![image](https://user-images.githubusercontent.com/21049524/96881480-50c3a080-144c-11eb-826a-d77e2f7c7d15.png)
Lights now no longer adapt any of those things.

**Comment by basnijholt** [comment]
That is because those options are now switches, such that you can automate it.

See the docs here: https://deploy-preview-14877--home-assistant-docs.netlify.app/integrations/adaptive_lighting/

**Comment by basnijholt** [comment]
![image](https://user-images.githubusercontent.com/6897215/96881918-07d90f80-147f-11eb-8a5c-74f15add2b59.png)

**Comment by Dakael** [comment]
Roger, thank you!
