### ISSUE TITLE
List of lights under automatic control

### ISSUE THREAD

**Issue by hoffbaked** [basnijholt/adaptive-lighting#210]
There is a property for lights that are under manual control, but it would be helpful if there was a similar property for lights which are being automatically controlled. I have to hard code the names of the adaptive lighting switches into everything. If there was a list, I could search for the adaptive lighting instance based on the name of the entity being controlled and make my scripts and automations more general. Also, I have to have a ton of controllers for bulb in different rooms, and of different relative brightnesses. Sometimes it's tricky to remember which of the integration instances a given bulb is controlled by. Being able to browse the states would be very helpful.

**Comment by Talor-A** [comment]
what is the property for getting the lights under automatic control? I don't see it documented.

**Comment by RubenKelevra** [comment]
@hoffbaked sounds like you have a large installation.

Can you look at the roadmap for v2 and vote on the things which would improve your experience and report close this, if the issue would be solved with those goals?

Thanks!

**Comment by th3w1zard1** [comment]
If you want to send every adaptive-lighting switch, you can use the following template in your automation/script:
```
  entity_id: |
    {{ entity_id|default(states.switch
       | map(attribute='entity_id')
       | select(">", "switch.adaptive_lighting_al_")
       | select("<", "switch.adaptive_lighting_al_z")
       | join(",")) }}
```
output:
`switch.adaptive_lighting_al_bedroom_ceilingfan_lights,switch.adaptive_lighting_al_den_ceilingfan_lights,switch.adaptive_lighting_al_linkind_dimmer_bulb,switch.adaptive_lighting_al_shellyrgbw2_ddcc57`

**Comment by hoffbaked** [comment]
This doesn’t solve the problem that for any given light, I can’t tell which adaptive light switch is controlling it. For example, I have motion sensing scripts that dim the light over time. I have to get the brightness and color temp from the adaptive lighting switch, so I have to hard code it. But I have a bunch of 13 adaptive lighting groups, so it sometimes takes quite a while to go through the setup of each instance of the adaptive lighting integration, and then look through the dropdown to find out which one is controlling it. I usually miss it the first time through, and have to go through a second time. It’s very error prone and tedious. And if I move I light to a different group, I then have to modify every script, also.On Mar 23, 2023, at 10:38 AM, Benjamin Auquite ***@***.***> wrote:﻿
If you want to send every adaptive-lighting switch, you can use the following template in your automation/script:
  entity_id: |
    {{ entity_id|default(states.switch
       | map(attribute='entity_id')
       | select(">", "switch.adaptive_lighting_al_")
       | select("<", "switch.adaptive_lighting_al_z")
       | join(",")) }}

output:
switch.adaptive_lighting_al_bedroom_ceilingfan_lights,switch.adaptive_lighting_al_den_ceilingfan_lights,switch.adaptive_lighting_al_linkind_dimmer_bulb,switch.adaptive_lighting_al_shellyrgbw2_ddcc57

**Comment by th3w1zard1** [comment]
I'm very interested in this too. If we make loop through all switches created by adaptive-lighting and find the switch entity_id based on the light.switch entity_id, we can make the switch optional from the service call.

would that be enough for ya? I agree the naming schemes get old pretty fast especially with large configs like ours.

**Comment by th3w1zard1** [comment]
I've exposed the entire config in #445 however getting the services to accept a light's entity_id instead of requiring a switch's entity_id has been challenging, but I also finished that. You'll be able to use the area/group/entity id selectors just like in all the other service calls hass has.

**Comment by hoffbaked** [comment]
Nice!! I’ll check it out…On Mar 24, 2023, at 12:09 AM, Benjamin Auquite ***@***.***> wrote:﻿
@hoffbaked Check out #459 I believe I've implemented what you're looking for.

**Comment by hoffbaked** [comment]
I probably did something wrong, but I managed to checkout your PR branch under the home assistant terminal, renamed by old adapative_lighting in custom_components installed by HACS, and then symlinked the one from the PR. I restarted, and it seems to be working, but the labels are missing when I get into the settings of an AL instance. When I look at states under developer tools, I'm not noticing any new attributes. I'm guessing I'm doing something horribly wrong.

**Comment by th3w1zard1** [comment]
> I managed to checkout your PR branch under the home assistant terminal, renamed by old adapative_lighting in custom_components installed by HACS, and then symlinked the one from the PR. I restarted, and it seems to be working, but the labels are missing when I get into the settings of an AL instance. When I look at states under developer tools, I'm not noticing any new attributes. I'm guessing I'm doing something horribly wrong.

I'm so sorry I got my wires crossed. The feature you're looking for is correctly implemented in #445 .
![image](https://user-images.githubusercontent.com/2219836/227657580-504ea6f7-2d4a-47b1-8094-d932fc63b107.png)

**Comment by hoffbaked** [comment]
No problem! I'll give it a go...

**Comment by th3w1zard1** [comment]
Worth noting that the lights appearing under `lights` are not the ones being adapted, but are a collective of all the lights in the config. You'll need to have your automation/script filter out the ones in the `manual_control` list yourself.
