### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by SeLLeRoNe** [basnijholt/adaptive-lighting#213]
#### Version information:
1.0.14
HA core-2021.11.0b2

#### Description:

This is from console:
```
POST https://HOST/api/config/config_entries/options/flow/795dd180c8ba4de585a5d8ad13c29162 400
I @ styles.ts:365
(anonymous) @ styles.ts:365
callApi @ styles.ts:365
s @ ha-card.ts:5
value @ step-flow-form.ts:69
handleEvent @ styles.ts:365
```

This is the POST payload:
```
{lights: ["21"], prefer_rgb_color: false, initial_transition: 1, transition: 45, interval: 90,…}
detect_non_ha_changes: true
initial_transition: 1
interval: 90
lights: ["21"]
0: "21"
max_brightness: 100
max_color_temp: 5500
min_brightness: 1
min_color_temp: 2000
only_once: false
prefer_rgb_color: false
separate_turn_on_commands: false
sleep_brightness: 1
sleep_color_temp: 1000
sunrise_offset: 0
sunrise_time: "None"
sunset_offset: 0
sunset_time: "None"
take_over_control: true
transition: 45
```

Which returns:
```
{"message": "User input malformed"}
```

Hope I've provided enogh information, if not, please feel free to ask.

Thanks
Andrea

**Comment by jk1993** [comment]
Having the same issue. Assumed it was something related to the beta. Think the workaround for this integration is to use yaml for the config. That seems to work, but would be nice to be able to set it up in the UI

**Comment by DTTerastar** [comment]
I saw this in 2021.11.0b4

**Comment by SeLLeRoNe** [comment]
Yes it started with the latest beta

**Comment by sambarlick** [comment]
I also have this issue, experienced it on 2021.119b3 and 4 and 5.

**Comment by luisleonardo** [comment]
Same here since 2021.11.0b1 and also with Passive BLE monitor.

**Comment by stevenjev** [comment]
Also noticing this error using the release version of 2021.11

**Comment by felix63** [comment]
<img width="595" alt="Schermafbeelding 2021-11-05 om 00 55 29" src="https://user-images.githubusercontent.com/16501940/140436326-d8567314-72c5-4845-b975-52e77c4c2796.png">

I have the same issue. It also occurs in other custom integrations such as 'Magic Area'

**Comment by sambarlick** [comment]
I think this might have something to do with the new drop down list. It's
the only thing I can think of that's changed in n 2021.11.

**Comment by SeLLeRoNe** [comment]
Yep, I believe so @sambarlick

**Comment by thomclae33** [comment]
Same issue. 😢

**Comment by pnm1977** [comment]
I've also got this issue. Updated to core-2021.11.1 and lost ability to add new rooms or edit existing ones through the integration option.

**Comment by maccident** [comment]
+1  Same "User input malformed" issue.

**Comment by oksibutch** [comment]
+1 have a problem too

**Comment by DeadpoolW** [comment]
+1 Same here, tried to delete some lights, now I also have "User input malformed". Deleting the integration and re-adding it, does not solve it.

**Comment by randomlyalex** [comment]
Following this as i have the same issue, and also have it with [programmable thermostat](https://github.com/custom-components/climate.programmable_thermostat/issues/42) which is using the same input fields maybe?

**Comment by basnijholt** [comment]
I have looked into it, but cannot figure out what changed. Even HomeKit is generating these errors: https://community.home-assistant.io/t/homekit-error-user-input-malformed/353390

**Comment by randomlyalex** [comment]
I couldnt see an issue in the front end related to this, and its across many integrations, so either some kind of breaking change update needs releasing so people can adapt, or there is a bug in the front end and it needs looking it :)

**Comment by poelzi** [comment]
When I open the light dropdown menu does not have the entries selected which are written in the field. Toggeling the checkbox adds an aditional entry, so there is definitily also some desync happening.

**Comment by bgreet** [comment]
Having same issue.  Integration no longer works if adding anything new from the UI

**Comment by andrewfitz** [comment]
Same issue, broke on update to 2021.11 from 2021.10.6, or from enabling hue groups support.

**Comment by LEJOUI** [comment]
Same [issue](https://github.com/custom-components/ble_monitor/issues/543) was found in the ble custom component. He found a solution, might be helpfull?

**Comment by Boggie** [comment]
Is it cause by frontend bug in HA?
https://github.com/home-assistant/frontend/issues/10567

**Comment by SeLLeRoNe** [comment]
It could be but hasn't been picked up by HA Staff yet

**Comment by liudger** [comment]
https://github.com/home-assistant/frontend/pull/10585
it looks like this is the issue?

**Comment by basnijholt** [comment]
Great, a fix has just been merged by @bramkragten, I imagine it will make it to the next patch release.

**Comment by lucasfr** [comment]
When is the next patch release expected to happen?

**Comment by Syfaro** [comment]
After upgrading to Home Assistant 2021.11.3, it seems to work again.

**Comment by poelzi** [comment]
Strange, I can not even select any entry anymore, the whole selection box is missing. Pressing save still causes the error message.

**Comment by SeLLeRoNe** [comment]
Confirmed to be fixed by 2021.11.3 that includes the related Frontend updates: https://github.com/home-assistant/core/pull/59451

**Comment by poelzi** [comment]
Ok, I see the problem now. It is not completly fixed:
I had a lamp which was controlled by adaptive lighting. I then renamed this lamp and created a light group of the same name as the old lamp was.
The old entry is now still shown as selected in the combo box, but the entry does not actually exist anymore to select. This causes the malformed data to be sent. It is not possible to deselect the now not shown entry, causing the dialog to be broken with no way to fix it.

**Comment by SeLLeRoNe** [comment]
I had the same, but not related to this issue.
It's a bug but a different one.
To fix I had to remove that specific ntegration and add it back.

**Comment by poelzi** [comment]
I opened [#10608 ](https://github.com/home-assistant/frontend/issues/10608) for that. Yes, I think it's a different problem that is partially related
