### ISSUE TITLE
Sleep Transition

### ISSUE THREAD

**Issue by ciswindell** [basnijholt/adaptive-lighting#217]
The documentation states that a sleep transition option can be set with sleep_transition however I get an error stating "Invalid config for [adaptive_lighting]: [sleep_transition] is an invalid option for [adaptive_lighting]. " 

Otherwise this is my favorite component in HA. Thanks for the awesome work!

**Comment by Stooovie** [comment]
Anyone? I use sleep state in my toddler's room and the instant transition between the default and the sleep state is jarring.

**Comment by bung69** [comment]
Sleep transition time and inital transition time do not work for me at all.  Configured using the GUI

**Comment by RubenKelevra** [comment]
Hey @ciswindell, @Stooovie, @bung69,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291?sort=top#discussioncomment-2886261
