### ISSUE TITLE
Usage of device_state_attributes is depricated in Home Assistant 2021.12b0

### ISSUE THREAD

**Issue by pimw1** [basnijholt/adaptive-lighting#227]
#### Version information:
Home Assistant Supervised 2021.12b0

#### Description:
As per Home Assistant 2021.12b0, the usage of device_state_attributes is depricated. I think extra_state_attributes should be used from now on (see the Home Assistant Github Beta channel for more info).

Please try to include:
Exact error message:

- Entity switch.adaptive_lighting_slaapkamer_hobbykamer (<class 'custom_components.adaptive_lighting.switch.AdaptiveSwitch'>) implements device_state_attributes. Please report it to the custom component author.
- Entity switch.adaptive_lighting_gang (<class 'custom_components.adaptive_lighting.switch.AdaptiveSwitch'>) implements device_state_attributes. Please report it to the custom component author.
- Entity switch.adaptive_lighting_woonkamer (<class 'custom_components.adaptive_lighting.switch.AdaptiveSwitch'>) implements device_state_attributes. Please report it to the custom component author.
- Entity switch.adaptive_lighting_keukenblok (<class 'custom_components.adaptive_lighting.switch.AdaptiveSwitch'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by monotonus** [comment]
Same here with non-beta 2021.12.1

**Comment by LordMike** [comment]
See more at home-assistant/core#47304

**Comment by basnijholt** [comment]
I have just created a new release. Did it solve the issue?

**Comment by pimw1** [comment]
Yes it did solve the issue. Thank you very much @basnijholt and @covid10
