### ISSUE TITLE
Idea for enhancing manual control

### ISSUE THREAD

**Issue by broyuken** [basnijholt/adaptive-lighting#237]
This is to hopefully resolve the by far #1 complaint my wife has with our smart home. When she turns on a light, AL adjusts it to what it thinks it should be, she changes it to what she wants it to be, then AL adjusts it back. 

Could you add a check in after the initial turn on transition for the light? If the light is where AL thinks it should be, great. If it's not, set it to manually controlled and stop adjusting it.

**Comment by vbaros** [comment]
There is an option take over control which does exactly that.

**Comment by broyuken** [comment]
It doesn’t though. If I turn it on and immediately change the brightness like a normal person would AL still takes over. Manual control doesn’t seem to kick in until at least the first check in after it’s turned on.

**Comment by anoblet** [comment]
@broyuken Make sure that the lights defined in adaptive line match the lights in whatever automation you are using if any. If you set up adaptive light using a group of some sort (native/Zigbee) and try to set an individual light, AL won't respect that change.

**Comment by broyuken** [comment]
It works fine after the first check in. But if I adjust the lights right away after AL changes them it doesn’t mark it as manually adjusted.

**Comment by RubenKelevra** [comment]
Hey @broyuken,

> It works fine after the first check in. But if I adjust the lights right away after AL changes them it doesn’t mark it as manually adjusted.

While this might be a bug, version 2 is planned to get a completely new output module anyway, so this bug will likely disappear.

Additionally the manual/automatic controlling of lights/groups/rooms should be much more comfortable in v2 as well. So there might be a big improvement in "wife compatibility" ahead ;)

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.

**Comment by broyuken** [comment]
Awesome, thank you! I have a bunch of tickets open around manual control and random lights turning back on. 

No pressure, and we’re not holding you to any hard dates but do you have a rough ETA on v2? Are you thinking days, weeks, months, next year, etc. really looking forward to any improvements because this is by far my most used integration.

**Comment by mikz** [comment]
I've been debugging the same issue and it looks like if you adjust brightness after turning the light on it does not trigger manual mode on state change.

Brightness change is checked only when adapt light is called, so if you change brightness it first sets new adaptive light brightness and then sets manual mode and quits.

You could pre-emptively enable the set manual mode. Looking forward v2 too! 

I know some Python and do a lot of other coding so I'm happy to test an early release/dev branch.

**Comment by bastiaanterhorst** [comment]
Resurrecting this as I am experiencing the same behaviour. A lot of work has happened on this component since this ticket was filed -- should this have been fixed in the mean time, or will an adjustment right after turning the lights on still be overridden by AL?

**Comment by broyuken** [comment]
I think this is a planned fix for v2 whenever that is going to happen. I haven’t heard a rough ETA or anything yet

**Comment by basnijholt** [comment]
Yes “v2” is really @RubenKelevra his project. I personally see a more gradual upgrade path as long as we continue with the current code. I don’t have a lot of time for a big rewrite unfortunately.

**Comment by cramertj** [comment]
> Could you add a check in after the initial turn on transition for the light? If the light is where AL thinks it should be, great. If it's not, set it to manually controlled and stop adjusting it.

Another option would be to enable manual control (and stop adjusting) if a light is turned on at a different brightness than the last recorded brightness (when it was turned off). This would indicate that the light was turned on to an intentional brightness, and should not be adapted.

**Comment by broyuken** [comment]
That wouldn’t work. If you turn a light off at noon when it should be at 100% and white, and then don’t turn it on again until 7pm when it should be 50% and warm it shouldn’t be set to manual control.

**Comment by th3w1zard1** [comment]
PR #450 fixes this with the config options `strict_adapting: false` OR `alt_detect_method: true` set.

**Comment by broyuken** [comment]
It does seem to be fixed, thank you!!!
