### ISSUE TITLE
Service example is wrong ?

### ISSUE THREAD

**Issue by pixeye33** [basnijholt/adaptive-lighting#24]
Hello,

Here's what i get when trying to call the service using the parameters described in docs + in the service itself
![image](https://user-images.githubusercontent.com/1382471/97086443-94243780-1623-11eb-9fe1-2661497ff74c.png)

both adapt_color_temp and adapt_rgb_color parameters have the same behaviour.

I'm using this exact commit : https://github.com/basnijholt/home-assistant/tree/911e88ae9eb92f76a34b3ccf83292494bd87bf63

Plus, quick question : would you suggest using this service to turn on the lights in automations ? instead of a classic turn_on ?

Thanks !

**Comment by pixeye33** [comment]
I think i've found the mistake :

https://github.com/basnijholt/home-assistant/blob/911e88ae9eb92f76a34b3ccf83292494bd87bf63/homeassistant/components/adaptive_lighting/services.yaml#L16
https://github.com/basnijholt/home-assistant/blob/911e88ae9eb92f76a34b3ccf83292494bd87bf63/homeassistant/components/adaptive_lighting/switch.py#L276
https://github.com/basnijholt/home-assistant/blob/911e88ae9eb92f76a34b3ccf83292494bd87bf63/homeassistant/components/adaptive_lighting/const.py#L42

There is no : adapt_rgb_color anymore
and adapt_rgb_color became adapt_color

**Comment by basnijholt** [comment]
Good catch, I will fix it when I find a minute!

**Comment by basnijholt** [comment]
Can you check if with the latest update the problem is fixed? https://github.com/basnijholt/adaptive-lighting/commit/3352fa3b9c51982b4460827ddc796e5e7edfd4f3

**Comment by pixeye33** [comment]
It does work ;) Thanks 👍

**Comment by pixeye33** [comment]
> Plus, quick question : would you suggest using this service to turn on the lights in automations ? instead of a classic turn_on ?

Looks like it was a great idea : https://github.com/basnijholt/home-assistant-config/blob/master/scripts.yaml#L576
i started doing the same thing :)

**Comment by basnijholt** [comment]
I only realized that this would be a great idea after you suggested it! I wanted to post back in this issue after having tested it for some days. perhaps we should create a adaptive_lighting.turn_on feature in the future.
