### ISSUE TITLE
Set entity_category for generated switches to 'config'

### ISSUE THREAD

**Issue by stefanroelofs** [basnijholt/adaptive-lighting#241]
As per documentation the integration creates 4 switches:
- switch.adaptive_lighting_living_room
- switch.adaptive_lighting_sleep_mode_living_room
- switch.adaptive_lighting_adapt_brightness_living_room
- switch.adaptive_lighting_adapt_color_living_room

I think it is nice if the last 3 switches (sleep_mode, adapt_brightness and adapt_color) are of entity_category: `config`
These switches are used to configure the integration, and do not need to show up on my main dashboard.

More info here: https://developers.home-assistant.io/docs/core/entity/#generic-properties

Solution might be something like this. Add the following line to switch.py line 1003:
```self.entity_category = "config"```

Thanks!

**Comment by RubenKelevra** [comment]
Thanks for the headsup. I moved this to the todo list for version 2, as version 1 is in feature freeze.

**Comment by RubenKelevra** [comment]
Hey @stefanroelofs,

this is now part of the Roadmap for Version 2.

Feel free to vote on the point which will fix this:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2946844

**Comment by th3w1zard1** [comment]
@stefanroelofs Hi @stefenroelof,

I was trying to implement this request into the integration and ran into a few questions I could have clarified further, my apologies! I indeed did read your original post

I don't quite understand what `entity_category` does or exactly the ramifications of changing it to `config` when considering existing systems.

from the docs you listed:
>Classification of a non-primary entity. Set to config for an entity which allows changing the configuration of a device, for example a switch entity making it possible to turn the background illumination of a switch on and off. Set to diagnostic for an entity exposing some configuration parameter or diagnostics of a device but does not allow changing it, for example a sensor showing RSSI or MAC-address.

I'd rather switches aren't disappearing from lovelace dashboards unnecessarily in use cases where users are expecting it to be there.

Additionally I don't know why you can't just use this option:
![image](https://user-images.githubusercontent.com/2219836/229964119-d50df5be-9d69-43ca-9ff5-e6ba737250d0.png)

Thank you for your suggestion

**Comment by stefanroelofs** [comment]
Hi, thanks for your response, and I understand your reservations.
The entire reason for my suggestion is to make the switches disappear from my (auto-generated) Lovelace dashboard.
I think the 3 switches are used to configure the integration, and I don't need to see them on my dashboard.

If I mark the entities as 'Hidden', they are also hidden in the Settings view. Not exactly what I like.

Anyway, it's up to you. Good luck!
