### ISSUE TITLE
seperate control over brightness and colourtemp

### ISSUE THREAD

**Issue by jeroenvansch** [basnijholt/adaptive-lighting#242]
When I leave everything standard the colourtemp curve is nice, but brightness to my opinion is too high around sunrise and sunset.
If you then use a sunrise or sunset offset and get the brightness the way you like the colourtemp curve isn't nice anymore.

Would it be possible to get separate control over brightness and colourtemp?

**Comment by RubenKelevra** [comment]
Hey @jeroenvansch,

there is a ticket for the high brightness around sunrise/sunset already #133.

Additionally, you can always switch off the brightness or color temperature automatism separately off. Adaptive Lighting exports an "Adapt Brightness" and an "Adapt Color temperature" switch :)

**Comment by iloominaty** [comment]
> 

Do i just disable the "Adaptive Lighting Adapt Color:" in the frontend using the "Enable entity" toggle switch?

**Comment by th3w1zard1** [comment]
@iloominaty are you still having this issue?

If it helps, you can also use the config options `max_brightness` and `min_brightness` in your config.

**Comment by basnijholt** [comment]
Check out the new `brightness_mode` feature introduced in 1.19.0: https://github.com/basnijholt/adaptive-lighting/blob/104664d3588442730f7ea9e811dd1986aca0c2e8/README.md#custom-brightness-ramps-using-brightness_mode-with-linear-and-tanh

This should give you enough control to separate brightness and color.

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

![adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/assets/6897215/4e5cb08c-0327-40c2-8822-3095eb795358)

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f
