### ISSUE TITLE
Was working fine, now goes to white at late time

### ISSUE THREAD

**Issue by mdeweerd** [basnijholt/adaptive-lighting#245]
#### Version information:
Version 1.0.15
HASS OS  - core-2021.12.3

#### Description:
The integration worked fine for several months.

It now changes to white color (possibly more intense) late in the evening (about 22h30/45).  This possibly happens after a home assistant restart.
The on/off switch behavior of the light is strange because in the UI it can enter some kind of infinite on/off repeating change loop, while the light physically stays on.
When I manually wan to change the color temperature, the slidebar is at most only visible for a small moment in the UI.

I have to disable the integration to regain control - no more looping of the on/off state and I can set the color temperature manually.

I checked out the journal but could not find anything relevant.

![image](https://user-images.githubusercontent.com/1504752/149029948-d706d02f-b513-414e-a242-6bab8d6d9874.png)

**Comment by mdeweerd** [comment]
It seems related to a new behavior of the on/off state: when below 43% the state of the light is set to "off", but in practice it is still on (brightness high enough).

I am checking to find how I can change that.

**Comment by RubenKelevra** [comment]
New behaviour of the on/off state at 43%?


Can you elaborate? Where are these Infos coming from?

**Comment by mdeweerd** [comment]
Further testing shows it is more complex.

It looked like when changing brightness to a level lower than 43% or so the light turned off and above it it stayed on (in the UI).
But now, any click just turns it off (in the UI).

I get this error:

![image](https://user-images.githubusercontent.com/1504752/149139330-cbf1802c-d00e-4aca-a5f8-d88068ba2a1d.png)


I do not know how that impacts the adaptive lighting integration.


Anyway, I only get the temperature bar above in the UI when I disable the adaptive-lighting integration.

When entering debug mode and breaking when the "on/off" switch has changing properties, the debugger first stops on this:
![image](https://user-images.githubusercontent.com/1504752/149139607-632939a5-477b-4e92-b261-558a9a95abf7.png)

Which is initiated from:
![image](https://user-images.githubusercontent.com/1504752/149140277-4d878395-e9cf-44df-8cc5-01c744d0f1eb.png)

So this is likely not due to the integration even if there is some impact from the integration.

I am going to clean up my browsers cache for my instance and check again.

**Comment by mdeweerd** [comment]
Even with cache and integration disabled, the UI still manages to behave strangely with regards to the popup.

However, when the integration is not enabled the standard on-off button in the dashboard behaves normally and when the integration is active, the button immediately switches off after enabling it:

![image](https://user-images.githubusercontent.com/1504752/149141441-7b62bcd5-7173-4ca2-8135-33fbd034c56a.png)

And the light intensity and color changed to the ones that I would expect for this time of day.

**Comment by mdeweerd** [comment]
I tested in private navigation mode, and selected to not stay logged in.

Changing the light state to on still switches it off immediately (integration active) and on top of that I am logged out (in private mode).

Then, I disabled the integration, reidentified myself in private mode.  I was able to switch the light on and off multiple times.  I need to reidentify myself only when I manually reload the page.

**Comment by mdeweerd** [comment]
Maybe this report on the HA forum is related: https://community.home-assistant.io/t/adaptive-lighting-hue-lidl-lights-lidl-lights-are-warmer/379053 .

**Comment by mdeweerd** [comment]
Yes, I am using LIDL lights as well.

**Comment by mdeweerd** [comment]
Here are some gif animations illustrating the impact of adaptive lighting.

# **With** adaptive lighting integration active on the light:

The light is actually already on, but always switches to off in the UI:
![LigthButtonResetWithAdaptive](https://user-images.githubusercontent.com/1504752/150676286-b947f7d5-6f33-47c1-855b-cd6a018265c1.gif)

When switching the light on, access to the temperature setting, etc shows only a very short moment as the light switches off again:
![LigthButtonResetWithAdaptive2](https://user-images.githubusercontent.com/1504752/150676292-0f81c0d3-a0e8-42b3-bffe-13b012da6422.gif)

# **Without** Adaptive ligthing integration active on the light:
The light can be switched on and off normally.
![LigthButtonResetWithoutAdaptive](https://user-images.githubusercontent.com/1504752/150676302-75b25eac-cc63-4656-ac2c-9c2cffd80d86.gif)

There is a strange UI behavior when changing the intensity (the UI switches the light to off but it is still on).  I can set on/off, intensity and temperature despite some strange behavious;
![LigthButtonResetWithoutAdaptive2](https://user-images.githubusercontent.com/1504752/150676306-decb1357-3fdf-4977-bd41-430595c79f7c.gif)

**Comment by mdeweerd** [comment]
FYI: I tested this on a "TI Sample Light" - the TI Sample Light does not have strange behavior, but Adaptive Lighting is not adapting it despite having configured it.

So, the controls of the TI Sample Light" are working normally, except that Adaptive Lighting does adapt it at all - with or without "prefer_rgb_color: Use 'rgb_color' rather than 'color_temp' when possible."

![image](https://user-images.githubusercontent.com/1504752/150677372-ffd6e0ec-63fc-47aa-8241-437e7ed25908.png)

![image](https://user-images.githubusercontent.com/1504752/150677616-09ce695e-1013-4e13-9cea-8de956bc6184.png)

**Comment by mdeweerd** [comment]
It looks like this is a LIDL light issue ...  It's sending back an off status when it's requested to be on...

https://github.com/zigpy/zha-device-handlers/issues/1303#issuecomment-1019570957

**Comment by mdeweerd** [comment]
The LIDL light I have is really not behaving correctly.

We can suppose that the fact that things get worse with Adaptive Lighting is essentially because of this bad behavior in association with the commands requested by Adaptive Lighting.

For me you can close this for Adaptive Lighting.

**Comment by mdeweerd** [comment]
I confirmed that this is due to the device by adding a ZHA quirk to ignore the OnOff attribute updates from the device.
