### ISSUE TITLE
Add proper sensors

### ISSUE THREAD

**Issue by poelzi** [basnijholt/adaptive-lighting#255]
It would be nice if proper sensors would be generated for each integration hat contains the calculated color and brightness of the integration.
This value can then be used for template values in scenes and automations.

**Comment by th3w1zard1** [comment]
Can you not already do this by just reading the attributes of the main adaptive-lighting switch? It will update its attributes with the last adapt call data after each `interval`

Adaptive-lighting exposes the following attributes in its switch:
```
brightness_pct: 1
color_temp_kelvin: 1000
color_temp_mired: 1000
rgb_color:
  - 255
  - 56
  - 0
xy_color:
  - 0.682
  - 0.315
hs_color:
  - 13.882
  - 100
sun_position: -0.7199188750393026
```
