### ISSUE TITLE
Use dimming without color temperature changes

### ISSUE THREAD

**Issue by pauldiloreto** [basnijholt/adaptive-lighting#260]
My apologies if there is already a way to do this, but I haven't been able to find it so far.

When using adaptive lighting with light switches, it only adjusts the brightness level throughout the day, which makes sense. WIth my RGB lights (currently using some Philips Hue lights), it adjusts the color temperature as well as the brightness based on the range in the settings. Obviously, this is the whole point of adaptive lighting, however, I was hoping to set up a separate instance of Adaptive Lighting integration for some Hue lights that I like to have set at certain colors.

Is it possible to set it up to only dim throughout the day, without changing the current color/scene?
_If_ this is not currently possible, I think it would make a great enhancement.

Thank you for the great plugin, by the way!

**Comment by jamescadd** [comment]
There's a switch for turning off color scheming. Add a second group of lights for the ones you don't want to change color, it will create the switch for them and you can turn it off.

**Comment by pauldiloreto** [comment]
Ohh I missed that. I had thought it would be in the integration config, but I see it creates an entity where I can switch it off like you said. Not super intuitive, but it works!

Thanks! I'll close this issue.
