### ISSUE TITLE
Allow the user to setup a delay between "turn on" and adaptive lightning changing values

### ISSUE THREAD

**Issue by Dumonster** [basnijholt/adaptive-lighting#262]
I'm using a template light.

The issue is that when the "light" comes on, sometimes the bulbs aren't yet connected to the network which leads to adaptive lighting failing to set the initial values and me having to wait 90 seconds for it to set everything up properly.

My current work around is an automation and disables and renables adaptive lighting whenever the light turns on but...

**Comment by Dumonster** [comment]
It seems that something was added regarding this on today's update.

When I switch on Adaptive Lightning, The colour will follow the initial transition.

However, the brightness won't. It just goes directly to the target value.

**Comment by th3w1zard1** [comment]
@Dumonster this seems like normal behavior though...? If you want adaptive-lighting to update faster than 90 seconds you simply need to set the interval lower. Am I missing something?

As for your second comment here, could you post your template light config and your adaptive-lighting config?
