### ISSUE TITLE
Send brightness and color adjustment multiple times with a delay

### ISSUE THREAD

**Issue by stoffelll** [basnijholt/adaptive-lighting#269]
I installled the adaptive-lighting and configured it accordingly. But I never got it really working even checking the debug logs.
So I build a similar feature manually with node red and had same issues, that my commands for brightness adjustment were not working.

Hence I added an delay of 10 seconds between detecting my bulb (Tradfri GU10) is going online (I switch them completely off - no power -> so I get an "on"-event by my hue bridge) until commands are accepted by the bulb.
Further testing the situation I recognized that some bulbs need up to 30 seconds to be completely operational.

Maybe its because I've around 50 bulbs connected to my bridge...

So additional parameter like delay and repeating the command would be helpful to somehow deal with the delays until bulbs are completely operational.

**Comment by broyuken** [comment]
This updates the bulbs every x seconds throughout the day. What’s the problem you’re seeing?

**Comment by patrickcollins12** [comment]
@stoffelll I have 50 Ikea bulbs and no such problems. I suggest reviewing your setup. I'm using zigbee2mqtt and USB stick zigbee controller. Do you see the same non-responsiveness from your switch remotes?

In any case, as @broyuken mentions, Adaptive Lighting is updating the lights very regularly in normal operation so any missed commands should get picked up on the next loop.

**Comment by th3w1zard1** [comment]
You just need to set the `interval` to something lower than the default of `90`
