### ISSUE TITLE
Switches don't appear in the logbook

### ISSUE THREAD

**Issue by Patrick1610** [basnijholt/adaptive-lighting#270]
#### Version information:
1.0.15

#### Description:

I have changed the 'Adaptive Lighting' sensor on/off several times, from automations and manually but the change never appears in the logbook. I haven't excluded those entities from logging. 
This makes troubleshooting much more difficult.

**Comment by th3w1zard1** [comment]
You still getting this issue with the latest Adaptive-lighting and latest home assistant core versions?

**Comment by th3w1zard1** [comment]
stale
