### ISSUE TITLE
KeyError on 2022.4

### ISSUE THREAD

**Issue by tivoo** [basnijholt/adaptive-lighting#272]
#### Version information:
adaptive_lighting 1.0.15
core-2022.4.0

#### Description:
After updating Home Assistant Core to 2022.4 I get a KeyError and the integration does not seem to be able to adjust the brightness / temperature. Adaptive Lighting switch is turned on and works after the lights turn on, but seems to be unable to continuously adjust the brightness / temperature. These parameters stay on the same value after the lights have been turned on.

I have not changed anything in my set-up and everything was working properly on 2022.3.8 before.
See error message below.

Error doing job: Task exception was never retrieved
```
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1257, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'
```

Thanks in advance.

**Comment by basnijholt** [comment]
I fixed the problem in PR https://github.com/basnijholt/adaptive-lighting/pull/321.

I will release 1.0.17 in a few minutes 🎉

Same problem as #75 #283.
