### ISSUE TITLE
Append entity names and ids to original

### ISSUE THREAD

**Issue by aetha** [basnijholt/adaptive-lighting#273]
I'm finding it inconvenient to have the default naming scheme of _"Adaptive Lighting [setting]: [name]"_ and `switch.adaptive_lighting[_setting]_[id]`. I prefer _"[name] Adaptive Lighting [setting]"_ and `switch.[id]_adaptive_lighting[_setting]`, as these sort to be just below the controlled entity in the entity lists, keeping them visually grouped together. Also makes it easier to remember their names when referencing them in yaml. Manually renaming all these after creating each integration instance is annoying.

Could you please add a global option to generate names and ids in this way, as an alternative to the default scheme?

**Comment by th3w1zard1** [comment]
This was added in 1.7.0
