### ISSUE TITLE
Different default icons for each control

### ISSUE THREAD

**Issue by aetha** [basnijholt/adaptive-lighting#274]
It'd be quite nice to have different default icons for each control, as this makes them easier to tell apart in entity lists, and when having a set of dashboard controls together. I suggest these:

- Keep `mdi:theme-light-dark` for master control
- `mdi:brightness-4` for brightness
- `mdi:sun-thermometer` for colour
- `mdi:sleep` for sleep mode

**Comment by th3w1zard1** [comment]
![image](https://user-images.githubusercontent.com/2219836/227215770-5ceefa6d-934a-4648-ab17-64c3e63bef77.png)

Looks good!
