### ISSUE TITLE
No attributes set in latest Home Assistant 2022.4.3

### ISSUE THREAD

**Issue by peter-dolkens** [basnijholt/adaptive-lighting#275]
#### Description:
After updating to the latest version of home assistant (2022.4.3), the switches no longer receive attribute updates.

I've tried removing the integration and re-adding it, removing the repository from HACS and re-adding it, and also adding the configuration via YAML explicitly, but nothing resulted in attributes being set.

```

  {{ states.switch.adaptive_lighting_home }}

  <template TemplateState(<state switch.adaptive_lighting_home=on; icon=mdi:theme-light-dark, friendly_name=Adaptive Lighting: 
home @ 2022-04-14T14:43:36.567469+01:00>)>

```

## System Health

version | core-2022.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4917
Installed Version | 1.24.5
Stage | running
Available Repositories | 1028
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 15.2 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), File editor (5.3.3), Terminal & SSH (9.3.0), Zigbee2mqtt (1.18.1-1), Samba share (9.5.1), Node-RED (11.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 5
mode | storage

</details>

**Comment by Joebinator** [comment]
Same problem here :(

Any ideas on how to fix or work around this?

**Comment by th3w1zard1** [comment]
Assuming this has been fixed?
