### ISSUE TITLE
Adapt Color switch not working

### ISSUE THREAD

**Issue by sambarlick** [basnijholt/adaptive-lighting#279]
#### Version information:
2022.4.7

#### Description:
The entity adapt Color switch does not seem to work. 
The switch itself toggles on and off but it has no affect.

![Screenshot_20220426-213712](https://user-images.githubusercontent.com/47462284/165291743-b46b9880-9445-41b4-b022-cfe7c71cc311.png)

**Comment by cameronurnes** [comment]
Can confirm it seems to have no impact.  If I turn off the color switch, and change the light to a color... adaptive lighting still resets the color on every next cycle, removing the current color setting.

**Comment by basnijholt** [comment]
I have just tested the behavior locally, it definitely works for my lights.

Are you sure you do not have multiple Adaptive Lighting switches where the lights also appear? If not, are there any error messages in the logs?

**Comment by th3w1zard1** [comment]
stale
