### ISSUE TITLE
Can't uncheck delete light

### ISSUE THREAD

**Issue by LukaszP2** [basnijholt/adaptive-lighting#287]
#### Description:
If light is deleted, can't uncheck this light in configuration.

**Comment by cinghialino** [comment]
Same problem here. To solve it, I need to delete the whole profile and recreate it.

**Comment by tjxism** [comment]
Confirm the issue exists. Will it be enhanced in 2.0 release?😹

**Comment by RubenKelevra** [comment]
Yeah, super annoying issue I ran into the other day as well.

Deleting and recreating the integration isn't really a neat workaround. 😆 

@tjxism you guessed right, I'll add this to the list ;D

**Comment by sn33ky** [comment]
Same problem. And the most irritating part is, when this happens, you can not even change other configurations from the settings menu

**Comment by peter--s** [comment]
This is the same as #278, #236, #220 and seems to have started with 2021.11's dropdown list (see #213), which is addressed in [Frontend #10608](https://github.com/home-assistant/frontend/issues/10608)

**Comment by danaues** [comment]
PR to fix this issue:
https://github.com/basnijholt/adaptive-lighting/pull/350

**Comment by basnijholt** [comment]
Closed by #350 thank to @danaues :tada:
