### ISSUE TITLE
Displayname in HACS

### ISSUE THREAD

**Issue by RubenKelevra** [basnijholt/adaptive-lighting#292]
### Discussed in https://github.com/basnijholt/adaptive-lighting/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **brgerig** August 28, 2021</sup>
HACS shows the name of the component as "adaptive_lighting". Would it be better displayed as "Adaptive Lighting"?</div>

**Comment by bcutter** [comment]
> But should already be the case:
> 
> https://github.com/basnijholt/adaptive-lighting/blob/8abeee974162e1a611f8fa0a0cf34c6afc21f68c/hacs.json#L2

Final result in integration overview section:
![grafik](https://user-images.githubusercontent.com/13799156/179837772-d92fcd50-faa3-45a2-8f88-5254114820ff.png)

Only in detail view it is looking fine:
![grafik](https://user-images.githubusercontent.com/13799156/179837878-9f613a63-2c6c-4b6d-afaa-fc8cde37b833.png)

**Comment by basnijholt** [comment]
This is fixed now:

![Uploading image.png…]()
