### ISSUE TITLE
I revamped the icon

### ISSUE THREAD

**Issue by KTibow** [basnijholt/adaptive-lighting#295]
I made the icon look a little better (at least in my opinion). I suppose this would need another PR to the brands repo to implement it.
```
<svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="ColorTempGradient" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="hsl(30, 80%, 80%)" />
            <stop offset="100%" stop-color="hsl(200, 80%, 80%)" />
        </linearGradient>
        <linearGradient id="MetalGradient" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stop-color="hsl(0, 0%, 70%)" />
            <stop offset="50%" stop-color="hsl(0, 0%, 50%)" />
            <stop offset="100%" stop-color="hsl(0, 0%, 70%)" />
        </linearGradient>
    </defs>
    <rect x="224" y="384" width="64" height="128" fill="url(#MetalGradient)" />
    <circle cx="256" cy="256" r="192" fill="url(#ColorTempGradient)" />
</svg>
```
Before:
![image](https://user-images.githubusercontent.com/10727862/175313739-4fc19859-047a-4146-a6a7-cccc471dc46c.png)
After:
![adaptive_lighting](https://user-images.githubusercontent.com/10727862/175313958-21a5f9f4-3475-4858-96c2-e36b6adeb819.png)

**Comment by basnijholt** [comment]
That looks great! 😍

Could you open that PR?

**Comment by KTibow** [comment]
Sure, I'll go ahead and do that.

**Comment by RubenKelevra** [comment]
@KTibow thanks! Looks much better. Just note that I plan to replace the icon in the future :)
