### ISSUE TITLE
A light is responding to adaptive lighting which is not added to an instance. Where's the instance data stored?

### ISSUE THREAD

**Issue by smarthomejunkie** [basnijholt/adaptive-lighting#296]
#### Description:
A light in my office is responding to adaptive lighting which is not added to any instance. It seems that it responds as soon as the brightness is decreasing for instances. The weird thing is, that this light has never been part of any instance. 

Where is the instance data stored? I looked into the .storage folder, but I cannot seem to find a yaml file that contains the light entities for each instance.

Please try to include:
  * What you were doing when you experienced the bug.
  * Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
  * When possible, steps to reliably produce the bug.
-->

**Comment by smarthomejunkie** [comment]
I removed all the instances and the Hacs integration, rebooted HA twice, and installed everything again. The issue seems not to be there anymore. Not sure what happened, but for now I will close the issue.

**Comment by nathang21** [comment]
I suspect I had a similar issue, was experiencing a bunch of odd AL behavior, and when looking at the logs, instances I had long deleted were still running, which explains the conflicts I was having with the AL instances I did have enabled. 

I completed removed all, uninstalled, rebooted HA, purged the DB, and then re-installed and setup AL again carefully, and it seems to be working now.
