### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by besiktas97** [basnijholt/adaptive-lighting#299]
#### Version information:
1.0.15 -> latest version

#### Description:

I have only one entity that I use for it and thats a group of 5 bulbs in it to turn on by a button on the dashboard in the evening. And when we are going to sleep we are turning it off. Have no automations or something else, so the only thing that will give this error log are those 5 bulbs. But why I am getting this error, is unknown for me.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1257 
Integration: Adaptive Lighting (documentation, issues) 
First occurred: July 3, 2022, 01:58:03 (2 occurrences) 
Last logged: 01:26:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1257, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'

**Comment by kompiz** [comment]
This looks like a double of https://github.com/basnijholt/adaptive-lighting/issues/283. OP, check that thread, there seems to be a workaround.

**Comment by besiktas97** [comment]
> This looks like a double of https://github.com/basnijholt/adaptive-lighting/issues/283. OP, check that thread, there seems to be a workaround.

Thank you. Will check it out.

**Comment by basnijholt** [comment]
That's correct.

I fixed the problem in PR https://github.com/basnijholt/adaptive-lighting/pull/321.

Please update :-)
