### ISSUE TITLE
Is everything in const.py valid for config?

### ISSUE THREAD

**Issue by KTibow** [basnijholt/adaptive-lighting#3]
When I was making the docs, I only used configuration variables in your "full configuration example". I was looking at the source, and there's a couple variables in there not in the example in the PR. Are all of them valid?

**Comment by basnijholt** [comment]
The examples in my PR are out-of-date, all options in conf.py are valid!

Also, check out `strings.json` for an explanation. 

Thanks a lot for the help with the documentation BTW 😄
