### ISSUE TITLE
Lights within adaptive light instances are turned on after restart of Home Assistant

### ISSUE THREAD

**Issue by smarthomejunkie** [basnijholt/adaptive-lighting#300]
#### Description:
When you restart Home Assistant, all lights that are part of one or more adaptive lighting instances are turned on after Home Assistant has started.

Please try to include:
  * What you were doing when you experienced the bug.
  * Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
  * When possible, steps to reliably produce the bug.
-->

**Comment by dekiesel** [comment]
I restart my HA daily and I don't see any lights coming on at startup. I have one wifi bulb, one wled and two (ikea) zigbee bulbs.

**Comment by smarthomejunkie** [comment]
> I restart my HA daily and I don't see any lights coming on at startup. I have one wifi bulb, one wled and two (ikea) zigbee bulbs.

That is strange. I do see them come on every time when I restart Home Assistant. When I remove the Adaptive lighting instance, those lights do not come on anymore after restart.

**Comment by smarthomejunkie** [comment]
Just found out that they still turn on after a new update of Home Assistant af available. When installing the update and Home Assistant restarts after the update, all lights that are part of an adaptive lighting instance turn on.

**Comment by smarthomejunkie** [comment]
Okay, I  did a search on Google and it seems  due to Zigbee2MQTT and retaining the states. Will close this again until further notice.

**Comment by dekiesel** [comment]
In case you haven't already: maybe you can find something in the debug logs. 
```
logger:
  default: warning
  logs:
      custom_components.adaptive_lighting: debug```

I probably f'ed the formatting because I am on mobile.

**Comment by smarthomejunkie** [comment]
I can confirm that it was a bug in Zigbee2MQTT that is fixed in the dev branch of Zigbee2MQTT now.
