### ISSUE TITLE
Event to get all switches and add a list of lights controlled by a switch to its state attributes

### ISSUE THREAD

**Issue by dekiesel** [basnijholt/adaptive-lighting#303]
Hi,

Thanks for this great piece of code!

It would be great if there was an event that when fired would hand back a list of  all AL switches.

I could then have a look at the states of these switches to find out what lights these switches control and toggle them on/off automatically.

Use case: I have a light that is (beautifully) controlled by AL. But if one of my automations needs momentary control over that light I need to hardcode the switch name in the automation.

With the two new features I could simply look up all the relevant switches and flip them without having to hardcode anything.

I have looked through the roadmap for v2 but not found these addessed :)

**Comment by FADEC44** [comment]
+1 for this, especially adding the controlled lights list to the switch attributes.  It's gating my ability to handle things dynamically in some of my NetDaemon automations.  

Hope to see this added to the roadmap!

**Comment by dekiesel** [comment]
Thanks for the new release. While it helps a bit I don't think it addresses the issue.

I still need to manually hardcode (and manually update) a list of all AL switches on my automation(s) to find the light whose switch I need to turn off.

It's be great if AL could react to an event my automation fired and answer with a list of switches and their attached lights.

**Comment by th3w1zard1** [comment]
How do you suppose adaptive lighting should do this @dekiesel?

**Comment by th3w1zard1** [comment]
@dekiesel #459 has the feature you want I believe. With it you won't need to worry about which switch has which light or anything, you simply call adaptive_lighting.apply or set_manual_control with the light.

The switch is optional: the integration is smart enough to figure out which switch contains the light.

**Comment by th3w1zard1** [comment]
@dekiesel if you still need a collective list of switches, try this template in your automation/script (this works in any adaptive lighting version)
```
{{ states.switch
    | map(attribute="entity_id")
    | select(">", "switch.adaptive_lighting_al_")
    | select("<", "switch.adaptive_lighting_al_z")
    | join(",")
}}
```

**Comment by dekiesel** [comment]
@th3w1zard1 ,

#459 seems  to solve my problem, thank you very much!
