### ISSUE TITLE
Set Night Mode RGB value

### ISSUE THREAD

**Issue by sovanyio** [basnijholt/adaptive-lighting#31]
Currently upgrading from the circadian_lighting setup. With that one, I have a automation scene external to the integration at sun-down that sets all color lights to red and then hands off brightness control only to the circadian service.

Would love for something like that to be integrated here, seems that the base is already there to support it. I think these items would greatly extend use cases:
- [x] Sleep mode scheduling / sun event offset
- [ ] Allow RGB pinning to a single color or an RGB target to transition to during the time period covered by the above

**Comment by RubenKelevra** [comment]
Hey @sovanyio,

can you create for your list of possible features individual tickets? I feel like they are worth tracking on their own. :)

**Comment by sovanyio** [comment]
As I was going to do that, I re-reviewed the current state and it looks like the first item has already been taken care of. Still want me to create a second ticket for the remaining item of the manual sleep setting, I think we can track here?

I'd revise my list to this single item for this issue:
- [ ] Allow for sleep color override, rgb/xy/temp

I see from #150 the note that the transition isn't straightforward if the color type isn't the same (temp vs rgb, for example). For my usages, I think it would be ok to abruptly change or otherwise rely on a bulb's built-in transitional capabilities. 

Otherwise, I'm not sure how accurate it is, but there does seem to be an approximation for temperature <-> rgb: https://andi-siess.de/rgb-to-color-temperature/ Maybe a similar relationship is defined already for xy as well and can be used to get close-enough and then pop to the set color?

**Comment by RubenKelevra** [comment]
I'm currently in the process of doing version 2. This will be added/fixed.

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.

**Comment by basnijholt** [comment]
Who's excited?!

<img width="498" alt="image" src="https://user-images.githubusercontent.com/6897215/187840527-f0c88d7f-541f-4f73-bac9-a3d1ed35892c.png">

See https://github.com/basnijholt/adaptive-lighting/pull/329

**Comment by basnijholt** [comment]
I have just released [1.1.0](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.1.0) where you can set the sleep color using RGB.

This issue can finally be closed! :tada

**Comment by d-nx** [comment]
> Who's excited?!
> 
> <img alt="image" width="498" src="https://user-images.githubusercontent.com/6897215/187840527-f0c88d7f-541f-4f73-bac9-a3d1ed35892c.png">
> 
> See #329

I'm running v1.2.1 but can't see this color picker option. I'd love to use this feature ! =)

**Comment by basnijholt** [comment]
There was this problem https://github.com/home-assistant/frontend/issues/14314#issuecomment-1305402907 that was supposed to be fixed.
