### ISSUE TITLE
Sleep mode minimum seems too bright in our RV

### ISSUE THREAD

**Issue by PieBru** [basnijholt/adaptive-lighting#328]
Hi, in our RV we are just appreciating the great benefits of using adaptive lighting.

However, the sleep mode seems too "aggressive" when one wakes during the night. It may be because of the unusually small space lighted by the bulb. I'm using a high quality RGBW bulb (Zigbee) by Ledvance (Osram GmbH): https://www.amazon.it/gp/product/B07VHRP4PS (4x 60€)

Default config values are OK, but it would be nice to be able to lower the temperature <1000°K and/or the brightness <1% (float), without tampering locally with `VALIDATION_TUPLES` in `config.py`, thus loosing the click-to-update laziness.

Thank you,
Piero

**Comment by ASNNetworks** [comment]
Has nothing to do with this integration, but with your lightbulbs. Your Osram lights are fairly cheap and I know that most cheap lights don't have 1% brightness. They have the setting, but the light itself doesn't go any lower than like 5-10%. I used a few Osrams before and noticed the same thing with the cheaper IKEA ones. You can't lower the brightness visually than what the light itself supports.

I also use Hue RGBW lightbulbs, which are more expensive but perform a lot better. 1% brightness is extremely dim.

**Comment by PieBru** [comment]
Thank you for your... illuminating reply.
I will continue using your Adaptive Lighting, but as I don't like to spend 40€ for one E27 bulb, I will look for other hardware soutions, eventually DIY, like ESPhome wifi bulbs instead of Zigbee, or other DIY solutions.
Thank you again for your addon and your support.
Piero
