### ISSUE TITLE
HA 2022.9 Issue cannot import name 'ATTR_WHITE_VALUE' 

### ISSUE THREAD

**Issue by jacko85** [basnijholt/adaptive-lighting#336]
Hi,

Since updated to HA 2022.9, the integration isn't loading with the UI showing "Failed to set up: Import error"

The log itself shows this error:
Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

A quick search for that shows this might be affecting other integrations also https://github.com/StyraHem/ShellyForHASS/issues/713

**Comment by basnijholt** [comment]
Please update to the latest version of Adaptive Lighting. This issue should be fixed.

**Comment by jacko85** [comment]
That worked, perfect thankyou. 

Wish HACS updates were more obvious! :)

**Comment by Alethio36** [comment]
solved the issue for me as well (the update). i agree, the HACS update is kinda sneaky
