### ISSUE TITLE
`adaptive_lighting.set_manual_control` is now an "unknown service" in HA 2022.9.0

### ISSUE THREAD

**Issue by daFreeMan** [basnijholt/adaptive-lighting#337]
#### Version information:
AL 1.1.0
Previous version: 1.0.15

#### Description:
My Home Assistant updated overnight to build 2022.9.0. When I woke up, some lights didn't turn as they were supposed to. I took a look at my HA screen and saw 6 "repairs" listed in the notification, all telling me essentially the same thing:

```
The automation "Manual Lights off - Kitchen" (automation.manual_lights_off_kitchen) has an action that calls an unknown service: adaptive_lighting.set_manual_control.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.5:8123/config/automation/edit/1639522759747Kitchen) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.
```

After some poking around, I realized that I needed to update several of my HACS integrations (including AL), so I did so. I went from HA 2022.8 and AL 1.0.15 to HA 2022.9 and AL 1.1.0, and the errors persist. 

I presume that something changed in the HA 2022.9 update that AL will need to be adapted for in order to properly export the `adaptive_lighting.set_manual_control` command again, but I really don't have a clue.

**Comment by TheRealLink** [comment]
Yeah, something seems broken...

```
Logger: homeassistant.config_entries
Source: config_entries.py:338 
First occurred: 16:07:21 (1 occurrences) 
Last logged: 16:07:21

Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)
```

**Comment by basnijholt** [comment]
@TheRealLink, update to the new version. That will solve that issue.

**Comment by basnijholt** [comment]
@daFreeMan, it works for me. What version are you using?

**Comment by daFreeMan** [comment]
@basnijholt What version is "the new version"?

**Comment by daFreeMan** [comment]
Also, HA updated overnight again, now v2022.9.1, however the "Repairs" remain.

**Comment by jamieboy05** [comment]
My VM recently crashed and I'm having to start over, but prior to losing my configuration, it did indeed show as an unknown service.  Now when attempting to reinstall, it installs in HACS but doesn't show when attempting to add the service on the frontend, and when trying to configure through YAML the service won't load.

**Comment by julian-klode** [comment]
FWIW, had the same error, pulled latest git HEAD and it works again, thanks!

**Comment by jamieboy05** [comment]
So, I changed the release to the master release instead of 1.1.0, rebooted and the frontend is now working.  Thanks!

> FWIW, had the same error, pulled latest git HEAD and it works again, thanks!

**Comment by daFreeMan** [comment]
@julian-klode  or @jamieboy05 you're implying that my copy of AL may have been corrupted and I need to reinstall it? I'll give that a shot. Thanks.

**Comment by daFreeMan** [comment]
After removing/installing I've still got the `Repairs` listed. Do they go away on their own or do I have to acknowledge them and see if they come back?

**Comment by daFreeMan** [comment]
I've manually cleared the `Repairs` and they don't seem to have come back. I guess this is resolved...
