### ISSUE TITLE
Disabling sleep mode sometimes doesn't work properly

### ISSUE THREAD

**Issue by StSaens** [basnijholt/adaptive-lighting#344]
#### Description:
I noticed that sometimes disabling sleep mode on my kitchen light doesn't work properly.
I'd expect the light to switch to brightness as AL determines it to be (80%-100%), but it stays at 1% (which I set in AL settings).
I'm guessing 1/15 times it doesn't switch properly. It switches to the correct brightness after a few 10s of seconds.

To reproduce:
I just toggle the AL sleep mode switch in my HA dashboard until it fails to switch to correct brightness.

Light that is used is an Ikea Tradfri. 
Homeassistant OS (latest version)
Zigbee2mqtt latest version 1.27.2-1
Stick a Sonoff Zigbee 3.0 USB Dongle Plus (CC2652P)

Unsure which logs you'd need. But I'd be happy to see what I can find.

**Comment by th3w1zard1** [comment]
Toggling the al sleep mode switch in the dashboard is exactly how I test other unrelated code I develop for the project.
For us to help you diagnose why you're experiencing this, you'd need to post logs of you flipping the switch. You can turn debug logging on with these instructions from the readme:

>Please enable debug logging by putting this in configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.adaptive_lighting: debug
```
>and after the problem occurs please create an issue with the log (/config/home-assistant.log).

**Comment by th3w1zard1** [comment]
stale
