### ISSUE TITLE
Restore previous state of light when adaptive lighting is turned off

### ISSUE THREAD

**Issue by zachboatwright** [basnijholt/adaptive-lighting#347]
I would love to have the optional feature to restore a light to its previous state when adaptive lighting mode is turned off. This would be really useful for those of us who like to switch between using their lights for fun (like when watching a movie or relaxing) and using them for utility (like cleaning or eating). It's annoying to have to reset the scene every time. 

**Expected Behavior**
- Adaptive lighting is not currently turned on for my room. I change the scene for the room. I have a green, blue, and pink light, all at 50% brightness.
- I turn on adaptive lighting. The lights update their settings to the current adaptive lighting color/brightness levels.
- I turn off adaptive lighting. The lights revert back to green, blue, and pink, and 50% brightness.

I suppose I could do this by creating an automation that saves the state of the room lights, then turns on adaptive lighting, and restores said state when adaptive lighting is turned off, but having it as a native option would be really nice.

**Comment by porchthecoder** [comment]
Another vote here. I would love to have a way to toggle all lights that are currently on, to 100% brightness and disable adaptive control. For when I am looking for something, cleaning, or need the light.

**Comment by MattKaboom** [comment]
https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly

**Comment by zachboatwright** [comment]
> https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly

That's what I'm currently doing, but I think in this situation it would make sense to have it as an option when setting up a group.

**Comment by th3w1zard1** [comment]
This feature is very unnecessary.
The correct sequence of events you're looking for:
\> ensure you have `take_over_control: true` set in the adaptive-lighting config
\> turn on adaptive-lighting's main switch
\> change the scene for the room to your green, blue, and pink light, at your desired 50% brightness.

at this point `adaptive-lighting` will fire a manual control event for that light group, and will stop adapting it until you call the service `adaptive_lighting.set_manual_control` with the service data `manual_control: false` (or just turn off and on the main adapt switch)

**Comment by th3w1zard1** [comment]
Stale/duplicate - closing.
