### ISSUE TITLE
Entity Name Change

### ISSUE THREAD

**Issue by Fonzi03** [basnijholt/adaptive-lighting#349]
When you change an entity name and the original name is no longer valid there is no way to de-select the no longer existing name. Trying to modify the existing automation results in an error that the previous entity is no longer available.

**Comment by danaues** [comment]
I've just posted a PR for this issue.  It's been driving me crazy as well.

https://github.com/basnijholt/adaptive-lighting/pull/350

**Comment by basnijholt** [comment]
Closed by #350 thank to @danaues :tada:
