### ISSUE TITLE
Enable dynamic offset for max brightness

### ISSUE THREAD

**Issue by ErikApption** [basnijholt/adaptive-lighting#352]
I believe this is not possible today but I was looking for a way to adjust the max brightness depending on a light sensor. The idea is that on a bright day, I'd like to lower the max brightness. Is something like that possible today?

**Comment by hickmanz** [comment]
I would also love to see a feature like this but for the opposite reason!

On a cloudy/rainy day Im interested in turning the max brightness down a bit.

Being able to adjust `max_color_temp` would also be useful here.
