### ISSUE TITLE
What is the recommended approach for using prefer_rgb_color during sleep mode only?

### ISSUE THREAD

**Issue by tnunamak** [basnijholt/adaptive-lighting#36]
Maybe this should be a feature request instead, I am not sure.

I have an automation that activates sleep mode in a manner similar to the one shown in the [documentation](https://deploy-preview-14877--home-assistant-docs.netlify.app/integrations/adaptive_lighting/#automation-examples). If I extend this automation to also toggle `prefer_rgb_color` via `adaptive_lighting.apply`, my lights are adapted accordingly, but then they are adapted back to the original setting a moment later.

Is it possible to keep adaptive lighting on, but modify this setting until I turn sleep mode off?

**Comment by basnijholt** [comment]
Currently, that is not possible.

You could have two switches, one with `prefer_rgb_color: true` and the other with `prefer_rgb_color: false` then toggle the switch when sleep_mode is on.

**Comment by RubenKelevra** [comment]
@tnunamak would you like to convert this into a feature request?

In this case this ones might be related:

- https://github.com/basnijholt/adaptive-lighting/issues/132
- https://github.com/basnijholt/adaptive-lighting/issues/135

**Comment by basnijholt** [comment]
Who's excited?!

<img width="498" alt="image" src="https://user-images.githubusercontent.com/6897215/187840527-f0c88d7f-541f-4f73-bac9-a3d1ed35892c.png">

See https://github.com/basnijholt/adaptive-lighting/pull/329

**Comment by basnijholt** [comment]
I have just released [1.1.0](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.1.0) where you can set the sleep color using RGB.

This issue can finally be closed! :tada
