### ISSUE TITLE
Adaptive Lighting broken with new z2m version and a non transition dimmer.

### ISSUE THREAD

**Issue by MarcPot** [basnijholt/adaptive-lighting#378]
#### Version information:
Latest

#### Description:
Every brightness call adaptive lighting makes the “transition” parameter is also transferred.
Previously z2m would just error this and send the command anyways, but with the new z2m version it will error and not send.

On my z2m issue they commented that the transition parameter is optional in Home Assistant, and that I should take it up with the integration that’s incorrectly sending this parameter.

A solution would be to add a “None” to the transition time disabling the transition parameter completely.

**Comment by hilsonp** [comment]
I think this "bug" created a really strange effect on my Ikea light bulbs.
The light would slightly dim every "interval" time (ie: 90sec) then the light would slowly get brighter until the interval passed where it would dim again and raise again for 90 secs...
The "breathing" bulb effect was driving me crazy until I read this description.
In my case, I did set the "Transition time when applying a change to the lights" to 0 and this made the trick.

**Comment by th3w1zard1** [comment]
Came to post I'm also having this issue with the latest build.

**Comment by th3w1zard1** [comment]
Found original issue he mentioned @ https://github.com/Koenkk/zigbee2mqtt/issues/15057

**Comment by th3w1zard1** [comment]
Looking back at the date this was posted, adaptive-lighting v1.2.1 was the current version at the time. Going back even further I still see that this code exists:
```
        if "transition" in features:
            service_data[ATTR_TRANSITION] = transition
```
Transition should only be set if the light claims to support the feature. If the light does not support transitions and is incorrectly displaying that it does, that is a Z2M problem. Regardless I think we'll just prevent transitions of 0 moving forward as it can't hurt anything.
