### ISSUE TITLE
RGB channel intensity sliders for led strips

### ISSUE THREAD

**Issue by xenophobentx** [basnijholt/adaptive-lighting#379]
Hello,

Itt would be a nice feature to adjust per channel RGB intensity when calculating colors  for RGB mode. Some light strips has to bright BLUE leds for example and warm(orangeish) yellow tends to be to cold. 
Unfortunatly only esphome based led drivers have such settings to adjust the channel intensity.

**Comment by th3w1zard1** [comment]
![image](https://user-images.githubusercontent.com/2219836/226807622-3d06411b-fae4-47ab-9253-2117a98ac123.png)
This is the UI directly from HASS, and as such there's not much adaptive-lighting can do about it.

Click on the bottom right <> next to R G B. You can modify whatever values you want. You can even goto a 3rd party website, copy a hex color code and paste it right in.

hass's dev tools will let you call `light.turn_on` so you can confirm the RGB color is exactly what you'd like before pasting it in your config.
