### ISSUE TITLE
Initial transition only when turning off sleepmode

### ISSUE THREAD

**Issue by smqrt** [basnijholt/adaptive-lighting#38]
Most of the lights in my house are controlled by motion sensors. In the mornings we find the lights get too bright too early so we leave on night mode longer. To get a smooth transition when night mode turns off (in my case 20% -> 100% most of the time) we set an hight initial transition. 

The problem with motion sensor control is that my lights ar regularly turned of and on. And every time it turns on it gets the initial transition which takes to long to change the lights when you want them to change quickly during day time.

I could make more switches and set the according switches based on daytime to overcome this, but it would be nice to have an transition time only for switching night mode off.

**Comment by Jason-nz** [comment]
You could just use the [service](https://deploy-preview-14877--home-assistant-docs.netlify.app/integrations/adaptive_lighting/#services) to turn on the light when motion is detected and set the transition there.

**Comment by RubenKelevra** [comment]
Hey @smqrt,

I can see the issue and why this would be nice to have.

I think a master switch for the lights would be all you need, right?

In this case that ticket here would be superseded by https://github.com/basnijholt/adaptive-lighting/issues/132

**Comment by RubenKelevra** [comment]
I think that's fixed in 1.0.15. 

If not, LMK
