### ISSUE TITLE
updated to 1.2.1 integration shows not loaded, can not downgrade

### ISSUE THREAD

**Issue by shikon** [basnijholt/adaptive-lighting#382]
The configuration broke after updating to 1.2.1.
It doesn't load and therefore does not work.

I tried everything to remove it.
But the integration can not be removed from HACS unless it is removed from HA, however this is not possible.
I tried downgrading to any version, 1.1.0 or 1.2.0, but that does not work either. Now I am stuck with a broken integration while I really like the integration and would love to get it working again.

**Comment by mpeterson** [comment]
@basnijholt I think with release 1.2.1 the manifest was not updated. Could this be the problem? I also find myself getting an older version every time I try to update or uninstall/install

**Comment by shikon** [comment]
Hey I am not so sure what you mean with manifest?

I was able to remove the integration now, and also deleted it from HACS.

However after adding it with the latest version 1.4 or 1.2 it seems that in the HA interface it tells config flow not loaded. Is there any debugging files I can view?

**Comment by th3w1zard1** [comment]
I'd be happy to look into this if someone could explain how to reproduce this.

**Comment by mpeterson** [comment]
@th3w1zard1 i think this has been fixed already. At least for me, it did.

**Comment by th3w1zard1** [comment]
@mpeterson Are you certain? I imagine it'll still happen for anyone updating from 1.2.0 and lower.
