### ISSUE TITLE
take over control not working when changing color temperature

### ISSUE THREAD

**Issue by adri535** [basnijholt/adaptive-lighting#394]
Version 1.2.1

I have hue white ambiance bulbs setup with AL & take over control enabled.
When changing brightness of a certain bulb, it is added to the manual control list as expected. 
When changing color temperature however (which also triggers a light.turn_on service call) it is not added to the manual control list hence AL changes it back after a few seconds.

I have 'debugged' this with Node red: the first service call is me manually changing the color temp, a couple of seconds later you can see AL is still updating the light.
![image](https://user-images.githubusercontent.com/3929958/205518121-799656f3-71ae-409a-b562-3e0eb7ea1f4a.png)
![image](https://user-images.githubusercontent.com/3929958/205518135-8de11e00-40e7-4b17-9a4b-2e8b51acf558.png)

**Comment by basnijholt** [comment]
This used to work and this problem arises because you send an update in Kelvin and Adaptive-lighting works with color_temp.

I believe that once https://github.com/basnijholt/adaptive-lighting/pull/375 is merged, it should work again.

**Comment by basnijholt** [comment]
Could you check whether 1.4.0 fixes the problem? https://github.com/basnijholt/adaptive-lighting/releases/tag/1.4.0

**Comment by RedQuarck** [comment]
Just updated and tested, it sounds like it's working fine now.
(can see the manual_control attribute correctly updated when changing light temperature)
Thanks a lot :-)

**Comment by basnijholt** [comment]
Great! I’ll close this issue then.
