### ISSUE TITLE
Some lights change color temperature on plain white

### ISSUE THREAD

**Issue by KTibow** [basnijholt/adaptive-lighting#4]
Some lights have a warm white when they're not in color mode, and then when they're slightly off white they're a cooler white (R + G + B instead of Warm White). Can adaptive lighting work with this behavior?

**Comment by basnijholt** [comment]
Sorry, I didn't get notified of these issues, I am only seeing it now.

I do not understand the problem, could you try rephrasing it?

**Comment by KTibow** [comment]
I have some RGBW Tuya lights.
When you set them to white (exactly, no difference) it turns on the bright warm white LED.
But if they're a bit off white, then they are a cooler color temperature.

**Comment by basnijholt** [comment]
Sure!

Do you mean that when you do
```
service: light.turn_on
data:
   ...
   color_name: white
```
you do not get a white light?

Still not follow the problem.

**Comment by KTibow** [comment]
Well it's white, but it's warm white. If it's a tiny bit off, it's cool white.
"Hey Google, set the light to white."
![20201015_114329](https://user-images.githubusercontent.com/10727862/96172969-025a5300-0edc-11eb-8414-9ecefc382796.jpg)
"Hey Google, set the light to light yellow."
![20201015_114347](https://user-images.githubusercontent.com/10727862/96172980-06867080-0edc-11eb-97bd-ceee6ec78656.jpg)
"Hey Google, set the light to light blue."
![20201015_114357](https://user-images.githubusercontent.com/10727862/96172996-0e461500-0edc-11eb-98ed-1ecd58fc9cd9.jpg)

**Comment by basnijholt** [comment]
OK now, I understand!

Adaptive Lighting just sets a color temperature and not by `color_name` (which is translated to rgb).

Do you notice this problem when using the integration? If so, did you try switching on/off the `prefer_rgb_color` option?

**Comment by KTibow** [comment]
It is using RGB color over color temperature, but this device only supports RGB, no color temp. I didn't notice this problem, I was just thinking it would be a good idea to first check it isn't pure white before sending the light.turn_on.

**Comment by basnijholt** [comment]
Ah, this seems a bit of an edge case. Maybe you could have an automation that checks whether the light is on pure white when `adaptive_lighting` is enabled?

**Comment by KTibow** [comment]
Yeah, I guess that would work.
