### ISSUE TITLE
Turning on, hue ambient white lights go green in transition

### ISSUE THREAD

**Issue by andrewfitz** [basnijholt/adaptive-lighting#404]
Latest version of HA and AL and hue firmwares

When turning on the lights and they are warm color temp and it's now daytime, they turn green on their way to white cool temp. It's a very unpleasant green effect that doesn't happen when using the sliders, only when AL adjusts when turning on going from one extreme of color temp to the other.

**Comment by basnijholt** [comment]
Can you enable debugging logging (https://github.com/basnijholt/adaptive-lighting#having-problems) and tell me the `service_data` associated with setting the color of the lights?

**Comment by andrewfitz** [comment]
Hi, I have just updated, and the issue doesn't seem to be happening anymore. Was this possible due to the change to kelvin vs mired or whatever was fixed? Thanks!

**Comment by basnijholt** [comment]
That's possible 😄

Thanks for reporting back, let's close this issue.
