### ISSUE TITLE
Ikea bulbs in Z2M groups do not dim when turned off and then on using standard wall switch.

### ISSUE THREAD

**Issue by kodifan** [basnijholt/adaptive-lighting#406]
Hello
I have two Z2M groups with Ikea gu10 bulbs. They are connected thru standard  wall switch.
Problem is when I switch it off , status of those bulbs remains on in Z2M and HA.
And that causes Adaptive lightning not working as expected when I turn them on. What is quite obvious because no state change is detected.
But Im pretty sure that some time ago it was working. And Im not sure what change made it stop to work (adaptive-lighting or HA or both).
One of those groups is now connected thru smart relay  and with some automation is working as expected.
But the other one could not be connected thru smart relay yet , so its turned on/off by dump wall switch.

Two questions:
1. is it possible that it was working for first group some time ago or I just do not remember it correctly ?
2. is it possible to make it work for second group currently ?

**Comment by th3w1zard1** [comment]
Can you post your zigbee2mqtt configuration.yaml and your adaptive-lighting config?
I believe this happens when `optimistic: false` is set inside zigbee2mqtt, or if there's another issue with reporting related to your zigbee config.
