### ISSUE TITLE
1.4.1 update: Error importing platform config_flow: cannot import name 'ATTR_COLOR_TEMP_KELVIN'

### ISSUE THREAD

**Issue by LuccoJ** [basnijholt/adaptive-lighting#407]
#### Version information:
Version 1.4.1, updating from... I'm not really sure, to be honest! Presumably whatever came before.

Home Assistant version "Home Assistant 2022.10.4 Frontend 20221010.0 - latest"

#### Description:
All three of my adaptive lighting entities show a red exclamation mark in the UI and do not work, all of the adaptive lighting switches are unavailable, and the logs show
````ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'ATTR_COLOR_TEMP_KELVIN' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)````
and also
````2022-12-18 17:12:56.316 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.adaptive_lighting_sleep_mode_daylight, switch.adaptive_lighting_sleep_mode_rgblight, switch.adaptive_lighting_sleep_mode_subdued_lighting or it is/they are currently not available````

This happened right after the update, although I only realized in the morning when the lights were still seemingly in sleep mode.

**Comment by basnijholt** [comment]
This means you need to update Home Assistant itself.

**Comment by basnijholt** [comment]
You need 2022.11 or later (https://github.com/basnijholt/adaptive-lighting/pull/375)

**Comment by LuccoJ** [comment]
Okay, thanks. I thought I was running on latest, tricked by lack of Docker knowledge. And dumbness, I guess.
