### ISSUE TITLE
Watchman shows missing entities 

### ISSUE THREAD

**Issue by PieBru** [basnijholt/adaptive-lighting#408]
This doesn't seem to create problems, but it would be cleaner not to have these warnings by Watchman:

```
+--------------------------------+---------+--------------------------------------------------------------+
| Entity ID                      | State   | Location                                                     |
+--------------------------------+---------+--------------------------------------------------------------+
| switch.adaptive_lighting_defau | missing | custom_components/adaptive_lighting/services.yaml:6,30       |
| lt                             |         |                                                              |
| light.bedroom_ceiling          | missing | custom_components/adaptive_lighting/services.yaml:9,36       |
+--------------------------------+---------+--------------------------------------------------------------+

-== Report created on 19 Dec 2022 16:58:58
```

Thank you for your integration.
Piero

**Comment by PieBru** [comment]
1. I found it very useful to reduce malfunctions after a lot of tinkering with entities: https://github.com/dummylabs/thewatchman
2. No, I don't have `light.bedroom_ceiling`, all my devices have a type/protocol/mac/location naming standard, i.e. `rgbww_z1234_countertop`.
3. The Watchman "lint" see as missing entities those examples:
* https://github.com/basnijholt/adaptive-lighting/blob/ce4503c9c6c8323802c7c6c350496e8fa883e042/custom_components/adaptive_lighting/services.yaml#L30
* https://github.com/basnijholt/adaptive-lighting/blob/ce4503c9c6c8323802c7c6c350496e8fa883e042/custom_components/adaptive_lighting/services.yaml#L36

4, Your code is correct, it's only a small aesthetics.

Thank you again for your AL.
Piero

**Comment by th3w1zard1** [comment]
What can be done here? There's going to be a myriad of similar issues once #443 is merged, how can we avoid this moving forward?
