### ISSUE TITLE
Feature request: Set working hours

### ISSUE THREAD

**Issue by abelmatser** [basnijholt/adaptive-lighting#41]
First of all, thanks for this great addition. Second, I'd like to make a feature request: setting working hours in which the color temperature can not fall below a threshold. 

My situation:
As the sun in the Netherlands sets quite early already, I'm still working at that time. As I associate colder light with working, I'd like the lights to be colder during working hours (but still varying). After working hours - let's say at 18:00 - I would like the same lights to turn warmer than during the day, but still be adaptive.

Solution:

1. The first solution I thought of was to have an option within the integration to define a "working hour" time range in which the brightness/temperature can not exceed a certain value. However, this has a limited scope to other problems, and would not work directly when having a second range of working hours later in the evening for example.

1. The solution I think is better: Being able to define the time range during which an adaptive lighting integration should be enabled. In this way, you define separate integrations for separate periods with different temperature/brightness values. These integrations then work on the same set of lights anyway.

Let me know what you think, and keep up the great work!

**Comment by basnijholt** [comment]
This can be accomplished by having two Adaptive Lighting instances with different sunset/sunrise times and toggling between them during working hours.
