### ISSUE TITLE
Update to 1.4.0 not blocked for HA versions prior to 2022.11 - AL integration can not be set up

### ISSUE THREAD

**Issue by bcutter** [basnijholt/adaptive-lighting#411]
#### Version information:
AL 1.4.1 on HA Core 2022.9.7

#### Description:
The integration should block updates for HA Core versions older than 2022.11.
Older ones are not aware of https://github.com/basnijholt/adaptive-lighting/pull/375 which results in not loading integration and this in the logs (I have 3 AL integrations):

```
Logger: homeassistant.config_entries
Source: config_entries.py:338
First occurred: 02:42:46 (3 occurrences)
Last logged: 02:42:46

Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'ATTR_COLOR_TEMP_KELVIN' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)
```

You should set minimum versions for releases in HACS to avoid this.

I meanwhile try downgrading to 1.3.0 until HA can be updated to resolve this version conflict.

**Comment by basnijholt** [comment]
Could you open a PR to pin HA? 😄

**Comment by yousaf465** [comment]
![image|366x289](upload://nOjIoHa4wzBWlOf7AU8LxCRCYGr.png)
 facing this error for past three months, can't find a solution.

**Comment by bcutter** [comment]
> ![image](https://user-images.githubusercontent.com/83491212/210049567-ea6a2ef8-b7f8-4dbd-8461-ddb6bd995e80.png)
> 
>  facing this error for past three months, can't find a solution. 

Check the logs and compare to the one I posted - is it the same issue?

**Comment by yousaf465** [comment]
> importing platform config_flow

it seems yes 
```

**Comment by yousaf465** [comment]
2022-12-30 17:12:24.197 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)
2022-12-30 17:12:24.362 INFO (MainThread) [homeassistant.setup] Setting up raspberry_pi

```

**Comment by basnijholt** [comment]
I have now pinned the version of HA and we test all the way back to the earliest supported version.
