### ISSUE TITLE
Brightness jumping from 5% (lowest) in morning to 60%

### ISSUE THREAD

**Issue by Shaun-Harrison** [basnijholt/adaptive-lighting#415]
#### Version information:
v1.4.1

#### Description:
For the past few days, between 7am and 9am the brightness is set at 5%, then it is jumping up to 60% for a long period of time before adjusting as expected after some time

I've got a sensor called `sensor.adaptive_lighting_brightness` which is taking the adaptive lighting brightness attribute via `value_template: '{{state_attr("switch.adaptive_lighting_home","brightness_pct") }}'`

![image](https://user-images.githubusercontent.com/46562010/210053416-ace707db-5526-484a-a077-452e66b3ce23.png)

**Comment by kreene1987** [comment]
Show your settings page for the AL integration.

**Comment by th3w1zard1** [comment]
Please set your logging to `debug` and post your config to continue this issue.

**Comment by basnijholt** [comment]
Because there are no settings nor logs there is not much we can do.

I will close this issue for now. When you provide more information we will reopen this issue (or you can open a new one).
