### ISSUE TITLE
Ignore lights being turned on with a specific color value and effects.

### ISSUE THREAD

**Issue by maxi1134** [basnijholt/adaptive-lighting#416]
Hi there!
I hope y'all are doing great!

I have this issue where  I sometimes turn on lights with specific colors and effects in some automation. (Mainly for accessibility as I don't hear too well ). 
Unfortunately, those get turned to white by this integration.

Would it be possible for the tool provided here to ignore lights being turned on with "effect" or "color_name" and its counterparts?

Thanks!

-Maxi1134

**Comment by callumgare** [comment]
I would also love this! Honestly it’s how I presumed it would work by default and I was very confused when I realised it didn’t seem to work this way. I understand there maybe technical reasons why this is tricky to implement but purely from a user experience perspective if I have a switch or automation or something that turns on a light and explicitly sets a colour when it does so then I would expect that request would be respected. 

Without this behaviour it breaks things like scenes. I have a scene to turn on a few accent lights and set them to some soft colours. However when I activate the scene the lights are very briefly turned on to the desired colours but then AL turns them to white. With home assistant scenes I can at least activate the scene a second time and have it work which is annoying but manageable. However I’ll often use the Home app on iOS to control my lights (via the HomeKit integration) and with the Home app scenes work as a toggle, once you turn on the scene tapping it again will turn off the scene and all the lights in the scene. That means you can’t simply activate the scene twice and have it set the colours correctly the second time.

@basnijholt I see you mentioned in a different issue that this is something you were considering looking into https://github.com/basnijholt/adaptive-lighting/issues/2#issuecomment-704535079 did you ever get a chance to do that?

Least this come across too negative, I should say I love AL and and very much appreciate all the hard work that’s gone into making it!

**Comment by th3w1zard1** [comment]
If either of you are using `take_over_control: true` and this is still happening, this needs to be set as kind/bug and we'd appreciate if you post your logs and configuration.

`take_over_control: true` is supposed to ignore any light.turn_on calls when not called with an empty payload (i.e brightness or color_temp is set in the light.turn_on call).

The whole point of this project is to adapt lights while ignoring any manual commands.

**Comment by th3w1zard1** [comment]
If you are using `take_over_control: true`, then as long as you turn the light on before executing the desired state, adaptive lighting will set the light as manually controlled and will stop adapting the light.
Example:

```
alias: Turn light on with custom settings
sequence:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bedroom_ceilingfan_lights
  - service: light.turn_on
    data:
      flash: short
      effect: strobe
      color_temp: 180
    target:
      entity_id: light.bedroom_ceilingfan_lights
mode: single
```

If you only call the 2nd light.turn_on, **and** the light is off, adaptive-lighting will adapt the light. Having the second call there tells adaptive-lighting that we've turned the light on, **and we set it's state.**

**Comment by th3w1zard1** [comment]
@maxi1134 would you mind elaborating on how last_state is saved in hass? Do you have any node-red automations you could post utilizing this?

I'm a bit new to home assistant's developer api but I know the config option `cache_state` exists in zigbee2mqtt, which when enabled will store all prior state changes made to an zigbee device, for use in hass. This behavior makes me think hass doesn't keep a record of state changes.

As far as I'm aware, hass only has a `last_state` and `new_state` during `state_changed` events which don't happen when a device is offline.

**Comment by maxi1134** [comment]
> @maxi1134 would you mind elaborating on how last_state is saved in hass? Do you have any node-red automations you could post utilizing this?
> 
> I'm a bit new to home assistant's developer api but I know the config option `cache_state` exists in zigbee2mqtt, which when enabled will store all prior state changes made to an zigbee device, for use in hass. This behavior makes me think hass doesn't keep a record of state changes.
> 
> As far as I'm aware, hass only has a `last_state` and `new_state` during `state_changed` events which don't happen when a device is offline.

Sorry for the tardiness, I was out of the country!

This is what I see in node-red:

![image](https://user-images.githubusercontent.com/1342643/231770800-614e1f0e-d992-46bf-843b-7f9fb7b05481.png)

**Comment by zimmra** [comment]
> I am implementing an option `adapt_only_on_bare_turn_on` which instantly triggers `manual_control` when turning on with brightness or color in PR https://github.com/basnijholt/adaptive-lighting/pull/709.
> 
> 
> 
> Enabling this will make sure AL doesn't take over when setting a scene.

This is a big deal IMO, and exactly what I've been hoping for.

My only notable gripe with A.L. has been not being able to utilize scenes/automations/scripts/etc 'as intended' and having to implement additional service calls to get the desired end result. 

This is expected for 1.19 release?

**Comment by basnijholt** [comment]
Yes, it is already in the 1.19.0b3 release 😃

**Comment by maxi1134** [comment]
This works for me on 1.19.0b4.

Thanks a lot! I've adapted my node-red flows already.
