### ISSUE TITLE
Applying RGB mode change with adaptive_lighting.apply service eventually just reverts back to previous RGB mode

### ISSUE THREAD

**Issue by etchings13** [basnijholt/adaptive-lighting#426]
#### Version information:
1.4.1

#### Description:
When I call the service "adaptive_lighting.apply" to change the RGB mode from "prefer_rgb_color: true" to "prefer_rgb_color: false" or vice versa, the change seems to apply. However, after a few minutes it just reverts right back to the previous setting. I have tried calling the service through Developer Tools as well as with automations with the same results.

Manually applying the change within the actual Adaptive Lighting settings (i.e. literally ticking or unticking the check box for RGB mode) _does_ make the change stick. It is only unsuccessful when using the service to apply the change.

**Comment by halfskye** [comment]
Experiencing the same issue. I think I'm going to try a workaround where I have two versions of the same AL service - one with color_temp and the other using prefer_rgb_color and then just conditionally toggle them on/off and off/on in the places where I previously was trying to apply prefer_rgb_color.

**Comment by etchings13** [comment]
> Experiencing the same issue. I think I'm going to try a workaround where I have two versions of the same AL service - one with color_temp and the other using prefer_rgb_color and then just conditionally toggle them on/off and off/on in the places where I previously was trying to apply prefer_rgb_color.

That's an excellent idea, I hadn't thought of that as a workaround. I'm going to try that as well.

**Comment by th3w1zard1** [comment]
This is actually not a bug, it's just part of how the integration works. `adaptive_lighting.apply()` just applies settings for that call only: it'll get reset on the next `interval` when adaptive-lighting applies what's in the config. There's currently no way to change the config values with a service call.

**Comment by th3w1zard1** [comment]
> There's currently no way to change the config values with a service call.
There is now, just grab https://github.com/th3w1zard1/adaptive-lighting/tree/change-config-via-service-call and call the new service call `change_switch_settings` to change anything on the fly.

**Comment by th3w1zard1** [comment]
`change_switch_settings` now included in PR #443
