### ISSUE TITLE
[Feature Request] Update lights when they become available again

### ISSUE THREAD

**Issue by pierosavi** [basnijholt/adaptive-lighting#43]
Hi, thanks for the awesome component!
I noticed that when my lights become unavailable and available again after I manually updated the status, it doesn't get updated.
I would like it to act like when it's turned off and on again, so the previous status is discarded and they return to be managed by Adaptive Lightning.
What do you think?
Thanks

**Comment by basnijholt** [comment]
Hi there, is this a similar request to https://github.com/basnijholt/adaptive-lighting/issues/33?

**Comment by pierosavi** [comment]
That fixes it, thanks!
