### ISSUE TITLE
Lights stuck on initial transition

### ISSUE THREAD

**Issue by ssillen** [basnijholt/adaptive-lighting#433]
When lights turn on, they start as very dimmed and it takes 1 up to a few seconds before adjusting to the correct brightness.
Sometimes they even stay very dimmed and never get adjusted.
I'm using this on hallway lighting, activated by a motion sensor, so currently it's very impractical if the lights stay dim.
What's the cause of this issue? Can the initial brightness at least be set to the minimal brightness setting so you can see?

**Comment by ssillen** [comment]
I think I found the solution.
When turning off the lights, I used the attribute "transition" so they would transition slowly to brightness 0. When turning back on the lights, they would start in their last state, being dimmed. I had initial_transition set to 0 (because i want the lights to come on asap), but Hue uses standard transition of 1s when sending turn_on. The AL kicks in after the light is turned on, but then the Hue bulb is still transitioning (to the dimmed state) and sometimes ignores the info sent by AL.
I solved it by either setting the "transition" for the turn_on service to 0 or (what I'm currently using) turning on the lights using the adaptive_lighting.apply service.

**Comment by mindtripper** [comment]
Take a look at Light Profiles. Starting dimmed with IKEA trådfri works quite well for me.

https://www.home-assistant.io/integrations/light/

This in combination with Adaptive Lightings "adapt_delay" of a couple hundred milliseconds could help.

**Comment by th3w1zard1** [comment]
Please update this issue with debug logs and your config if you are still having trouble

**Comment by th3w1zard1** [comment]
stale
