### ISSUE TITLE
Nothing logged anywhere

### ISSUE THREAD

**Issue by traysh** [basnijholt/adaptive-lighting#442]
I have enabled adaptive-lighting for some lights in home assistant, and it seems to be working, as their color temperature is different. But I can't see any messages in the logbook or anywhere. I even enabled "debug logging" for it, but still didn't see any messages in the logs.

How can I know what adaptive-lighting is doing?

**Comment by th3w1zard1** [comment]
Are you looking in home assistant's 'Core' logs? Can you give any more information?

If you're looking in the logbook you need to look for the adaptive lighting switch like so:
![image](https://user-images.githubusercontent.com/2219836/224545602-06477925-d237-4ed1-b40e-c0e90f9f7a0a.png)
