### ISSUE TITLE
[Feature Request] A way to "separate" color from brightness in offsets

### ISSUE THREAD

**Issue by mg0716** [basnijholt/adaptive-lighting#45]
I'm not entirely sure the title is the best way to put it, but here's my use case:

In the mornings prior to sunrise I prefer to have lighting that is a cooler temperature to simulate daylight. This means that I use a `sunrise_offset` of -03:00:00 or so to ensure that I have the correct color temperature at around 5am.

However, a casualty of this is brightness. Ideally I'd like to have brightness tracking to the sun position without offset.

I'm not entirely sure of the best way to recommend how to go about this—but want to share my use case that I'm sure I'm not alone on!

**Comment by basnijholt** [comment]
You can implement this by creating two Adaptive Lighting instances where one has only `adapt_brightness` enabled and the other one `adapt_color` enabled. Then use different sunset (rise) (offset) times.

**Comment by basnijholt** [comment]
Please reopen if my suggestion didn't work.
