### ISSUE TITLE
Is V2 by RubenKelevra still a planned release?

### ISSUE THREAD

**Issue by th3w1zard1** [basnijholt/adaptive-lighting#454]
@basnijholt I've a question for you.
I've been submitting a lot of PRs recently. Reading around the github, I see there's a project by @RubenKelevra for adaptive-lighting V2, but I can't find any fork for it or any comments made by him about V2 in the past year or so. I don't think he's disappeared either as he still has recent github activity in the last week.

Is @RubenKelevra still working on V2? I'd rather not code anything further if what I'm doing has already been implemented by another dev.

How can I further help the project going forward? Thank you!

**Comment by basnijholt** [comment]
I am quite certain that there was only a plan and no code was ever written (at least not publically). 

I have just invited you as a collaborator on this project. Feel free to add labels to issues, close issues, etc. as you see fit :-)

Which PR do you think is most ready for review (if not all)?

**Comment by th3w1zard1** [comment]
Hi, thank you for the invite!

What exactly do you mean by review?

I believe the only PR that still needs a bit more testing is the one involving manual control. I simply don't have the light groups/hardware necessary to test all potential breaking points of that PR.

The other PRs are simple enough to be ready for the next phase.
