### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable ('trigger.entity_id' is not a field in automation)

### ISSUE THREAD

**Issue by furgoose** [basnijholt/adaptive-lighting#46]
I've added an automation based on your example ["reset manual_control after 1 hour"](https://github.com/basnijholt/home-assistant-config/blob/df277ce733d876b071d976ec630817de7111c4c8/automations/adaptive_lighting.yaml#L68), but it fails due to trigger.entity_id not being defined - has this been updated/changed because I cannot find any reference to the adaptive_lighting switch in the event

Thanks a lot

**Comment by basnijholt** [comment]
The entity_id should be included: https://github.com/basnijholt/adaptive-lighting/blob/17ac3951240a65e75e79a548b85d50d7319d9f9b/custom_components/adaptive_lighting/switch.py#L260

Perhaps you changed the trigger type?

**Comment by basnijholt** [comment]
Actually, you are right:
![image](https://user-images.githubusercontent.com/6897215/99966821-2e001100-2d97-11eb-9d3d-1352637934d8.png)

This is a bug! I will fix it.

**Comment by mg0716** [comment]
Thanks for directing me here @basnijholt. Good to know it's a bug and you've identified it. Looking forward to getting this working!

**Comment by basnijholt** [comment]
This should be fixed now:
![image](https://user-images.githubusercontent.com/6897215/102689164-4d565680-41fc-11eb-9235-bf5bd42e9cb6.png)

You should make the change like https://github.com/home-assistant/home-assistant.io/pull/14877/files#r546235892
