### ISSUE TITLE
Watchman alert: switch.adaptive_lighting_default [missing]

### ISSUE THREAD

**Issue by Coder84619** [basnijholt/adaptive-lighting#461]
#### Version information:

1.4.1

#### Description:

Watchman reports this missing entity:

switch.adaptive_lighting_default [missing]
services.yaml

Not sure how to resolve this?

**Comment by th3w1zard1** [comment]
Duplicate of #408 

There's no actual issue, watchman is just detecting that the example values adaptive-lighting has in `services.yaml` don't exist.
Is watchman spamming your logs with these errors or is it easily ignorable? I could include a 'fix' for this in #460
