### ISSUE TITLE
Yeelight Xiaomi desk lamp potential incompatibility

### ISSUE THREAD

**Issue by agneevX** [basnijholt/adaptive-lighting#48]
I'm getting this error when adaptive_lighting is attempting to set the color temp

`
Error when calling <function YeelightGenericLight.set_colortemp at 0x8dfe8858>: {'code': -5001, 'message': 'invalid params'}
`

If I manually set the color temp, I'm able that the transitions work over time.

N.B. This is also an issue with Circadian Lighting ([#44](https://github.com/claytonjn/hass-circadian_lighting/issues/44)).

**Comment by basnijholt** [comment]
I think this is a bug in the yeelight integration.

**Comment by basnijholt** [comment]
And the answer is in the issue you linked: https://github.com/claytonjn/hass-circadian_lighting/issues/44#issuecomment-540162964 (nr. 2).

**Comment by agneevX** [comment]
> I think this is a bug in the yeelight integration.

If it was the integration, it would affect every single bulb.

How do you propose I get this value? The `color_temp` value ranges from `200` to `370`.
