### ISSUE TITLE
Offset brightness

### ISSUE THREAD

**Issue by bisquit2003** [basnijholt/adaptive-lighting#489]
Maybe I'm not using integration quite correctly, but I'll try to explain how it works for me: I have only 5-6 devices with brightness and/or color adjustment, I added them all to one integration. And I like the default settings, there is only one nuance. In the chandelier, my diode tape burned out (brightness and color temperature are regulated), I replaced it with another one, accidentally buying less power. And now its brightness is not quite enough for me (I use it only in the evening). It would be great if I could set the brightness offset for this device, for example +10%, in the settings. It seems to me that sunset offset will not work very correctly here, because it will also affect the temperature. Now I'm in daytime mode, I just turn up the brightness from the remote when I need it, but this does not meet the functions of a smart home :)

**Comment by th3w1zard1** [comment]
@bisquit2003 Hey all you need to do is create another configuration for your lower powered bulb, where the max_brightness is 100%. The others you can put on 90% brightness.

You need two configurations so you can store max_brightness values in two switches.

**Comment by th3w1zard1** [comment]
Basically just to to your integrations and add another adaptive-lighting instance.

**Comment by bisquit2003** [comment]
> Basically just to to your integrations and add another adaptive-lighting instance.

Thank you for your advice. But then everything will be lower in brightness at a specific time (for example, when it is already dark, but sleep mode is not turned on yet). I would like everything to remain as it was (for example, at 21.00 the brightness was about 50%, and specifically this chandelier was 60%). Although the best solution would be to install the LED strip of the correct brightness, as it was before)

**Comment by th3w1zard1** [comment]
But it sounds like you're saying the brightness of your lower powered bulb is no longer synced up to the rest of your bulbs? The default max brightness is 100% and it only will adapt to that at midday (noon), there's no way to go to 110% brightness from what you described in OP.

**Comment by th3w1zard1** [comment]
Sorry if I'm missing something obvious.

**Comment by th3w1zard1** [comment]
Are you just wanting the brightness higher for that specific bulb in the evenings?

**Comment by bisquit2003** [comment]
> But it sounds like you're saying the brightness of your lower powered bulb is no longer synced up to the rest of your bulbs? The default max brightness is 100% and it only will adapt to that at midday (noon), there's no way to go to e.g. 110% brightness from what you described in OP.

Of course, I understand that it is impossible to make 110% brightness, but since in the dark before turning on sleep mode, the brightness that the integration sets is much lower than 100%, a small offset to this set value would be my salvation. That is, the integration sets the brightness X, and for one lamp X + offset (or maybe someone needs a negative offset if 2 lamps of different capacities are used nearby), but no more than 100%

**Comment by bisquit2003** [comment]
> Are you just wanting the brightness higher for that specific bulb in the evenings?
> 
> You could setup that bulb in two different integrations, one with only the brightness switch on and one with only the color temp switch on. For the brightness integration, disable the color temp switch and set the sunrise/sunset offset. For the color temp integration, set it to default. You can keep the 2nd integration disabled during the day, and then enable it with an automation in the evening.

Well, it's more like Workaround

**Comment by th3w1zard1** [comment]
> > Are you just wanting the brightness higher for that specific bulb in the evenings?
> > You could setup that bulb in two different integrations, one with only the brightness switch on and one with only the color temp switch on. For the brightness integration, disable the color temp switch and set the sunrise/sunset offset. For the color temp integration, set it to default. You can keep the 2nd integration disabled during the day, and then enable it with an automation in the evening.
> 
> Well, it's more like Workaround

From what I understand anything we put in adaptive-lighting itself would also be a workaround for this issue. Many people keep lights in multiple integrations for this exact reason, it's a lot easier to customize this yourself when using automations.

**Comment by bisquit2003** [comment]
> 
> From what I understand anything we put in adaptive-lighting itself would also be a workaround for this issue. Many people keep lights in multiple integrations for this exact reason, it's a lot easier to customize this yourself when using automation.
> 
> Maybe someone else will have a better idea.

I completely agree that I need to take this lamp to the second instance of integration, but reducing the brightness of other lamps in the first instance will not solve my problem, because the lamp I need will still shine dimly at night. And if my offer seems wrong to you, then the only solution for me is sunset offset

**Comment by th3w1zard1** [comment]
> > From what I understand anything we put in adaptive-lighting itself would also be a workaround for this issue. Many people keep lights in multiple integrations for this exact reason, it's a lot easier to customize this yourself when using automation.
> > Maybe someone else will have a better idea.
> 
> I completely agree that I need to take this lamp to the second instance of integration, but reducing the brightness of other lamps in the first instance will not solve my problem, because the lamp I need will still shine dimly at night. And if my offer seems wrong to you, then the only solution for me is sunset offset

Yeah I suggested two ideas and you're completely right about the first.
With the second, you'll be able to utilize `sunset_offset` in the 2nd switch to only modify brightness, while the switch is on.

So basically you'd have two switches for the same light `light.lower_power_led` in the switches:
switch.adaptive_lighting_lower_power_led
switch.adaptive_lighting_lower_power_led_night

switch.adaptive_lighting_lower_power_led_night has a sunset_offset of 3 hours, and the color_temp switch is _**always**_ off.
During the day, switch.adaptive_lighting_lower_power_led_night is off,
Setup an automation that runs at night to turn switch.adaptive_lighting_lower_power_led_night on and switch.adaptive_lighting_lower_power_led off.

Since the color_temp switch is off, it'll only use the sunset_offset in switch.adaptive_lighting_lower_power_led_night to update the brightness.

Hope that makes sense.

**Comment by th3w1zard1** [comment]
@bisquit2003 Were you able to figure this out? I could write more descriptive steps if you'd like.

**Comment by bisquit2003** [comment]
> @bisquit2003 Were you able to figure this out? I could write more descriptive steps if you'd like.

Yes, I did this: I created a separate installation for this lamp and set the minimum brightness in the settings to at least 40%. It turned out what I wanted, without sunset offset

**Comment by bisquit2003** [comment]
I think that the issue can be closed
