### ISSUE TITLE
Organize Labeled Issues Automatically - Github Workflow Action

### ISSUE THREAD

**Issue by th3w1zard1** [basnijholt/adaptive-lighting#499]
earlier today I ran across https://github.com/marketplace/actions/move-labeled-or-milestoned-issue-to-a-specific-project-column to automatically organize new and outstanding issues in our [_Classic Projects_](https://github.com/basnijholt/adaptive-lighting/projects/4)

unfortunately I don't have the perms to set this up myself as it needs an [action token](https://github.com/marketplace/actions/move-labeled-or-milestoned-issue-to-a-specific-project-column#creating-an-action-token)

@basnijholt if you're interested please take a look!

**Comment by th3w1zard1** [comment]
@basnijholt currently you can filter through all of the stale/soon-to-be-stale issues by just appending `-label:need/author-input` to the search. that'll give you a good idea of what bugs are still present in the latest release. 😃

**Comment by basnijholt** [comment]
Wow! You really sorted out those issues!

I can add that action later today 😄

**Comment by th3w1zard1** [comment]
To be fair most were stale or fixed by our last releases. (over 60%)

**Comment by basnijholt** [comment]
I think there are sufficiently few open issues now that this might not be necessary at the moment. 

Also the [GH Action hasn't been maintained for almost 3 years and is not really popular](https://github.com/konradpabjan/move-labeled-or-milestoned-issue).

I'll close this for now and we can reconsider later.
