### ISSUE TITLE
Time remaining as attribute for autoreset_control_seconds 

### ISSUE THREAD

**Issue by mindtripper** [basnijholt/adaptive-lighting#525]
It would be nice to visualize for the end-user the remaining time of autoreset_control_seconds.
By adding seconds remaining of "autoreset_control_seconds" as attribute on switch.adaptive_lighting_*
Does not need to update super frequently but should be updated instantly when set and when it has ended.

Thanks!

**Comment by th3w1zard1** [comment]
I've no idea why we didn't think to do this during development. Great suggestion!

It wouldn't be 100% accurate as attributes are only updated every 90 seconds or whatever your `interval` is

**Comment by th3w1zard1** [comment]
You could implement this yourself by listening for adaptive lighting's manual control events that are fired to home assistant event's bus and keeping track of the time yourself for now.

**Comment by basnijholt** [comment]
I have added this in 558 :)
