### ISSUE TITLE
Improve manual control 

### ISSUE THREAD

**Issue by broyuken** [basnijholt/adaptive-lighting#54]
Is there a way we could change AL so that when a light is turned on and the state is updated in HA it checks to see if it has been manually controlled? For example my wife will turn on a light and instantly set it to a brightness she wants. The next time AL checks it will auto adjust that light because it’s not at a level it thinks it should be at. Then if she adjusts it again it finally turns on manual control. This really hurts the WAF (wife acceptance factor). I tried setting the update interval to 1 second but that didn’t help either. Right now it is the default which I believe is 45 seconds?

**Comment by basnijholt** [comment]
Unfortunately, I think this is unavoidable. How would you for example indicate to enable Adaptive Lighting upon turning on the light?

**Comment by broyuken** [comment]
When the state of the light goes from off to on in HA?

**Comment by basnijholt** [comment]
Ah, I think I misunderstood what the problem was. I will give it some more thought while looking at the code.

**Comment by broyuken** [comment]
Yea I think just having a poll happen instantly when the light was turned on would solve the problem.

**Comment by basnijholt** [comment]
Does this sequence happen in Home Assistant:
1. `light.turn_on(entity_id=some_light)`
2. `light.turn_on(entity_id=some_light, brightness=some_value_your_wife_wants)`

If so, I don't understand why that doesn't already work... 

Or are you using something external from Home Assistant?

**Comment by broyuken** [comment]
No the sequence of events that is causing the issue is...

1. light turned on at switch
2. HA state updates from off to on
3. Wife changes level of light from wall switch
4. On next update AL updates light to the level it thinks it should be at
5. Angry wife
6. Wife changes light level again from wall
7. AL sees light is manually adjusted
8. Light stays at correct level now

**Comment by basnijholt** [comment]
> 3. Wife changes level of light from wall switch

Does this communicate via Home Assistant or some external app/device?

**Comment by broyuken** [comment]
It’s a zwave wall switch using the open zwave beta integration.

**Comment by jamescadd** [comment]
Is it possible to have AL only adapt the light temperature, not the brightness?  I have a similar issue where I'd like to have the temperature vary throughout the day, but it should never override the brightness of the light.  My use case is Lutron Aurora dimmers controlling the brightness through the Hue hub.  Regardless of control I prefer not to have AL adjust the brightness of the lights.

**Comment by broyuken** [comment]
Yes there’s a switch with each instance that you can turn off. It should be something like switch.adaptive_lighting_adapt_brightness_living_room

**Comment by broyuken** [comment]
> It’s a zwave wall switch using the open zwave beta integration.

Little more info to clear this up, it’s a zwave dimmer switch, and she is manually adjusting the brightness using the switch itself. No smart bulbs involved here, just the switch. The switch uses the open zwave beta integration to HA.

**Comment by RicardoCst** [comment]
Yes its very annoying.

> 
> 
> No the sequence of events that is causing the issue is...
> 
>     1. light turned on at switch
> 
>     2. HA state updates from off to on
> 
>     3. Wife changes level of light from wall switch
> 
>     4. On next update AL updates light to the level it thinks it should be at
> 
>     5. Angry wife
> 
>     6. Wife changes light level again from wall
> 
>     7. AL sees light is manually adjusted
> 
>     8. Light stays at correct level now

**Comment by jd1900** [comment]
I think this is very related to the this issue:
https://github.com/basnijholt/adaptive-lighting/issues/96

IMHO, disabling brightness control and updating temperature not "turning on" the device (just changing temperature) could fix it.

**Comment by RubenKelevra** [comment]
@basnijholt no sure, but wasn't this fixed in the meantime with the "take_over_control" setting?

**Comment by RubenKelevra** [comment]
This ticket is stale but still feels important.

I think it will be fixed by having just different types over manual overrides in v2.

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.

**Comment by th3w1zard1** [comment]
This is exactly the issue I was having which is why I created #450. When it's merged it should close this issue.

**Comment by th3w1zard1** [comment]
@broyuken This should be fixed in [1.10.0](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.10.0)
