### ISSUE TITLE
Color/temp based on time and GPS coords

### ISSUE THREAD

**Issue by nnordrum** [basnijholt/adaptive-lighting#555]
I got a demo of the color adjusting of the Lutron Ketra lights, and one of the features they had was adjusting the color/temp based on (I believe) GPS and time so your lights matched what the color temp was outside. I know there's an Issue for adjusting the color/temp based on a sensor, but this would be cool as well.

I'm not sure what it does when it's dark out because my demo was at like 3pm, but guessing it's just a (quadratic?) curve to a value :time?

**Comment by nnordrum** [comment]
the use case is that it adjusts it automatically based on GPS as opposed to fiddling with 10 parameters to get it "right". My wife constantly thinks I have the parameters wrong. 

I assume it's just math to figure out what the values are; no external API needed.

**Comment by nnordrum** [comment]
I'm not opposed to the control, I just don't seem to know how to set the settings in a way that doesn't cause a lot of objecting. If you think what is there is "good enough", then I'd propose documentation that suggests how to get a setting that aren't so severe as the default settings.

**Comment by th3w1zard1** [comment]
I hear you but what I don't understand is how you're noticing the small discrepancies between your time zone, and the actual GPS position?

Let's say adaptive lighting is set up an hour off from my time zone. The brightness/color temp would only be a few percents difference. I wouldn't even notice _that_, despite a whole time zone difference being significantly larger than the GPS difference.

**Comment by nnordrum** [comment]
I was just trying to do something easy from the end user's perspective. if there already is a time zone setting, I probably didn't see it. I'll look now.

**Comment by th3w1zard1** [comment]
Look at the sunrise_time and sunset_time options. You can set them to the exact minute for your purpose during the creation, and `change_switch_settings` if you want to change them later
