### ISSUE TITLE
Lights Quit Adapting with 1.10.1

### ISSUE THREAD

**Issue by johnlento** [basnijholt/adaptive-lighting#556]
#### Version information:
I was on 1.4.1 and upgraded to 1.10.1. 

#### Description:
After the upgrade the lights don't seem to adapt. It is almost like only_once is set. The lights are now laggy and don't adapt but when I manage to get them off and turn back on they will adapt. They just won't adapt every 90 seconds with a 1 second transition.

I am seeing many ULI errors like this: ValueError: ULID must be 26 characters. That is about it.

**Comment by johnlento** [comment]
This was my fault. I thought I installed 1.10.1 but was on 1.10.

**Comment by th3w1zard1** [comment]
@johnlento Hey no worries, I'm just glad the 1.10.0 issue is finally gone. Please let us know if you find any other bugs.
