### ISSUE TITLE
IKEA Tradfri CCT bulbs issues

### ISSUE THREAD

**Issue by dedepene** [basnijholt/adaptive-lighting#56]
Apparently the IKEA Tradfri implementation [does not allow](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/445#issuecomment-373649142) for simultaneous receipt of brightness AND color temp adjustments. As a result it's a random affair - either bri or color temp will be randomly adjusted, never both on a turn_on event 👍 

I wonder if there's anything that you can do on your end to break up the call and delay on of these?

**Comment by basnijholt** [comment]
Yes, you can use the `separate_turn_on_commands ` option, please read and report in https://github.com/basnijholt/adaptive-lighting/issues/49.
