### ISSUE TITLE
Lifx lights not automatically adapting 

### ISSUE THREAD

**Issue by sambarlick** [basnijholt/adaptive-lighting#576]
I'm having an issue where my lifx lights are not automatically adapting I have to manually trigger the adaptive lighting apply service call.

I have tried different configurations of the options, only_once and seperate_turn_on_commands but nothing seems to work.

Is there something else I can try?

**Comment by th3w1zard1** [comment]
Please follow the issue template. What adaptive lighting version are you using, ha version , and have you already enabled debug logging?

**Comment by sambarlick** [comment]
Hi, sorry about not using the template.

I'm using Adaptive lighting version 1.11.0.
Home Assistant version 2023.4.4.

Would you like my logs?

**Comment by basnijholt** [comment]
As @th3w1zard1 correctly stated, please use the template.

I will close this one. Feel free to open a new issue with the complete information 😄
