### ISSUE TITLE
Meross HomeKit lights failing to continuously adapt

### ISSUE THREAD

**Issue by aatifk** [basnijholt/adaptive-lighting#579]
I'm having a weird issue for the last few weeks. I have a bunch of Meross BR30 HomeKit bulbs that are integrated into Home Assistant using the HomeKit Controller integration. I have been using these with Adaptive Lighting for a while until they stopped continuously adapting when on a few weeks ago. What I mean is that the lights adapt when turned off and turned on, but in the on state, they stay with the brightness and color temperature that they started with. Any thoughts on what could be causing this and how to fix it? This is only happening with these lights; others (I have a bunch of Kasa lights as well) are continuing to work fine. I've already removed the integration for these specific lights and added it back but that hasn't really solved the issue. 

Running Home Assistant 2023.4.6 and Adaptive Lighting 1.11.0 (the latest versions). 

Thanks!

**Comment by th3w1zard1** [comment]
Please follow the new issue template instructions, or close this issue. You need to post logs or any information that would help identify your issue. The 'new issue' template auto-fills all the information you need to describe in order to get accurate support.

**Comment by basnijholt** [comment]
Yeah, as @th3w1zard1 correctly stated, please use the template.

I will close this one. Feel free to open a new issue with the complete information.
