### ISSUE TITLE
Visual indication for sunset/sunrise

### ISSUE THREAD

**Issue by GoBooth** [basnijholt/adaptive-lighting#58]
Hi, I love adaptive-lighting, it's by far my favourite hac in Home Assistant, so thank you very much for creating and sharing this.

When I implemented this add-on a few months ago (when it was first released), my lighting was perfect in my house, but now that winter is here, it's too dim too fast.

You already have the solution for this, you allow me to manually set the sunset time.

My Problem is, manually setting the sunset time doesn't really give me much insight into what brightness level my lights are going to be and at what time.

it would be really great if there could be some sort of visual (like a graph) where I could see what % the light will be and at what time in reference to the "sunset time".

Thanks again.

**Comment by denilsonsa** [comment]
I was about to suggest the same feature. I wish I had a way to preview the light state for any given time of the day. It could be a graph from 00:00 to 23:59 that shows the brightness and the color temperature. This way, I would be able to tweak the parameters until I get the desired outcome. Bonus points if clicking on the graph applies those values to the lights.

**Comment by mr-ransel** [comment]
Another solution to this core problem that might be faster/easier to implement would be to, at a minimum, be able to display a list in text of "key times" in the next day. For example:

```
Given your settings, you will see this behavior:
- The lights will begin to dim at "X" today.
- The lights will reach minimum brightness at "Y" today.
- The lights will reach maximum brightness at "Z" tomorrow.
- At "some user-defined time" the lights will be at "B" brightness and "C" color temperature.
```

**Comment by basnijholt** [comment]
Hi @denilsonsa @mr-ransel @GoBooth, I have created https://basnijholt.github.io/adaptive-lighting/ which shows precisely how the brightness and colors change over time based on the settings.

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f


I think this is sufficient 😄 

Let me know what you think!

**Comment by mr-ransel** [comment]
It's amazing and I _LOVE IT_
