### ISSUE TITLE
Feature Request - Dim to Warm

### ISSUE THREAD

**Issue by sabaatworld** [basnijholt/adaptive-lighting#580]
Thanks for the great work and support for this integration. I'm looking for a feature that would allow the lights to change color temperature based on how bright they currently are.

For example, they could be cool white when at full brightness, but gradually change to a warm limit when brightness is decreased.

Further, this feature could be combined with existing configuration in some manner so that time or brightness could be given priority as the user needs.

Let me know your thoughts on this. Thanks!

**Comment by th3w1zard1** [comment]
There is already an ongoing thread for dim to warm https://github.com/basnijholt/adaptive-lighting/issues/78, please don't create duplicate threads thanks
