### ISSUE TITLE
Feature request: Adaptive Lighting should be inactive when the light is activated via brightness

### ISSUE THREAD

**Issue by j3mu5** [basnijholt/adaptive-lighting#581]
Hello dear community,

I am observing an undesirable behaviour. If I set a switched-off light in Homeassistant directly to a certain brightness in the context menu of the frontend, this is overwritten by Adaptive Lighting.

I would therefore like to see the following behaviour, if possible:
- Adaptive Lighting should become active when the light is switched on.
- Adaptive Lighting should not be activated when a certain brightness is set, which switches the light on.

**Comment by th3w1zard1** [comment]
See the V2 Roadmap for the main thread. This has been requested many many times already. 
The short is there isn't a good way to do this as the whole integration relies on the second `light.turn_on` being the main trigger for manual detection. Also some lights pass brightness/color data to the ha event bus and I haven't figured out a way to distinguish these either. You can see #528 for a rough implementation of the feature, feel free to test it out and see if it works the way you'd like.

**Comment by efenner** [comment]
I have this same issue. 

@th3w1zard1, you mention that this should work with scenes. Do you have any advice on that? When I apply a scene, even if I turn off the main adapt brightness toggle in the scene, the lights that are turned on by the scene that were previously off get adapted, breaking the scene.

**Comment by basnijholt** [comment]
I am implementing an option `adapt_only_on_bare_turn_on` which instantly triggers `manual_control` when turning on with brightness or color in PR https://github.com/basnijholt/adaptive-lighting/pull/709.

Enabling this will make sure AL doesn't take over when setting a scene.

**Comment by basnijholt** [comment]
This is now in the latest beta release. Looking forward to your feedback.

**Comment by j3mu5** [comment]
> This is now in the latest beta release. Looking forward to your feedback.

I just tested it - it works very well for me and exactly as desired: when setting the brightness or colour temperature directly, AL takes no action.
When switching on, AL sets brightness and colour temperature as desired.
Many thanks!

**Comment by basnijholt** [comment]
Thanks a lot for getting back to me! Glad you like it 😄
