### ISSUE TITLE
`min_sunset_time` seems to be confusing the brightness?

### ISSUE THREAD

**Issue by robcresswell** [basnijholt/adaptive-lighting#582]
Hello,

I'm on 1.11.0. This evening I've started seeing some really odd behaviour; at around 20:00 local time the lights all went fully dark as if it was hours past sunset. I had `min_sunset_time` set to `18:30:00` and its been fine up til now, but now its behaving really strange.

If I change `min_sunset_time` back to `None`, then the lights go back to normal, adjusting to actual sunset time. Equally if I set `min_sunset_time` to later than the current time, they go to full brightness, as expected. But any `min_sunset_time` earlier than the current time immediately makes the room act as if sunset was hours ago.

**Comment by th3w1zard1** [comment]
Please follow the new issue template as it has complete instructions on how to create a new issue, or close this. You need to post logs or any information that would help identify your issue.
