### ISSUE TITLE
Transitions ignored when lights turn on

### ISSUE THREAD

**Issue by protyposis** [basnijholt/adaptive-lighting#586]
My setup is Adaptive Lighting with Zigbee2MQTT (most recent versions) and various models of Ikea Tradfri lamps controlled by HA automations. Some lamps seem to have default turn-on transitions set (not sure where they come from), some have defaults set in Z2M, some automations explicitly set transition times in `light.turn_on`, and AL has the `initial_transition` set to its default of 1 second.

All of these transitions are ignored while AL is activated and lights turn on instantly to their target brightness. When I disable AL, all transitions are correctly applied.

Here's an example log from Z2M of a `light.turn_on` call:
```
Debug 2023-05-08 21:41:12Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5}'
Debug 2023-05-08 21:41:12Publishing 'set' 'state' to 'Bulb01'
Info 2023-05-08 21:41:12MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":136,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:41:13.278Z","level_config":{"on_level":"previous"},"linkquality":40,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Debug 2023-05-08 21:41:12Publishing 'set' 'transition' to 'Bulb01'
Info 2023-05-08 21:41:12MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":136,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:41:13.278Z","level_config":{"on_level":"previous"},"linkquality":40,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Debug 2023-05-08 21:41:12Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":1.0,"brightness":129,"color_temp":454}'
Debug 2023-05-08 21:41:12Publishing 'set' 'brightness' to 'Bulb01'
Info 2023-05-08 21:41:12MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":136,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:41:13.409Z","level_config":{"on_level":"previous"},"linkquality":40,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Debug 2023-05-08 21:41:12Publishing 'set' 'transition' to 'Bulb01'
Debug 2023-05-08 21:41:12Publishing 'set' 'color_temp' to 'Bulb01'
Info 2023-05-08 21:41:12MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":136,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:41:13.464Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Info 2023-05-08 21:41:12MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":129,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:41:13.464Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
```
The first line contains the transition set by the service call (`"transition":0.5`), and just moments after, AL sends another call with the `initial_transition` (`"transition":1.0`).

Only when I turn on the lights in quick succession, the transition is correctly applied. Logs of two consecutive turn-on sequences:

```
Debug 2023-05-08 21:49:51Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5}'
Debug 2023-05-08 21:49:51Publishing 'set' 'state' to 'Bulb01'
Info 2023-05-08 21:49:51MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":120,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:49:52.960Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Debug 2023-05-08 21:49:51Publishing 'set' 'transition' to 'Bulb01'
Info 2023-05-08 21:49:51MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":120,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:49:52.960Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
// OFF command removed
Debug 2023-05-08 21:49:55Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5}'
Debug 2023-05-08 21:49:55Publishing 'set' 'state' to 'Bulb01'
Info 2023-05-08 21:49:55MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":120,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:49:56.248Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
Debug 2023-05-08 21:49:55Publishing 'set' 'transition' to 'Bulb01'
Info 2023-05-08 21:49:55MQTT publish: topic 'zigbee2mqtt/Bulb01', payload '{"brightness":120,"color_mode":"color_temp","color_temp":454,"color_temp_startup":65535,"last_seen":"2023-05-08T19:49:56.248Z","level_config":{"on_level":"previous"},"linkquality":43,"power_on_behavior":"previous","state":"ON","update":{"installed_version":65554,"latest_version":65554,"state":"idle"},"update_available":false}'
```
Now there's only one `ON` command with `"transition":0.5`. If I wait a few seconds before turning it on again, there's again a second `ON` command with `"transition":1.0` from AL, and the transition is ignored.

Any ideas how to fix this? It seems to me that Z2M or the Tradfri lights cannot correctly handle overlapping transition commands, and a potential solution could be delaying the first AL adjustment command after turn-on by the initial transition time.

Btw, thanks for developing AL! I started using it a week ago and instantly loved it! It let me simplify light automations and provides a nicer experience :)

**Comment by protyposis** [comment]
Here's a script to reproduce the issue (run with AL disabled!):

```yaml
alias: transitiontest
sequence:
  - service: light.turn_off
    entity_id: light.badezimmer_decke
  - delay: 2
  # A normal turn-on command, transition works as expected
  - service: light.turn_on
    entity_id: light.badezimmer_decke
    data:
      transition: 1
  - delay: 2
  - service: light.turn_off
    entity_id: light.badezimmer_decke
  - delay: 2
  # Emulation of AL-enhanced turn-on sequence
  # - first, the normal command (e.g. from an automation)
  # - second, the command added by AL
  # Transition ignored, light turns on at full brightness
  - service: light.turn_on
    entity_id: light.badezimmer_decke
    data:
      transition: 1
  - service: light.turn_on
    entity_id: light.badezimmer_decke
    data:
      transition: 1
      brightness: 254
      color_temp: 180
mode: single
```
The transition is only ignored if both `brightness` and `color_temp` data are present. Removing one or the other makes transitions work as expected.

Splitting the commands further into one with only brightness, and one with only color temperature (no matter which order; making three commands in total), leads to the issue that the brightness is not correctly applied.

As mentioned before, it seems like a fix could be to wait for one command (transition) to finish before sending the next command. I am aware of the implications on user experience when then AL adjustment is delayed, so a reasonable trade-off could be to immediately send a brightness-only command and with a delay the color temperature command. The idea is that a wrong brightness (e.g. too high in the middle of the night) is perhaps more problematically perceived than a wrong initial color temperature. If this issue only happens with Tradfri lights (or any subset of brands/products), it could be an optional tweak.

**Comment by protyposis** [comment]
So... I found the `separate_turn_on_commands` config flag which basically does exactly that 🙈 It seems like it still needs some tweaking to work correctly, but this issue can be closed.

**Comment by th3w1zard1** [comment]
@protyposis Glad you found a solution! I also use the IKEA tradfri bulbs but I haven't noticed this problem. I ran the script you posted and it did not show the issue either. There's another command you might want to play with if you're still having trouble: `send_split_delay` and `adapt_delay`

**Comment by protyposis** [comment]
I suspended using `separate_turn_on_commands` due to the bug described in https://github.com/basnijholt/adaptive-lighting/issues/410#issuecomment-1539788096 (lights turning back on after turning off). Missing transitions are the lesser problem :)
