### ISSUE TITLE
`separate_turn_on_commands`: Adjust brightness first?

### ISSUE THREAD

**Issue by protyposis** [basnijholt/adaptive-lighting#588]
I would like to propose a user experience improvement to `separate_turn_on_commands`. Currently, when a command is split into two, the first command updates the color temperature, and the second one the brightness. I think that's not always ideal.

Here's an example (let's assume the `initial_transition` is set to `2` seconds):

1. Turn on lights during the day. AL sets brightness to 100%.
2. Turn off lights during the day.
3. Later during the night, you wake up and wander from your bedroom to your bathroom.
4. You turn on the bedroom lights. They first ramp up to 100% and burn your eyes for one second while AL adjusts the color temperature. Only afterwards, AL dims them down to 1%.
5. Relieved, you cross the hallway, where the same thing happens.
6. Then again in the bathroom. You're fully awake 😬😅 

So at night, I'd rather have a dimmed light at a wrong color temperature (that adjusts with a little delay) than a shockingly bright light. During the day, I think ramping up the brightness first might also be the smarter choice, because you probably don't want to wait 1 second until the light gets bright enough to be useful. Overall, a correct brightness settings could be more important for the utility of a light than the color temperature, which tends to be more of a cosmetic function.

There are multiple factors determining if and how bad this really is perceived, e.g., the distance of the starting brightness/temperature to the desired value, the configuration (transition length, min/max brightness, ...), used hardware, user sensitivity, and the example describes a worst-case scenario. But overall, I think this would be an optimization for the more extreme cases while not negatively affecting lighter cases.

As for the implementation, I think it's just a reorder of the two `if` blocks here: https://github.com/basnijholt/adaptive-lighting/blob/9caf64509349958a340f8cef9207fdb0ea35dbef/custom_components/adaptive_lighting/switch.py#L290-L298

Bonus improvement affecting the same code block: Skip unnecessary commands where lights are already at the desired state (e.g., to minimize Zigbee traffic).

What do you think?

**Comment by th3w1zard1** [comment]
I guess we could do this. Bonus points if you can figure out a way to implement your feature without changing existing setups. You are correct that swapping those two if blocks would swap the order.
>Bonus improvement affecting the same code block: Skip unnecessary commands where lights are already at the desired state (e.g., to minimize Zigbee traffic).

We already do this here (as requested in #80):
```
        # See #80. Doesn't check if transitions differ but it does the job.
        last_service_data = self.turn_on_off_listener.last_service_data
        if not force and last_service_data.get(light) == service_data:
            _LOGGER.debug(
                "%s: Cancelling adapt to light %s, there's no new values to set (context.id='%s')",
                self._name,
                light,
                context.id,
            )
            return
        else:
            self.turn_on_off_listener.last_service_data[light] = service_data
```

**Comment by th3w1zard1** [comment]
> Why do you think this is necessary? Seen as an iterative improvement of an existing feature, which is typically rolled out to existing setups, this should not need a config flag. Unless, of course, someone makes a reasonable argument why this is disadvantageous and degrades it from an improvement to an optional tweak. Then it should be disabled by default anyway.

I feel it's important to maintain the core logic across multiple different versions. The only exceptions should be bug-related. This isn't a bug; so it's more desirable to create a configuration option that allows the user to specify what order they want their service data to be sent to light.turn_on. 
The average user doesn't read the release notes and will mash the 'update' button expecting everything to work the same.

> I am not sure what this code block does or if it does anything at all, but it doesn't prevent unnecessary commands. See this Z2M log-

The code I posted is supposed to check if the service data is exactly the same as what was sent in the previous adapt. It does this by logging the service data sent to the light each iteration, and then comparing it to the previous before calling light.turn_on.

> As I understand your comment, the second adaptation command should not be sent? Bug? Anyway, this is related but different from what I proposed: What I meant is when commands are split, only those parts should be sent which actually change something. Continuing the example from above:

If you are using Adaptive Lighting 1.10.0 or later, that is indeed a bug you've reported. Would you mind enabling debug logging, reproduce the issue and post the adaptive lighting logs logged during that time? They would be very helpful for diagnosing the issue as I'm currently unable to reproduce it on my end.

**Comment by protyposis** [comment]
Let's move the bug discussion over to #589 and continue the discussion of the actual feature proposal in here.

**Comment by TheAlphaLaw** [comment]
This suggest is ideal. My wife constantly complains about initial brightness transition, especially when carrying our newborn around at night. I ended up just disabling adaptive light brightness after sundown and using a specific brightness when motion is detected. 

Ideally the light would turn on to specific brightness and temperature with no visible transition.

**Comment by TheAlphaLaw** [comment]
> @TheAlphaLaw Using "adaptive lighting apply" to turn on the lights instead of just "turn on light" help for the initial brightness transition. But still having issues with brightness only very dim at like 3 in the morning and 1 hours later and before it's way to bright at more than 1%

Thank you I will try this, hopefully it helps with motion sensors. I wish there was a good way to do this with voice and my wall mounted tablets.
