### ISSUE TITLE
FR: max_sunset option

### ISSUE THREAD

**Issue by MRobi1** [basnijholt/adaptive-lighting#592]
We get some pretty late sunsets here in the middle of summer. I'd love to see a max_sunset option to start adapting the lights earlier during those days. So let's say sunset is 9pm, we could set a max_sunset of 8pm to start adapting color and brightness a bit earlier. I wouldn't want to do this using offset since it would apply year round.

**Comment by basnijholt** [comment]
I have added this in https://github.com/basnijholt/adaptive-lighting/pull/707.

Please try out the `main` branch or `1.19.0b2` which I will release soon.
