### ISSUE TITLE
Slow Down Sparky

### ISSUE THREAD

**Issue by WeaselBreath** [basnijholt/adaptive-lighting#6]
Why are we getting multiple updates per day for this addon, that require a restart.  I appreciate the attention the author puts into the project, but maybe only 1-2 updates per week???

**Comment by Jeltel** [comment]
It's in full development. Then it's logical it gets more than the regular updates. You don't have to install every update. Just skip a few if you've got no issues.

I'm for one am happy about this development after being a bit irritated about the lack of development of the Circiadian Lighting addon.

So full steam ahead sparky!

**Comment by WeaselBreath** [comment]
If you are going to release 3-4 updates a day, then why not start a beta version and then lab rats like Jeltel can spend their day giving feedback.  Then make a public release when necessary.

I also used and still have installed the Circadian Lighting addon and it worked great without being updated multiple times per day.

I appreciate the authors enthusiasm for this project, but if you are going to make 3-4 changes per day then perhaps releasing them via a beta channel is the way to go.  I see a lot of other HA addon authors follow this route.

**Comment by broyuken** [comment]
Or how about stick with circadian lighting until this is released if you can’t handle the updates. Consider this a beta channel since the full release will be part of core. This is the silliest issue, “you’re doing too much work on this”

**Comment by WeaselBreath** [comment]
You are right, I deleted this train wreck and went back to Circadian Lighting

**Comment by basnijholt** [comment]
Sorry, I didn't get notified of these issues, I am only seeing it now.

@WeaselBreath, no one is forcing you to click the update button...
