### ISSUE TITLE
WLED not working in V1.12

### ISSUE THREAD

**Issue by Tommatheussen** [basnijholt/adaptive-lighting#601]
# Home Assistant Adaptive Lighting Issue Template

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ ] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

Debug logs for version 1.11 (that works): [home-assistant_adaptive_lighting_2023-05-25T18-28-38.253Z.log](https://github.com/basnijholt/adaptive-lighting/files/11568155/home-assistant_adaptive_lighting_2023-05-25T18-28-38.253Z.log)

Debug logs for version 1.12: [home-assistant_adaptive_lighting_2023-05-25T18-33-37.614Z.log](https://github.com/basnijholt/adaptive-lighting/files/11568207/home-assistant_adaptive_lighting_2023-05-25T18-33-37.614Z.log)

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):
```
lights:
  - light.wled_sink
prefer_rgb_color: true
include_config_in_attributes: true
initial_transition: 0
sleep_transition: 1
transition: 0
transition_until_sleep: false
interval: 10
min_brightness: 1
max_brightness: 45
min_color_temp: 2000
max_color_temp: 5500
sleep_brightness: 1
sleep_rgb_or_color_temp: color_temp
sleep_color_temp: 1000
sleep_rgb_color:
  - 255
  - 56
  - 0
sunrise_time: null
max_sunrise_time: null
sunrise_offset: 0
sunset_time: null
min_sunset_time: null
sunset_offset: 0
only_once: false
take_over_control: false
detect_non_ha_changes: false
separate_turn_on_commands: false
send_split_delay: 0
adapt_delay: 0
autoreset_control_seconds: 0
name: Sink
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:
After upgrading to V1.12, some of my WLED lights do not adapt anymore.

5. Steps to reproduce the behavior:
Upgraded to the newest version, no clue how to reproduce is, but restarting or reconfiguring does not seem to change anything. Downgrading to 1.11 makes them work again.

**Comment by tomadan1968** [comment]
Hello, i have the same problem here.

**Comment by th3w1zard1** [comment]
What's the brand and model number of your lights?

**Comment by Tommatheussen** [comment]
This particular light is controlled via a QuinLED DigUno controller board, running WLED version 0.13.3.
This LED strips itself are a SK6812 RGBW ledstrip from BTFLight.

**Comment by tomadan1968** [comment]
> What's the brand and model number of your lights?

Hello, it's a strip led controled with Shelly RGBW2

**Comment by Ede711** [comment]
Controller: Shelly RGBW2 (V. 1.13.1)
LED strip: Paulmann MaxLED 250 - PN 79867

**Comment by cinghialino** [comment]
same problem with WLED and some SK6812 , went back to 1.11 to solve it.

**Comment by javilopezalarcon** [comment]
I have the same problem, the shelly rgbw2 lights don't adapt... I've tried 1.12, 1.13 and 1.14, none of them resolved it, with 1.11, which is where I'm staying, they work perfectly

**Comment by tomadan1968** [comment]
> 

Same here..

**Comment by CmdrShepard482** [comment]
Same issue for me also using 1.12, 1.13, and 1.14. I am using SK6812 running directly off an ESP8266 in both instances

**Comment by ASNNetworks** [comment]
Came here to confirm and also post something else I found out. When you have a split the lightstrips in multiple segments, you get a Master light. That one does adapt with this integration still somehow (brightness). The Master only only has brightness, but that does still adapt.

**Comment by asolochek** [comment]
This also isn't working for me on 1.14 with an Athom LS-5P (an ESP2866 running WLED). I get changes using 1.11, but the color is way warmer than it should be.

**Comment by javilopezalarcon** [comment]
good morning, do you know if this already works in the .15? Until the .14 I could go back to the .11, but when I left the .15 it only appears to go back to the .12 that doesn't work... how could I make a backup of the .11 to test if it works or not, and if not, to be able to go back to the .11 ..

**Comment by dexn** [comment]
Still not fixed in .15

**Comment by basnijholt** [comment]
Unfortunately, this hasn't been addressed yet. The code introducing the bug is likely here: https://github.com/basnijholt/adaptive-lighting/compare/1.11.0...1.12.0#diff-2ae6ce86e459ad0e8703be113d8bd00c7fb232c57bc6133c2f3e5a680fd008b2

**Comment by basnijholt** [comment]
I am looking into this.

For the lights that do not work, what `supported_features` is reported in the **Developer Tools**?

For example, my light here is 44:

<img width="1415" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/91b3934d-42cf-41b1-8279-35f383a40f5e">

**Comment by basnijholt** [comment]
I have opened a PR #637 where I attempt to fix this issue.

Can anyone give it a try?

**Comment by diplix** [comment]
i installed the newest adaptive lighting version on my HA version 2023.7.2 and patched the switch.py as you suggested.
adaptive lighting on my wled works now, however it breaks a couple of my mqtt lights. this is what i get when i try to turn on my `light.kinderzimmer_decke_light` light (from zigbee2mqtt):

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/adaptive_lighting/switch.py:310
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:03:52 (1 occurrences)
Last logged: 22:03:52

[140533052812944] find_switch_for_lights: Light(s) ['light.kinderzimmer_decke_light'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/hass_utils.py", line 46, in service_func_proxy
    await intercept_func(call, data)
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 1810, in _service_interceptor_turn_on_handler
    adaptive_switch = find_switch_for_lights(self.hass, [entity_id])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 310, in find_switch_for_lights
    raise ValueError(
ValueError: find_switch_for_lights: Light(s) ['light.kinderzimmer_decke_light'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
```

**Comment by basnijholt** [comment]
@diplix, thanks for reporting back. That issue should also be fixed now. 

Please install v1.16.0 😄

Thanks all for your patience and support! 🙌

**Comment by asolochek** [comment]
For what it's worth, I worked around this issue by creating a template light, which also let me insert a blueprint "Use RGBW as CT light" so that I could calibrate the color temperature of my WLED lights to match my other lights.
