### ISSUE TITLE
Allow overrides in `apply` service

### ISSUE THREAD

**Issue by ashald** [basnijholt/adaptive-lighting#602]
In my specific case, I have a dial with a button.
When lights are off and button is pressed, I just call AL's `apply` and things are easy.
When lights are off and dial is rotated clockwise, I want to turn on lights to 10% but make sure to adapt color. Currently, there is no good way to achieve this. If I call `apply` first, I can get higher brightness than desired, and that wouldn't be pleasant. If I call `apply` after turning on lights to the desired level, the lights could be stuck in wrong color for a while (for some reason, AL doesn't seem to kick in immediately but after about 15 seconds in this case).

What I'd love to do is to be able to turn on lights and have their color adjusted by AL but set the brightness to the desired level. Looking at the code, I realized rather than adding support to such a specific case, it might make sense to just accept a dictionary of overrides to `light.turn_on` and update the parameters before the actual call.

Any chances this can be implemented? Or a PR accepted?

**Comment by th3w1zard1** [comment]
I'm not quite sure at the moment but take a quick look at `adaptive_lighting.change_switch_settings`, you might be able to find a workaround using it in a script or automation.

**Comment by ashald** [comment]
@th3w1zard1 could you help me understand how I can use `adaptive_lighting.change_switch_settings` please? My goal is to transition from light being off, to light being of correct color temperature, but specific brightness. `adaptive_lighting.change_switch_settings` seems to be about changing settings for adaptive lightning in general - or am I missing something?

**Comment by ashald** [comment]
Indeed, that worked - thanks! I'm setting min/max brightness to the same [desired] value, and then use `apply` and get what I want. I wish there was a more straightforward way though... 😊

**Comment by basnijholt** [comment]
@ashald, what you suggest in your first post has actually been implemented now. 

Try out the latest version 😀👍

it only works for turning on single lights now. Not multiple lights in a group.

**Comment by ashald** [comment]
Thanks a lot!
