### ISSUE TITLE
Transition to sleep not working as expected for RGB mode

### ISSUE THREAD

**Issue by sovanyio** [basnijholt/adaptive-lighting#608]
Been scratching my head why the transition to sleep settings weren't working for me and took a look at the code and it looks like that setting only supports color temp adjustment: https://github.com/basnijholt/adaptive-lighting/blob/4683f083f69952af7e9c26f9064305a62eddfe1a/custom_components/adaptive_lighting/switch.py#LL1660C8-L1660C8

When the sleep toggle is off, the transition is calculated against against the kelvin value and then converted back to rgb, which results in wrong/unexpected colors based on the setup (mine: 100% rgb(255, 0, 0)).

Minimally, would be nice to update the docs to explain this. I'm guessing that the lack of straight forward RGB support is due to the relative complexity of calculating the color delta VS calculating the appropriate color temperature. 

Spitballing--
```
if bulb is rgb sleep mode:
  if time => sunset:
    for each [r, g, b]:
      value = current val + ((sleep val - current val) / transition steps)
```

**Comment by pqhf5kd** [comment]
As far as I can tell, my lights are transitioning to pure red when enabling sleep mode. What are you seeing instead?

**Comment by sovanyio** [comment]
Expected behavior: lights transition to rgb sleep state without toggling the sleep boolean.
Actual behavior: lights transition to normal circadian mode rather than defined rgb state. Toggling the sleep boolean works as expected.

Based on the code snippet I posted, I'm not sure how it would ever work with rgb sleep states?

**Comment by pqhf5kd** [comment]
Oh I'm sorry, are you talking about the transition_until_sleep option? 
I thought you were referring to the sleep toggle, ignore me 🤦

**Comment by basnijholt** [comment]
Right now, after sunset, it will switch to rgb. And will start with the converted color temperature at that point in time and interpolate to sleep_rgb_color. 

Update to the latest version and let me know whether it works 😃
