### ISSUE TITLE
Changes not saving

### ISSUE THREAD

**Issue by Stooovie** [basnijholt/adaptive-lighting#611]
- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

[log is here](https://nc.jirifiala.cz/s/3R28FPDaTBotCWw)

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
I config by GUI, I don't know how to post that
```

3.  Zigbee

[https://nc.jirifiala.cz/s/CrTzK5654FssjZY](url)

6.  Describe the bug and how to reproduce it:

Changes in settings of AL do not save. Some of my lights are now in sleep mode during the day. I haven't changed the Adaptive Lighting config for years. I go to the AL settings, I turn off Sleep Mode, click Apply, change doesn't save. No issues with other integrations.

**Comment by protyposis** [comment]
Should be fixed by #607 in version [1.14.0](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.14.0). Please reopen if issue persists.
