### ISSUE TITLE
Speed of sunset/sunrise setting

### ISSUE THREAD

**Issue by funkytwig** [basnijholt/adaptive-lighting#616]
So you can tweak around sunset_offset and sunrise_offset to tell AL the sun is setting/rising earlier/later but I guess there is a curve that is used to say how this happens.  I would like to change this. I guess this is affected by where you are.

"The distance from the equator and the path of the sun determines not only the time of sunrise and sunset.....While a sunset near the equator lasts only about 20 minutes, in the United Kingdom, this period averages 50 minutes. In June, it's about 60 minutes in London, while in December it's 41 minutes. "[worlddata.info]( https://www.worlddata.info/europe/united-kingdom/sunset.php).

I am not saying AL has got this wrong, its just I would like to be able to make my lights dim a bit quicker.  Maybe telling changing the curve is a bit much for users, but maybe a sunser_speed and a sunrise_speed percentage maybe 500 to -500%.  Think this would only be applied to the main bit of the curve, effectively squashing (maybe) 10% around subset/sunrise (could have a squash_curve_around_sunrise_sunset percent).

If there is anything to do to help let me know.  I love the Integration.  I had a little look around the code but can't work out how this would be done.  Is there some type of document that explains how things are done /fit together?

**Comment by th3w1zard1** [comment]
I don't quite understand why `sunset_offset` and `sunrise_offset` aren't options here. You say you want your lights to dim by around an hour, wouldn't setting sunset_offset to `-3600` allow you to do this?

The percentages used in your example `sunset_speed` and `sunrise_speed` just don't make sense as the offsets *should* already control that. Apologies if I misunderstood something here.

**Comment by danielbrunt57** [comment]
I think what he wants is for the _duration_ of sunrise to be either shorter or longer in addition to when it actually starts, which we can do now via `sunrise_offset`, We should also be able to alter the effective _duration_ of sunrise which is sun.sunriseEnd - sun.sunriseStart.  If we had an input like like `sunrise_end_offset`, we could affect the slope the circadian curve from sun.sunriseStart to sun.sunriseEnd,

At the equator, sunrise _duration_ is only 20 minutes while further north it lengthens to upwards of an hour or more, which leads me to another approach. Rather than using sunrise_offset, allow input of a different location's cordinates for the sun curve, or an input of a +/- number of degrees to add to or subtract from the current location's coordinates.  It would depend on Adaptive Lighting's internal coding, whether this is feasible or not.

All food for thought...

**Comment by basnijholt** [comment]
I have started working on https://github.com/basnijholt/adaptive-lighting/pull/699

**Comment by basnijholt** [comment]
Hi folks, I have implemented this feature request in https://github.com/basnijholt/adaptive-lighting/pull/699.

That PR allows setting different `brightness_mode`s which determine how the brightness changes around sunrise and sunset. Here `brightness_mode` can be either `"default"` (current behavior), `"linear"`, or `"tanh"`. Additionally, when **not** using `"default"`, you can set `brightness_mode_time_dark` and `brightness_mode_time_light`.

with `brightness_mode: "linear"`:
- During **_sunset_** the brightness will start adapting constantly from `max_brightness` at `time=sunset_time - brightness_mode_time_light` to `min_brightness` at `time=sunset_time + brightness_mode_time_dark`.
- During **_sunrise_** the brightness will start adapting constantly from `min_brightness` at `time=sunrise_time - brightness_mode_time_dark` to `max_brightness` at `time=sunrise_time + brightness_mode_time_light`.

with `brightness_mode: "tanh"` it uses the smooth shape of a [hyperbolic tangent function](https://mathworld.wolfram.com/HyperbolicTangent.html):
- During **_sunset_** the brightness will start adapting from 95% of the `max_brightness` at `time=sunset_time - brightness_mode_time_light` to 5% of the `min_brightness` at `time=sunset_time + brightness_mode_time_dark`.
- During **_sunrise_** the brightness will start adapting from 5% of the `min_brightness` at `time=sunrise_time - brightness_mode_time_dark` to 95% of the `max_brightness` at `time=sunrise_time + brightness_mode_time_light`.

It would be awesome to get some feedback!

**Comment by basnijholt** [comment]
Some examples of the settings:

![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/5199f0b8-7e67-4ce6-a9d3-bc70372cb489)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/d655292f-2e9a-40ad-b48f-aad561849adf)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/ee55dbb6-ed6f-4212-92ae-d651911c04b4)

**Comment by danielbrunt57** [comment]
I for one am anxious to try this out!

**Comment by funkytwig** [comment]
Sorry, I have not replied, and thanks for everybody's time replying.   Should fo said how I saw the problem, not what I thought the solution was.  rucky error.  Basically, Inside a building from around 1/2-1 house after sunset, it is (for all intense and purposed) dark but the Adaptive Lighting service takes a lot longer to go to minimum brightness (maybe 2-3 hours).  In the morning it is similar.  I want it to stay on minimum brightness until the sun starts raising (i.e. start going to max brightness 1/2 house before sunrise and reach max brightness maybe 1 house after sunrise).

So basically I am asking if there is a way of saying how long after sunset minimum darkness is reached. So maybe start reducing brightness 45 mins before sunrise and get to max brightness 45 mins after. This seems about right for the UK.

Sunrise, it is similar.  Maybe start getting brighter 45 mins after sunrise and reach max brightness 45 minutes after.

So I guess the second curve is the closest.  One way of doing this is to have a number of curves based on total duration min to max brightness around sunset/sunrise.   For me, in the UK the curve may be called '1.5-hour transition'  (i.e. start diming/britening 45 mins before/after sunset/sunrise)

The curves could be.

- 1/2 hour transition
- one-hour transition
- 1.5 hour transition 
- 2-hour transition

The shortest would be if you were on the equator and the longest if you were furthest from the equator.  In brackets, you could also have places or a Curve for each UTC time zone.

Hope this makes sense and is useful.  I initially thought it would be numeric parameters but looking at this post curves seem to be the way things are done.

**Comment by basnijholt** [comment]
Please try out [version 1.19.0 beta 1](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.19.0b1) :tada: 🚀

**Comment by danielbrunt57** [comment]
Installed and reconfigured office lights but I won't be home to observe until tommow night 😭
Sunrise/Sunset offsets now 0. 
brightness_mode: tanh
brightness_mode_time_dark: 7200
brightness_mode_time_light: 1800

**Comment by danielbrunt57** [comment]
> So basically I am asking if there is a way of saying how long after **sunset** minimum darkness is reached. So maybe start reducing brightness 45 mins before **_sunrise_** and get to max brightness 45 mins after. This seems about right for the UK.
> Sunrise, it is similar. Maybe start getting brighter 45 mins **_after_** sunrise and reach max brightness 45 minutes **after**.

You need to get your before's and after's straight as well as sunrise/sunset!

I think what you want is to start dimming 45 minutes before sunset and reach min brightness 45 minutes after sunset
and for sunrise...
Start brightening 45 minutes before sunrise and reach max brightness 45 minutes after sunrise.
 
For that, install the beta, change brightness_mode from default to either tanh or linear, set brightness_mode_time_dark and brightness_mode_time_light to 2700 (seconds) which will be start 45 minutes before and end 45 minutes after sunrise/sunset.

**Comment by basnijholt** [comment]
Check out https://basnijholt.github.io/adaptive-lighting/ for an interactive graph.

**Comment by funkytwig** [comment]
> I think what you want is to start dimming 45 minutes before sunset and reach min brightness 45 minutes after sunset and for sunrise... Start brightening 45 minutes before sunrise and reach max brightness 45 minutes after sunrise.
> 
> For that, install the beta, change brightness_mode from default to either tanh or linear, set brightness_mode_time_dark and brightness_mode_time_light to 2700 (seconds) which will be start 45 minutes before and end 45 minutes after sunrise/sunset.

Thanks, You lot rock.

**Comment by funkytwig** [comment]
> Check out https://basnijholt.github.io/adaptive-lighting/ for an interactive graph.

Love it.  I take it that if the sunset/sunrise time is not set it uses the actual time (i.e. the change does not require the times to be set).

**Comment by funkytwig** [comment]
> Please try out [version 1.19.0 beta 1](https://github.com/basnijholt/adaptive-lighting/releases/tag/1.19.0b1) 🎉 🚀

Will give it a go but I've never installed 'manually' Can you point me to a howto to do this?  

Thanks for everybody's work.

**Comment by danielbrunt57** [comment]
Once you are here...
![Screenshot_20230807_102221_Home Assistant](https://github.com/basnijholt/adaptive-lighting/assets/49846893/b85fb02a-c372-4431-a75f-30826e68d02d)
click the three dots top right and select Redownload...
![Screenshot_20230807_102354_Home Assistant](https://github.com/basnijholt/adaptive-lighting/assets/49846893/2d6a021d-8d06-4a14-8a0f-a7475184d791)
which takes you here...
![Screenshot_20230807_102449_Home Assistant](https://github.com/basnijholt/adaptive-lighting/assets/49846893/acf6665a-2648-4067-9622-a95cdf8645a4)

**Comment by funkytwig** [comment]
LOL, that was the only option I did not try.  I feel quiter stupid.

**Comment by funkytwig** [comment]
Thanks, done.  Set up and will test it tonight.  I set offsets to 0 and brightness_time_mode_dark/light to 2700.

I noticed (you will see in the screengrab below) The long descriptions of these parameters go over the edge of the pop-up, not truncated with ...).

Also these default to 900/3600, I was expecting 0.  Not sure if that is relevant.

![image](https://github.com/basnijholt/adaptive-lighting/assets/14052216/5c74e6a3-0a52-4462-a48d-118a2b2aada2)

**Comment by funkytwig** [comment]
OK, notised something else.  Can raise another issue if you want.  If you remove the offsets and set them blank, rather than set them to 0, it does not work.  When you go back they are set to what they were before.

**Comment by danielbrunt57** [comment]
"Also these default to 900/3600, I was expecting 0. Not sure if that is relevant." 
That is not relevant if brightness_mode is 'default' since the `brightness_mode_time...` only applies to tanh or linear. 900 & 3600 are only there to act as programmed defaults for tanh & linear.

**Comment by danielbrunt57** [comment]
> OK, notised something else. Can raise another issue if you want. If you remove the offsets and set them blank, rather than set them to 0, it does not work. When you go back they are set to what they were before.

The integration could use better error checking of inputs there....

**Comment by danielbrunt57** [comment]
@funkytwig Perhaps you could open a new issue for @basnijholt to keep track of it...

**Comment by funkytwig** [comment]
OK. Seems to be working well.  2700 Matched the sunset nicely.  As for sunrise not sure when I will be around for it but if it happens will let you know.  Nice job.

**Comment by funkytwig** [comment]
> @funkytwig Perhaps you could open a new issue for @basnijholt to keep track of it...

Will test again and do so.

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

![adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/assets/6897215/4e5cb08c-0327-40c2-8822-3095eb795358)

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f

**Comment by funkytwig** [comment]
Could not sleep last night so got to test whne sun came up and it works.  So basic user testig passed :-)
