### ISSUE TITLE
change_switch_settings - "use_defaults = configuration" not working as expected

### ISSUE THREAD

**Issue by turi400** [basnijholt/adaptive-lighting#623]
### Discussed in https://github.com/basnijholt/adaptive-lighting/discussions/617

<div type='discussions-op-text'>

<sup>Originally posted by **turi400** June 18, 2023</sup>
I'm trying to setup an automation to adjust the brightness curve in the evening (I'd rather wait until 7pm for it to start dimming, I'm happy with the color curve).

I'm using adaptive_lighting.change_switch_settings to achieve this. One of my actions is to revert to the settings configured in the AL Integration UI. If my understanding of this service call is correct, using the "use_defaults: configuration" with no other explicit settings should achieve this. Or do I have this completely wrong?

As it stands, if I use the service call below, nothing changes (which is what I would expect if I used the "current" option).

service: adaptive_lighting.change_switch_settings
data:
  entity_id: switch.adaptive_lighting_main
  use_defaults: configuration

The only way I seem to be able to revert without again explicitly setting the values via adaptive_lighting.change_switch_settings is to reload the integration

[home-assistant_adaptive_lighting_2023-06-18T03-09-59.453Z.log](https://github.com/basnijholt/adaptive-lighting/files/11780583/home-assistant_adaptive_lighting_2023-06-18T03-09-59.453Z.log)

[AdaptiveLighting_Configuration.txt](https://github.com/basnijholt/adaptive-lighting/files/11780587/AdaptiveLighting_Configuration.txt)
</div>

**Comment by th3w1zard1** [comment]
Hello, I'm the one that added this feature.

I'm at a loss as to what the problem is. You are correct that the `configuration` option should default to whatever's in the configuration file. Looking over the code I don't see any immediate problems either.

I'll take your logs and write a test sometime later this week, thanks for the bug report.

**Comment by basnijholt** [comment]
I believe the misunderstanding is that the `service_call` changes the settings that are in the configuration. 

Instead it only changes it for the switch until Home Assistant is restarted. After that, the configuration will be as it is in the UI.

This feature is correctly implemented by @th3w1zard1 and it works great! ❤️

**Comment by mitchkeller** [comment]
I'm confused by @basnijholt's comment. What @turi400 has reported (and I am seeing as well) is that making the `service_call` changes nothing for the switch when `use_defaults: configuration` is passed. If that's the case, then there's no use for `use_defaults: configuration`, so why does it exist?

**Comment by basnijholt** [comment]
I didn’t understand that (reading is hard 😜). 

I’ll try producing this problem and fix it if @th3w1zard1 doesn’t get to it before me.

**Comment by basnijholt** [comment]
OK my attempt, the original settings as in set up in the UI:

<img width="683" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/5ff9ccba-d614-4666-a637-cc49977cebec">


Calling:

<img width="857" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/7c28a7a8-f6f4-4e17-b7e2-895a2ffc42cd">

Results in the correct change:

<img width="709" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/b5192cc7-d0c3-44d0-afb8-dbaa4fa823d1">


Then calling just `use_defaults: configuration`:
<img width="839" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/ecd72757-5e9b-4d96-9a3b-37bdd64faf36">

<img width="698" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/e83a8b98-bd98-43b5-a584-0f2a7c44ead5">



This indeed does not apply the defaults again.

**Comment by basnijholt** [comment]
We were mutating the copy of the configuration settings, so therefore it didn't work. I fixed it in #712.

Thanks again for reporting and your patience 😄 

I will release 1.19.0b3 soon.

**Comment by basnijholt** [comment]
(Beta) release with fix is out https://github.com/basnijholt/adaptive-lighting/releases/tag/1.19.0b3

**Comment by turi400** [comment]
Beta release fixes it for me 👍

**Comment by basnijholt** [comment]
Awesome! Thanks for reporting back 😄
