### ISSUE TITLE
color temp before sunset and RGB after

### ISSUE THREAD

**Issue by mouth4war** [basnijholt/adaptive-lighting#624]
I would like to use color temp until transition to sleep kicks in and turns lights red.

**Comment by ridxe** [comment]
Same here.
If I have the "use rbg over colour temp" it works fine.
But rgb on my lights during the day is horrible.
But the at night time they don't flick over to rgb and use red. Very frustrating.

**Comment by basnijholt** [comment]
Just use sleep_rgb_or_color_temp and see the README 😄

AFK now. Let me know whether that solves your problem.

**Comment by ridxe** [comment]
I wish it did!
However does not...

**Comment by ridxe** [comment]
Hey I still don't have my lights changing to rgb night mode.. I have to run an automation that manually toggles it.

**Comment by Nechaken** [comment]
> Just use sleep_rgb_or_color_temp and see the README

So, as far as I can tell, turning on sleep mode via the switch will pop the light (in my case, a hue) from color_temp to rgb_color.  But, turning on "transition to sleep" doesn't result in the light moving to sleep mode (and thus moving from colortemp mode to rgb mode.)  So the transition never gets "redder" than 2000K.

**Comment by basnijholt** [comment]
Ah, I see. Do you mean `transition_until_sleep`?

**Comment by Nechaken** [comment]
> Ah, I see. Do you mean `transition_until_sleep`?

Yes, transition_until_sleep.  Sorry.

**Comment by ridxe** [comment]
This exactly.
If I havw prefer rbg over color temp it works fine. But then I have terrible daytime lights.
Hence needing an automation to manually turn on nightime after a certain time.

**Comment by basnijholt** [comment]
OK I think this feature is doable. I would just have to interpolate between color_temp and RGB here 

https://github.com/basnijholt/adaptive-lighting/blob/c1528ec10a514b7b0e52a1a95f122d9964130961/custom_components/adaptive_lighting/switch.py#L1640

**Comment by basnijholt** [comment]
OK folks, could you try out the code in https://github.com/basnijholt/adaptive-lighting/pull/656?

**Comment by Nechaken** [comment]
I'll give this a shot tonight.  Thanks for your attention - I really dig this component!

**Comment by mouth4war** [comment]
This got fixed but the calculation is off. Lights look green instead of red

**Comment by basnijholt** [comment]
What did you guys set as min_color_temp and sleep_rgb_color?

likely the linear interpolation between those colors is not a satisfying path?

**Comment by mouth4war** [comment]
Min color temp is 1700k and sleep RGB color is red.

**Comment by basnijholt** [comment]
I have just realized the problem. 😅

I assumed that the variable percent was between 0 and 1. However, it is between -1 and 1. I’ll push a fix ASAP.

**Comment by basnijholt** [comment]
I opened https://github.com/basnijholt/adaptive-lighting/pull/660 and will release 1.17.1 shortly.

**Comment by basnijholt** [comment]
I also implemented a better color interpolation function that first converts to HSV, performs the interpolation in that color space, and then converts back to RGB.
