### ISSUE TITLE
How to get Ikea bulbs to work?

### ISSUE THREAD

**Issue by MarkuBu** [basnijholt/adaptive-lighting#625]
Hi, I have several Ikea light bulbs and I want to use Adaptive Lighting with them, but I can't get it to work. I know that there is an issue caused by the lights, but is it possible to work around this issue, like a firmware update or a specific setting in Adaptive Lighting?

**Comment by protyposis** [comment]
Check the Ikea Tradfri section in https://github.com/basnijholt/adaptive-lighting#bulb-bulb-specific-issues

**Comment by MarkuBu** [comment]
That's helpful, thanks
