### ISSUE TITLE
light.turn_on and light.toggle services impacted by update

### ISSUE THREAD

**Issue by StumblingGamer** [basnijholt/adaptive-lighting#638]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [X] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [X] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/adaptive_lighting/switch.py:327
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 1:09:33 PM (12 occurrences)
Last logged: 1:38:14 PM

[140634344999312] find_switch_for_lights: Light(s) ['light.table'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
[140634344999312] find_switch_for_lights: Light(s) ['light.family_room_ceiling'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
[140633627447376] find_switch_for_lights: Light(s) ['light.family_room_ceiling'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 46, in service_func_proxy
    await intercept_func(call, data)
  File "/config/custom_components/adaptive_lighting/switch.py", line 1843, in _service_interceptor_turn_on_handler
    adaptive_switch = find_switch_for_lights(self.hass, [entity_id])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/switch.py", line 327, in find_switch_for_lights
    raise ValueError(
ValueError: find_switch_for_lights: Light(s) ['light.table'] not found in any switch's configuration. You must either include the light(s) that is/are in the integration config, or pass a switch under 'entity_id'.
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
I used Front End to configure... not sure how to get the config.  I am willing to get it, just need to know how.
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```
problem persists against all light devices zwave and zigbee and wifi...   I have already confirmed this isn't related to those services.
```

4.  Describe the bug and how to reproduce it:
Likely the cause:  https://github.com/basnijholt/adaptive-lighting/pull/628
When attempting to call light.turn_on or light.toggle on any light that is not configured in Adaptive Lighting, an error is generated and light control is not possible.  

5. Steps to reproduce the behavior:
Call light.toggle or light.turn_on service on ANY light entity that is NOT configured with Adaptive Lighting.

**Comment by Eyco1981** [comment]
+1
All not in AL integrated lights (e.g. switches converted to lights) cannot be turned on with version 1.15.1.
1.15.0 is working, so commit 1133f0d seems to be the culprit.

**Comment by basnijholt** [comment]
@StumblingGamer, @Eyco1981, thanks a lot for reporting. I understand what the problem is. 

We don't have tests for managing lights that are not managed by AL so I didn't catch this one.

I opened https://github.com/basnijholt/adaptive-lighting/pull/639 which should fix this. I will release 1.15.2 promptly.

**Comment by basnijholt** [comment]
I have just released https://github.com/basnijholt/adaptive-lighting/releases/tag/1.15.2, let me know whether it works now.

**Comment by Eyco1981** [comment]
Seems to be working again

**Comment by basnijholt** [comment]
Great, thanks for reporting back! 😄

**Comment by StumblingGamer** [comment]
> Great, thanks for reporting back! 😄

Thanks for your quick response to this!  Much appreciated.

Keep up the good work!  My wife and I love the integration and what it does for the ambiance of the house.  🤘😁
