### ISSUE TITLE
Unable to install this custom add-on

### ISSUE THREAD

**Issue by artemkolotilkin** [basnijholt/adaptive-lighting#65]
I'm trying to follow the installation instructions and having troubles with the very first step.
> add https://github.com/basnijholt/adaptive-lighting to your custom repos in HACS and install it 

When I try to add the URL, I'm getting `Invalid Add-on repository!`.

Is there anything I'm missing or should the instructions be updated? Sorry if it's a simple question. I'm still new to Home Assistant ecosystem. And thanks in advance for your help!

**Comment by Chreece** [comment]
Hello,

Where exactly are you trying to put the URL?
Are you sure you are adding it in HACS (from the left bar) -> click on 3 dots upper left corner -> Custom repositories

**Comment by artemkolotilkin** [comment]
My bad. I was trying to install it from a Supervisor screen -> Add-on Store -> Repositories. Probably because I just added Zigbee2mqtt that way. From your comment I realized that [HACS](https://hacs.xyz/) is a completely different thing that I need to install first. That should resolve my issue. Thanks a lot!
