### ISSUE TITLE
Display the AL version number in the integration config panel?

### ISSUE THREAD

**Issue by danielbrunt57** [basnijholt/adaptive-lighting#653]
It would be nice to see it somewhere here...

![image](https://github.com/basnijholt/adaptive-lighting/assets/49846893/82775c59-50f8-4077-8628-46d325cfce2c)

**Comment by basnijholt** [comment]
That's a great idea, however, this is not in our control unfortunately. Rather one has to make this change in https://github.com/home-assistant/frontend.

**Comment by danielbrunt57** [comment]
Will do, thanks!
