### ISSUE TITLE
Todos release 1.19.0

### ISSUE THREAD

**Issue by basnijholt** [basnijholt/adaptive-lighting#664]
- [x] detect_non_ha_changes needs to be enabled to detect state_changes
- [x] in significant_change there is no need to "if detect_non_ha_changes" because it is only called if that is the case
- [x] Setting 0% brightness with turn_on, should not intercept
- [x] https://github.com/basnijholt/adaptive-lighting/issues/720
- [x] https://github.com/basnijholt/adaptive-lighting/issues/726
- [x] https://github.com/basnijholt/adaptive-lighting/issues/723
- [x] fix long descriptions in UI for `brightness_mode` related things

Won't fix:
- [x] [manual control is broken with having two switches for the same light (one brightness and one color), it just marks as manually controlled, even though maybe you only changed color](https://github.com/basnijholt/adaptive-lighting/issues/730)

**Comment by fbloemhof** [comment]
Great to see al the effort you put in this project! Is it an idea to adopt some kind of release schedule? Publishing new releases in such short timeframes is quite intense, regarding the restart HA needs after updating.

**Comment by basnijholt** [comment]
@fbloemhof, there is no release schedule because I cannot consistently dedicate the same amount of time to working on this integration. I currently have some time because I am on early parental leave and the babies are sleeping mostly 😄 

I would also not recommend to instantly update if you do not want to try out the newest features. Recently we added a couple new features which came with a lot of bugs, which I immediately tried to fix by making patch releases.

**Comment by Wireheadbe** [comment]
Congrats on the babies! 👏🏻 🎈 👶🏻

**Comment by bouwew** [comment]
@basnijholt When reading this: "I would also not recommend to instantly update if you do not want to try out the newest features" I would suggest you should release such updates as beta-versions.

**Comment by basnijholt** [comment]
@bouwew, I have not been using beta versions because it is more time consuming (it's just me doing this mostly).

However, I have released a first a first beta `1.19.0b0` but I doubt many folks will notice it and install it.

**Comment by bouwew** [comment]
Our way-of-working with the Plugwise-beta custom_components is that we create an a-version for testing by the devs, a b-version that we ask the issuer and others that follow the issue to test. An when the issuer(s) tells us it's working, we create the formal release-version.

Don't worry, many people that know about the Show Beta-button in HACS have it enabled :)

**Comment by basnijholt** [comment]
I used this issue to track TODOs for 1.19.0, which I have just released after 5 betas 😄 🎉
