### ISSUE TITLE
Moving from YAML config to UI config doesn't work

### ISSUE THREAD

**Issue by jamescadd** [basnijholt/adaptive-lighting#68]
Hello, I started with a YAML config and then decided to move to UI.  I commented out the adaptive_lighting section, rebooted HA, but was still given the message about not seeing UI config if YAML is present in the integration options screen.  I tried uninstalling adaptive_lighting through HACS and rebooting, and oddly after that I saw a notification in HA that the integration adaptive_lighting couldn't be setup (this could be old, have to double check).  However at that point the old config appeared to still be present and I was still unable to configure adaptive lighting via UI.  Is there somewhere the config is stored that I can delete the old data?

**Comment by basnijholt** [comment]
Does deleting the instance from "Config" -> "Integrations" work?

For reference:
![image](https://user-images.githubusercontent.com/6897215/103484516-aa9efa00-4def-11eb-9f78-1453acc3b73d.png)

**Comment by Davst** [comment]
Had this same issue, deleting the integration worked, though this is quite unintuitive.

**Comment by glemsom** [comment]
I'm having the same issue. Deleting the integration, and reinstalling does not seem to work.

**Comment by RubenKelevra** [comment]
Well, the config is stored below configuration -> integrations. If you delete it, the settings will be reset.

If you remove the component, the settings cannot find the corresponding component and thus there's this error message.

Hope this makes now more sense.

**Comment by th3w1zard1** [comment]
Is this still an issue with the latest adaptive-lighting 1.7.0?

**Comment by th3w1zard1** [comment]
stale
