### ISSUE TITLE
Kelvin doesn't go below 2500k when set to 2200k and bulb supports it.

### ISSUE THREAD

**Issue by IIV-NATHAN-VII** [basnijholt/adaptive-lighting#694]
# Home Assistant Adaptive Lighting Issue Template

Even though I set lowest to 2200k and sleep mode to 2200k, it never drops below 2500k, works fine in Tapo app (using tapo bulbs).

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ ] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```

```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```

```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:

5. Steps to reproduce the behavior:

**Comment by basnijholt** [comment]
Are you sure your light has that in the attributes?

What does it report in the Developer Tools attributes?

e.g.,: 
<img width="1224" alt="image" src="https://github.com/basnijholt/adaptive-lighting/assets/6897215/b429c0ed-44c1-43ab-88c8-bf03509ca973">

K = 1000000 / mired

So for me, taking:
```
min_mireds: 150
max_mireds: 500
```

minimum: 1000000 / 500 = 2000 K 

Can you check your values?

**Comment by IIV-NATHAN-VII** [comment]
`min_color_temp_kelvin: 2500
max_color_temp_kelvin: 6500
min_mireds: 153
max_mireds: 400
supported_color_modes:
  - brightness
  - color_temp
  - hs
  - onoff
friendly_name: Living
supported_features: 0
color_mode: color_temp
brightness: 255
color_temp_kelvin: 2906
color_temp: 344
hs_color:
  - 27.987
  - 59.51
rgb_color:
  - 255
  - 174
  - 103
xy_color:
  - 0.505
  - 0.385
`

**Comment by IIV-NATHAN-VII** [comment]
So I just did an override in my config:

`homeassistant:
  customize_domain:
    light:
      min_color_temp_kelvin: 2200
      max_color_temp_kelvin: 6500`

Shows in Developer Attributes.
min_color_temp_kelvin: 2200
max_color_temp_kelvin: 6500
min_mireds: 153
max_mireds: 400
supported_color_modes:
  - brightness
  - color_temp
  - hs
  - onoff
color_mode: color_temp
brightness: 102
color_temp_kelvin: 2500
color_temp: 400
hs_color:
  - 28.874
  - 72.522
rgb_color:
  - 255
  - 159
  - 70
xy_color:
  - 0.546
  - 0.389
friendly_name: Living
supported_features: 0

Still only sets 2500.

**Comment by basnijholt** [comment]
I think this is due to the `max_mireds: 400`, you should set that to 

`max_mireds = 1000000 / 2200 = 454`

This is because Home Assistant computed the `min_color_temp_kelvin` based on the mireds (I believe).

**Comment by IIV-NATHAN-VII** [comment]
After a bit of digging I think it's something else, I can see it changing on the Tapo app when I toggle sleep mode on/off, I can also see it sending 2200K in the log now, but my bulbs don't seem to want to go below 2500k unless set in the app, I will check the Tapo integration, thank you.

**Comment by IIV-NATHAN-VII** [comment]
Can I ask, if I put all my bulbs in a group and some only support 2 of my 10 bulbs only go to 2500k (not 2200), would that also limit the others to 2500k?

Thanks.

**Comment by IIV-NATHAN-VII** [comment]
@basnijholt

**Comment by basnijholt** [comment]
If you put them in a Home Assistant light group, AL will expand them and treat them separately. So it won't limit the others.
