### ISSUE TITLE
Invalid Repository Error

### ISSUE THREAD

**Issue by willpuckett** [basnijholt/adaptive-lighting#70]
Hi,

when attempting to add the repo, I get "not a valid add-on repository."

The logs:

21-01-01 20:00:31 ERROR (MainThread) [supervisor.store] https://github.com/basnijholt/adaptive-lighting is not a valid add-on repository
21-01-01 20:00:32 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/87b06ca4/repository.json: [Errno 2] No such file or directory: '/data/addons/git/87b06ca4/repository.json'

Thanks buckets!

**Comment by Chreece** [comment]
Hey willpuckett,

This repo isn't suitable to add to the supervisor addons.
You should install first the addon HACS and then inside this addon you can add it.

More Info:
https://hacs.xyz/docs/installation/manual

**Comment by willpuckett** [comment]
Hi thanks Chreece. I worked it out the other night. Closing the issue thanks for the response.
