### ISSUE TITLE
New cutoff values for min_brightness and max_brightness 

### ISSUE THREAD

**Issue by haseat** [basnijholt/adaptive-lighting#72]
Hi,

right now the parameters `min_brightness` and `max_brightness` serve - when set - as new limits for the calculation of the actual brightness, e.g. when min_brightness is 80 and max_brightness is 100 and calculated brightness is 50, the actual brightness will be 90 (50% between 80 and 100). Is it possible to add new parameters which do not influence the calculation, but limit the return value?

pseudo-code:
```
if calculatedBrightness < minBrightness return(minBrightness)
if calculatedBrightness > maxBrightness return(maxBrightness)
return(calculatedBrightness)
```

min | 0 | 80 | 80
-- | -- | -- | --
max | 100 | 100 | 100
% | calculated | calculated now | should be
0 | 0 | 80 | 80
5 | 5 | 81 | 80
10 | 10 | 82 | 80
20 | 20 | 84 | 80
30 | 30 | 86 | 80
40 | 40 | 88 | 80
50 | 50 | 90 | 80
60 | 60 | 92 | 80
70 | 70 | 94 | 80
80 | 80 | 96 | 80
90 | 90 | 98 | 90
100 | 100 | 100 | 100

Thanks for this great addon!
Robert

**Comment by whig0** [comment]
This is exactly what I need.

**Comment by euinor** [comment]
I would vote for this - I would like to have the min/max settings behave as ceilings or floors for the brightness/colour graphs. Currently how they behave maintains the shape of the graph and just changes the Y Axis.

Someone on the forum suggested the settings 'absolute_(min/max)_(brightness/colour_temp)'

**Comment by RubenKelevra** [comment]
@haseat / @whig0 / @euinor 

Hey guys, I understand what you want - but I don't really get why. So the transition isn't fast enough in the morning/evening?

That would be https://github.com/basnijholt/adaptive-lighting/issues/62

Or is there something else that is the issue with the color temperature curve right now?

**Comment by euinor** [comment]
If I recall I wanted this to flatten the curve for colours, in order to fix the night or day colour to static, while keeping the dawn/dusk transition. If you have long nights or days it is good to have the night or day colour reached and then stay there. Currently it transitions slowly to the min/max value slowly throughout the evening or day.

So #62 might cover my wants, depending on what the conclusion was.

**Comment by th3w1zard1** [comment]
```
if calculatedBrightness < minBrightness return(minBrightness)
if calculatedBrightness > maxBrightness return(maxBrightness)
return(calculatedBrightness)
```

I didn't even see your pseudo code see this when I wrote this code to add this in:
```
if self.flat_limits:
    if percent * 100 > self.max_brightness:
        return self.max_brightness
    elif percent * 100 < self.min_brightness:
        return self.min_brightness
    return percent * 100
```

**Comment by basnijholt** [comment]
Check out the new `brightness_mode` feature introduced in 1.19.0: https://github.com/basnijholt/adaptive-lighting/blob/104664d3588442730f7ea9e811dd1986aca0c2e8/README.md#custom-brightness-ramps-using-brightness_mode-with-linear-and-tanh via https://github.com/basnijholt/adaptive-lighting/pull/699

This should give you enough control to change brightness precisely.

Some more examples:
Notice the values of `brightness_mode_time_light` and `brightness_mode_time_dark` in the text box.
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/15143580-13cd-4ab2-a603-89f2b7830afd)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/f61fdac9-6d47-48c9-84ed-cbb451d5de5d)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/e5fc5d27-3c37-4e3d-93d1-6e7cf4b48e7c)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/3dcbdc42-63c4-49df-8651-d2fae53dd08d)

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

![adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/assets/6897215/4e5cb08c-0327-40c2-8822-3095eb795358)

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f
