### ISSUE TITLE
adapt_only_on_bare_turn_on missing description in UI config

### ISSUE THREAD

**Issue by danielbrunt57** [basnijholt/adaptive-lighting#720]
# Home Assistant Adaptive Lighting Issue Template

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
V1.19.0b4
```
4.  Describe the bug and how to reproduce it:

![Screenshot_20230807_104504_Home Assistant](https://github.com/basnijholt/adaptive-lighting/assets/49846893/fbe53428-339d-4ed4-8642-2e61fdd96fda)

**Comment by basnijholt** [comment]
Thanks for reporting. It is very strange because it works for me. I strongly suspect because it’s due to cashing.

Which language do you have your Home Assistant set to?

I see this BTW
![IMG_3727](https://github.com/basnijholt/adaptive-lighting/assets/6897215/f9fcfe29-53bc-4000-8c02-812699a018a7)

**Comment by danielbrunt57** [comment]
Hmm...it's fine now, and my version is still 1.19.0b4.  I've had a couple of HA restarts since reporting that, plus a phone reboot so might have have been a weird caching issue somewhere...

My HA language is English (Canada).

**Comment by basnijholt** [comment]
OK good to know.

I don't think this is an issue specific to AL but rather HA, so I'll close it :)
