### ISSUE TITLE
Lonsonho ZB-RGBCW lamps do not work

### ISSUE THREAD

**Issue by bisquit2003** [basnijholt/adaptive-lighting#721]
i use all latest software

i have [2 lamps ](https://www.zigbee2mqtt.io/devices/ZB-RGBCW.html#lonsonho-zb-rgbcw) that stopped turning on from the ha interface if they are added to the integration. from z2m they are fully controlled. I noticed that you can turn them on and off if reduce and then add brightness. 
Everything was working correctly before.

**Comment by basnijholt** [comment]
I need to see some debugging logs because with this information I can’t help. 

I’ll reopen when you provide them 😃

**Comment by basnijholt** [comment]
Also which version was working and now I’m which version does it not work?

**Comment by bisquit2003** [comment]
> Also which version was working and now I’m which version does it not work?

I haven't been home for the last 2-3 weeks, but I've logged into the interface and updated it periodically, so now I can't say in which version it stopped working

**Comment by bisquit2003** [comment]
> I need to see some debugging logs because with this information I can’t help.
> 
> I’ll reopen when you provide them 😃

I’ll try to do it tomorrow

**Comment by basnijholt** [comment]
_Might_ be same as this issue https://github.com/basnijholt/adaptive-lighting/issues/726

**Comment by bisquit2003** [comment]
> _Might_ be same as this issue #726

1.19.0 dont fix my problem

**Comment by bisquit2003** [comment]
[debug.txt](https://github.com/basnijholt/adaptive-lighting/files/12313108/debug.txt)

**Comment by basnijholt** [comment]
@bisquit2003, thanks for sharing the logs, however, there doesn't seem to be anything strange in there.

You have only shared the logs of 0.037 seconds long.

I would need the logs that include the behavior of which you are talking about (the lamps not working).

**Comment by bisquit2003** [comment]
> @bisquit2003, thanks for sharing the logs, however, there doesn't seem to be anything strange in there.
> 
> You have only shared the logs of 0.037 seconds long.
> 
> I would need the logs that include the behavior of which you are talking about (the lamps not working).

The problem is that everything is displayed normally in the interface. That is, I press turn on the lamp and it turns on (in lovelace), but physically the lamp does not light up. And if I manually turn down the brightness and then add it, then the lamp starts working. And as soon as I exclude the lamp from integration, the real work and the display in the interface work the same way. I will try to record video for you

**Comment by bisquit2003** [comment]
> @bisquit2003, thanks for sharing the logs, however, there doesn't seem to be anything strange in there.
> 
> You have only shared the logs of 0.037 seconds long.
> 
> I would need the logs that include the behavior of which you are talking about (the lamps not working).

[Video for u](https://drive.google.com/file/d/1YM-L-S14uvjCvYCErS36vtVr_NoN_RkY/view?usp=drivesdk)

**Comment by bisquit2003** [comment]
[debug new.txt](https://github.com/basnijholt/adaptive-lighting/files/12320946/debug.new.txt)

**Comment by basnijholt** [comment]
Thanks!

What are the `enitity_id`s of the lights that are not working?

BTW, try setting `separate_turn_on_commands: true`. Some lights do not support setting both at the same time.

**Comment by bisquit2003** [comment]
/

> Thanks!
> 
> What are the `enitity_id`s of the lights that are not working?
> 
> BTW, try setting `separate_turn_on_commands: true`. Some lights do not support setting both at the same time.

light.nochnik_papa_2
light.nochnik_mama_2

“separate_turn_on_commands: true” Don’t fix problem

**Comment by basnijholt** [comment]
It looks like `light.nochnik_papa_2` is not part of the switch at all (not set up to use that one).

For `light.nochnik_mama_2` I see:
`14:09:30.357 Preparing adaptation data for light.nochnik_mama_2 with service data {'entity_id': 'light.nochnik_mama_2', 'transition': 1.0, 'brightness': 255, 'color_temp_kelvin': 5225}`

and then

`14:09:30.575 Detected a 'light.nochnik_mama_2' 'state_changed' event: '{'min_color_temp_kelvin': 2000, 'max_color_temp_kelvin': 6535, 'min_mireds': 153, 'max_mireds': 500, 'supported_color_modes': ['color_temp', 'xy'], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 255, 'color_temp_kelvin': 4000, 'color_temp': 250, 'hs_color': (26.812, 34.87), 'rgb_color': (255, 205, 166), 'xy_color': (0.421, 0.364), 'icon': 'mdi:globe-light', 'friendly_name': 'Ночник Мама', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01H7J4K0VGC0FQ52ZXGJMB26ZY'`

Which means it is trying to set the brightness and color_temp at the same time but fails because it becomes 4000 instead of 5225

**Comment by basnijholt** [comment]
Maybe it is related to the transition.

Can you set `transition: 0`?

**Comment by basnijholt** [comment]
It might be that this light cannot be turned on with any settings. For example read this: https://github.com/Koenkk/zigbee2mqtt/discussions/16430#discussioncomment-5500633

**Comment by basnijholt** [comment]
Can you try to put both lights in the same switch and turn off `multi_light_intercept` and then use a service call `light.turn_on` to turn both on at the same time (so with 2 entity_ids). 

If that works I might know a solution.

**Comment by bisquit2003** [comment]
> Can you try to put both lights in the same switch and turn off `multi_light_intercept` and then use a service call `light.turn_on` to turn both on at the same time (so with 2 entity_ids).
> 
> If that works I might know a solution.

Sorry, but it’s doesn’t work 😭

**Comment by bisquit2003** [comment]
> It might be that this light cannot be turned on with any settings. For example read this: [Koenkk/zigbee2mqtt#16430 (comment)](https://github.com/Koenkk/zigbee2mqtt/discussions/16430#discussioncomment-5500633)

These lamps worked fine in integration a few versions ago, but I can't download a version lower than 1.18, so I can't say exactly when it broke

**Comment by basnijholt** [comment]
Did you actually make the service call?

**Comment by bisquit2003** [comment]
> Did you actually make the service call?

Yes. Developer Panel-> Services->light.turn_on

**Comment by basnijholt** [comment]
Hmmm. Because that _should_ skip the interception and turn on the lights as if not in the integration. 

Since that doesn’t work I’m not about a solution ATM.

**Comment by bisquit2003** [comment]
> Hmmm. Because that _should_ skip the interception and turn on the lights as if not in the integration.
> 
> Since that doesn’t work I’m not about a solution ATM.

As soon as I exclude lamps from integration, they work correctly…

**Comment by bisquit2003** [comment]
Is it possible to enable the download of older versions of the integration, for verification? But after 22.08, because I went on vacation

**Comment by chewth91** [comment]
Hi, just updated to latest version yesterday from 1.15 and the same light could not turn on via HA, it only works by removing the entities from adaptive lighting. Was working fine before.

**Comment by basnijholt** [comment]
@chewth91, do you also have these Lonsonho lights?

**Comment by basnijholt** [comment]
@bisquit2003, I opened https://github.com/basnijholt/adaptive-lighting/pull/750 which makes the intercept configurable.

This should fix your issue. Disable `intercept`.

**Comment by bisquit2003** [comment]
> @bisquit2003, I opened #750 which makes the intercept configurable.
> 
> This should fix your issue. Disable `intercept`.

Thanks, I'll check it out when I get back from vacation.

**Comment by bisquit2003** [comment]
> @bisquit2003, I opened #750 which makes the intercept configurable.
> 
> This should fix your issue. Disable `intercept`.

Do I need to make a separate entry in the integration for these lamps, or can I use a common one, as it was before?

**Comment by basnijholt** [comment]
You can use a common one but that will result in the lights that were functioning before, not immediately adapting. So for a best user experience I would create 2 switches.

**Comment by basnijholt** [comment]
@bisquit2003, it would be really great that once you try it out, if you could report back, because then I will add something to the README about these lamps in https://github.com/basnijholt/adaptive-lighting/pull/756.

**Comment by chewth91** [comment]
> @chewth91, do you also have these Lonsonho lights?

Yes i have 2 and they acted differently under adaptive lighting. I had separated them with different settings and now can be turned on via HA. They were managed under HA Light groups previously.

**Comment by basnijholt** [comment]
@chewth91, did disabling intercept do the trick for you?

**Comment by chewth91** [comment]
> @chewth91, did disabling intercept do the trick for you?

Hi, it is working well for now.  That works as well for my WW/CW light ZB-CT01 from YSRSAI. 
Thanks!

**Comment by bisquit2003** [comment]
Hello.
I connected these lamps via zha, they were identified under a different name (eWeLight ZB-CL01) and this problem does not manifest itself, regardless of intercept

**Comment by basnijholt** [comment]
@all-contributors please add @bisquit2003 for bug

**Comment by basnijholt** [comment]
@all-contributors please add @chewth91 for bug
