### ISSUE TITLE
Offset and manual time control seems not working

### ISSUE THREAD

**Issue by kingii98** [basnijholt/adaptive-lighting#77]
When I am trying to change sunrise and/or sunset time it doesn't change anything. I was trying to set offset to 43200 seconds which is 12 hours but it behaves the same as integration without the offset.

**Comment by Jopinder** [comment]
I'm seeing the same issue. I turn off Sleep mode automatically 06:30:00, but no matter what I set the sunrise_time to, AL keeps the lights dimmed until the actual sunrise.

**Comment by basnijholt** [comment]
I find this very unexpected.

Could you guys share the logs?

**Comment by Jopinder** [comment]
Unfortunately this is going to be a rather long output from the debug-log. Is there some way to limit the debug to a single AL-instance?

Adaptive Lighting: Hallway (light.hallway_ceiling) settings:
min_brightness: 75%
max_brightness: 100%
sleep_brightness: 1%
sunrise_time: 06:00:00
sunrise_offset: 0
sunset_time_ None
sunset_offset: 0
take_over_control: marked

Timeline:
06:13:36 - light.hallway_ceiling turned on by HA when opening door.
06:30:00 - Adaptive Lighting Sleep Mode: Hallway (and all other Sleep mode switches) are turned off by HA (time-trigger)
07:11:53 - HA switches themes when (start of?) sunrise happens.
07:13:20 - Lights gets correct brightness

AL manages to set the correct color temperature when turning off sleep mode, it's only the brightness that's off. Even if it's not supposed to be 100% at sunrise the lights are way below the min_brightness: 75% I've set.

The bulbs affected are [Ikea TRÅDFRI LED bulb E27 1000 lumen](https://www.ikea.com/gb/en/p/tradfri-led-bulb-e27-1000-lumen-wireless-dimmable-white-spectrum-globe-opal-white-60408483/) 

[debug.txt](https://github.com/basnijholt/adaptive-lighting/files/6066525/debug.txt)

**Comment by Jopinder** [comment]
Same behavior today, except this time the lights in the living room managed to get the correct brightness while the hallway waited until sunrise....

Timeline:
7:11:38 AM - Hallway got correct brightness
7:11:06 AM - Daylight changed to sunrise_start
7:09:01 AM - Light theme after Sunrise has been triggered by sunrise
7:09:01 AM - Sun rose
6:42:59 AM - Livingroom Window Middle turned on by Tablet
6:42:59 AM - Livingroom Couch Right turned on by Tablet
6:42:59 AM - Couch turned on by Tablet
6:42:59 AM - Livingroom Couch Left turned on by Tablet
6:42:59 AM - Spotlight window turned on by Tablet
6:42:59 AM - Living room turned on by Tablet
6:42:59 AM - Livingroom Window Left turned on by Tablet
6:42:59 AM - Livingroom Window Right turned on by Tablet
6:30:00 AM - Sleep Mode turned off by Hass.io
6:29:26 AM - Daylight changed to dawn
6:18:13 AM - Hallway Ceiling turned on by Hass.io
6:18:13 AM - Door was opened

[debug 03.03.21.txt](https://github.com/basnijholt/adaptive-lighting/files/6073974/debug.03.03.21.txt)

**Comment by Jopinder** [comment]
Tried turning on the lights after HA switches off sleep-mode, and all lights worked as expected.
6:30:00 AM - Sleep Mode turned off by Hass.io
6:41:17 AM - Hallway turned on by door opening, normal brightness
6:54:47 AM - Living room turned on, normal brightness

[debug 04.03.21.txt](https://github.com/basnijholt/adaptive-lighting/files/6081206/debug.04.03.21.txt)

**Comment by RubenKelevra** [comment]
Hey @kingii98,  @Jopinder,

can you please reconfirm this issue with a recent version of HA? Thanks!

**Comment by Jopinder** [comment]
Updating now, but as I'm on vacation I'm unsure when I'll get around to test it.

**Comment by th3w1zard1** [comment]
Is anyone still having this issue on the latest version 1.7.0?

**Comment by basnijholt** [comment]
I am going to assume that this issue has been fixed in the last 2 years, so I will close this issue.

We have a lot of tests now that test this functionality, so I would be very surprised if the manual sunrise/sunset times aren't working.
