### ISSUE TITLE
Tradfri Bulbs stopped adapting 

### ISSUE THREAD

**Issue by DuzAwe** [basnijholt/adaptive-lighting#835]
# Home Assistant Adaptive Lighting Issue Template

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [ X ] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [ X ] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ X ] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ X ] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

[home-assistant_adaptive_lighting_2023-11-08T20-34-54.069Z.log](https://github.com/basnijholt/adaptive-lighting/files/13301208/home-assistant_adaptive_lighting_2023-11-08T20-34-54.069Z.log)

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

![ad2](https://github.com/basnijholt/adaptive-lighting/assets/2813049/7cf2a6a7-ed00-4796-a6bd-98153eddd2bb)
![ad3](https://github.com/basnijholt/adaptive-lighting/assets/2813049/e8ac3fae-1693-49db-b97a-bfc7baa19b31)
![ad4](https://github.com/basnijholt/adaptive-lighting/assets/2813049/c799e255-ede4-462e-a856-10e9531452b4)
![ad1](https://github.com/basnijholt/adaptive-lighting/assets/2813049/00e0866b-78eb-439b-a52f-7989e9a362a6)

4.  Describe the bug and how to reproduce it:

No adaptation. Functionally everything you would do to have brightness or temp change  isn't working. 

5. Steps to reproduce the behavior:
Turn light on, off, wait for the passage of time., enable sleep mode. No adaptation.

**Comment by patrickc-sb** [comment]
I think I'm having the same issue. Which switch exactly did fix this for you?
Cant seem to find the right one

**Comment by basnijholt** [comment]
See the list of 4 switches here: https://github.com/basnijholt/adaptive-lighting?tab=readme-ov-file#bulb-features
