### ISSUE TITLE
brightness_mode_time_dark vs brightness_mode_time_light

### ISSUE THREAD

**Issue by henfri** [basnijholt/adaptive-lighting#905]
#### Location

Readme.md

#### Description
The Documentation and the GUI (incl German Translation) do Not explain the difference between

brightness_mode_time_dark	(Ignored if brightness_mode='default') The duration in seconds to ramp up/down the brightness before/after sunrise/sunset. 📈📉	900	int

brightness_mode_time_light	(Ignored if brightness_mode='default') The duration in seconds to ramp up/down the brightness after/before sunrise/sunset

I suspect:
brightness_mode_time_dark	(Ignored if brightness_mode='default') The duration in seconds to ramp **down** the brightness **after** sunrise/sunset. 📈📉	900	int

brightness_mode_time_light	(Ignored if brightness_mode='default') The duration in seconds to ramp **up** the brightness **before** sunrise/sunset

Greetings,

Hendrik

**Comment by basnijholt** [comment]
It is correct in the description but perhaps not entirely clear. 

`brightness_mode_time_dark` for example means the time before sunrise and the time after sunset. So the time that it is dark, moving to daylight in the morning and moving to darkness after sunset.

If you have suggestion for a better description, feel free to share! One requirement is that it should be brief.

**Comment by basnijholt** [comment]
Try the webapp here https://basnijholt.github.io/adaptive-lighting/

I think when you see the effects it will make sense.

**Comment by henfri** [comment]
It is clearer now. But I have no better wording...

**Comment by StSaens** [comment]
brightness_mode_time_dark: the time in seconds before sunrise and the time after sunset. (while sun is below the horizon)

brightness_mode_time_light: the time in seconds after sunrise and the time before sunset. (while sun is above the horizon)
