### ISSUE TITLE
Assert-error in HA LOG regularly

### ISSUE THREAD

**Issue by bouwew** [basnijholt/adaptive-lighting#919]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ ] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```

```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```

```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:
![image](https://github.com/basnijholt/adaptive-lighting/assets/11290930/b9eac4ec-2ac6-42e4-9e6e-76b29237f42b)

5. Steps to reproduce the behavior:

**Comment by th3w1zard1** [comment]
You've left half of the issue template blank, please fill in the missing details so we can properly help you.

**Comment by bouwew** [comment]
Yeah I know, to much information to add :)

Anyway, I fixed the error myself in the local code, it was just a mistake in what to assert.

Switch.py line 1419 should read: `assert isinstance(adapt_color, bool | None)` in line with the `init` of  in line 1243: `adapt_color: bool | None = None`
Also, line 1418 should be corrected as `adapt_brightness` is also inited as `bool | None`.

**Comment by bouwew** [comment]
After capturing some logging, it turns out the error is caused by a light that is no longer present in HA.
