### ISSUE TITLE
config options to adjust brightness profile shape

### ISSUE THREAD

**Issue by edgimar** [basnijholt/adaptive-lighting#94]
It would be nice if there were a brightness scale-factor that causes the 'normal' computed brightness-percent value `X` to be replaced by `max(round(s*X), min_brightness)`, where `s` is the scale factor.

OR

if you want to get fancy, you could allow the user to choose either of the following:

1. a single (time, brightness) pair, which would be used to automatically choose an appropriate amplitude scale factor under the assumption that the "width" and "center" of the brightness profile does not change.
2. two (time, brightness) pairs that are on either side of the "center" time, which would be used to adjust the position/shape of the profile to fit both points.

**Comment by edgimar** [comment]
One correction: the "brightness scale-factor" should only affect the delta from the max brightness.  In other words, the [`calc_brightness_pct`](https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L1084) function should return the following:
```python
return max(self.brightness - round(brightness_scale_factor*(delta_brightness * percent)), self.min_brightness)
```

**Comment by RubenKelevra** [comment]
Hey @edgimar,

can you explain your use case and why this would help you? :)

**Comment by edgimar** [comment]
Yes I seen to have left out that key piece of info!  I am already using the 'brightness scale factor' change locally, and the reason is because otherwise the brightness values never get low enough to make my bulbs as dim as I'd like at the times I want them dim.

**Comment by basnijholt** [comment]
Check out the new `brightness_mode` feature introduced in 1.19.0: https://github.com/basnijholt/adaptive-lighting/blob/104664d3588442730f7ea9e811dd1986aca0c2e8/README.md#custom-brightness-ramps-using-brightness_mode-with-linear-and-tanh via https://github.com/basnijholt/adaptive-lighting/pull/699

This should give you enough control to separate brightness and color.

Some more examples:
Notice the values of `brightness_mode_time_light` and `brightness_mode_time_dark` in the text box.
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/15143580-13cd-4ab2-a603-89f2b7830afd)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/f61fdac9-6d47-48c9-84ed-cbb451d5de5d)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/e5fc5d27-3c37-4e3d-93d1-6e7cf4b48e7c)
![image](https://github.com/basnijholt/adaptive-lighting/assets/6897215/3dcbdc42-63c4-49df-8651-d2fae53dd08d)

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

![adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/assets/6897215/4e5cb08c-0327-40c2-8822-3095eb795358)

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f
