### ISSUE TITLE
Transiton doesn't work - lights change hoiourly

### ISSUE THREAD

**Issue by JohnMcIl** [basnijholt/adaptive-lighting#952]
The lights are meant to constantly transition.

They don't.

They only fade every one hour, and the transition is very noticeable.

Please help…

**Comment by th3w1zard1** [comment]
Issue threads that do not provide the details the issue template requests will be deleted. This was mentioned in the issue template you so blatantly deleted.

Try asking in [discussions](https://github.com/basnijholt/adaptive-lighting/discussions) if you don't have a bug to report.
