### ISSUE TITLE
Problems with zigbee2mqtt 1.34.0 and above

### ISSUE THREAD

**Issue by djcrawleravp** [basnijholt/adaptive-lighting#975]
After updating to any zigbee2mqtt version above 1.33.1 my adaptive lighting won't work.

My automations are as follows:

1. When presence is detected turn on the lights or disable sleep mode if the lights are already on (activates adaptive lighting)
2. When presence is not detected turns on sleep mode for 30 secs after that it shuts off the lights

After upgrading to 1.34.1+ my lights starts in sleep mode and sometimes after a couple of minutes starts the adaptive mode sometimes stays at sleep mode

I've been waiting for new versions of Zigbee2Mqtt but every time I update to the new last version I get the same result and have to rollback to 1.33.1

I even have tried several Zigbee firmwares.

I'm putting this in here because is my only reason for being stuck at Z2M 1.33.1, everything else works fine
On Z2M repo they told me to address this issue in here :/

Any help is much appreciated

**Comment by DubhAd** [comment]
For what it's worth I'm on Z2M 1.35.3 and don't see this problem.

**Comment by djcrawleravp** [comment]
I have several LIght groups on Z2M (1.33.1) I'll show you one of them:

Adaptive Light Config:
<img width="593" alt="Screen Shot 2024-04-12 at 14 34 55" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/4c07ec4f-fe80-4979-866b-053fdc54e260">
<img width="596" alt="Screen Shot 2024-04-12 at 14 35 03" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/56699c8a-168c-4072-b5a6-6577928f4b96">
<img width="580" alt="Screen Shot 2024-04-12 at 14 35 09" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/770bee6d-2124-4db1-be1a-0a0ceaa38c85">
<img width="591" alt="Screen Shot 2024-04-12 at 14 35 17" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/0042bc56-ac29-49bd-aaf0-bb320a0942fe">
<img width="592" alt="Screen Shot 2024-04-12 at 14 35 22" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/e508b6ee-3284-44d4-ba1b-f88b9357a33b">

On node Red I have this config (I hope spanish makes some sense):

<img width="1491" alt="Screen Shot 2024-04-12 at 14 36 46" src="https://github.com/basnijholt/adaptive-lighting/assets/12896341/b9725ad2-4fa2-43dc-b035-608691d2fc27">

For some Reason I can go above 1.33.1

**Comment by djcrawleravp** [comment]
Still on Z2M 1.33.1 beacause of this, When switching to later varsions when My light is triggered it stays in sleep mode, sometimes the light adapts well, sometimes the lights take like 2-3 minutoes to adapt

**Comment by djcrawleravp** [comment]
The problem is on Zigbee2Mqtt Side.. the converter from 1.34.0 and above is a different one.

I already opened a new [issue](https://github.com/Koenkk/zigbee2mqtt/issues/22676) asking if is possible to use the old external converter
