### ISSUE TITLE
Manual control when light becomes unavailable

### ISSUE THREAD

**Issue by Alfiegerner** [basnijholt/adaptive-lighting#98]
Hi,

Love this intergation, thanks very much for all your efforts.

I have an issue that some of my esphome smart bulbs can be become unavailable from time to time.  When that happens the integration appears to register that manual control has been taken they return online.  Which makes total sense, as a new light-on event has been registered, without an off event.

So in my example, I have 3 bulbs in a set controlled by adaptive lighting, one of them is unreliable.  The two 'good ones' do nice circardian lighting.  The third slightly occasionally unavailable bulb is often start white in the evening.

For now I've turned off the manual control bit toggle and they work great, but ideally would love to keep that.

Would it be possible to mark on light-on events after unavailable as 'system' rather than 'manual' control, and let adaptive lighting push changes?  

Thanks very much.

**Comment by broyuken** [comment]
Why not just make an automation that if the light goes from unavailable -> on, then set manual control false

**Comment by Alfiegerner** [comment]
@broyuken thank you for that - probably missing something simple but how would I say manual control to false?

**Comment by broyuken** [comment]
Look at the main page under adaptive_lighting.set_manual_control

**Comment by Alfiegerner** [comment]
Gah, thanks!
