### ISSUE TITLE
Deprecation warning in 2024.5.0b1

### ISSUE THREAD

**Issue by dcmeglio** [basnijholt/adaptive-lighting#984]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [X] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [X] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 1665: self.hass.bus.async_listen(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 1670: self.hass.bus.async_listen(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
Detected that custom integration 'adaptive_lighting' calls `async_listen_once` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 958: self.hass.bus.async_listen_once(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

N/A running 1.21.1

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
N/A

4.  Describe the bug and how to reproduce it:
Upgrade to 2024.5.X, this is a new deprecation warning . Check logs. This is a new deprecation warning being added to 2024.5

5. Steps to reproduce the behavior:
Upgrade to 2024.5.X, this is a new deprecation warning . Check logs

**Comment by basnijholt** [comment]
Fixed by #991
