### ISSUE TITLE
Error: Config Flow could not be loaded

### ISSUE THREAD

**Issue by danielbrunt57** [basnijholt/adaptive-lighting#99]
New AL integrations cannot be added - Error: Config Flow could not be loaded
Existing integrations have no edit option.

Latest HA Version 2021.3.1

**Comment by basnijholt** [comment]
I have just updated but I do not observe the same issue. 

Did you set up everything via the UI or YAML?

**Comment by danielbrunt57** [comment]
I've resolved it via re-installing the integration from HACS.
